//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// File generated on 09/08/2017 12:50:28
namespace LeapMotionSample
{
    using System;
    
    
    public sealed class WaveContent
    {
        
        /// <summary> Path to Content/LeapMotionSample.wgame </summary>
        public const string GameInfo = "Content/LeapMotionSample.wgame";
        
        public sealed class Scenes
        {
            
            /// <summary> Path to Content/Scenes/MyScene.wscene </summary>
            public const string MyScene = "Content/Scenes/MyScene.wscene";
        }
    }
}
