//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// File generated on 11/10/2015 10:50:08 AM
namespace DolbySample
{
    using System;
    
    
    public sealed class WaveContent
    {
        
        public sealed class Assets
        {
            
            /// <summary> Path to Content/Assets/audiodolby.mp3 </summary>
            public const string audiodolby_mp3 = "Content/Assets/audiodolby.mp3";
            
            /// <summary> Path to Content/Assets/background.png </summary>
            public const string background_png = "Content/Assets/background.png";
            
            /// <summary> Path to Content/Assets/logo.png </summary>
            public const string logo_png = "Content/Assets/logo.png";
            
            /// <summary> Path to Content/Assets/speakera.png </summary>
            public const string speakera_png = "Content/Assets/speakera.png";
            
            /// <summary> Path to Content/Assets/speakerb.png </summary>
            public const string speakerb_png = "Content/Assets/speakerb.png";
        }
        
        public sealed class Scenes
        {
            
            /// <summary> Path to Content/Scenes/ButtonsScene.wscene </summary>
            public const string ButtonsScene = "Content/Scenes/ButtonsScene.wscene";
            
            /// <summary> Path to Content/Scenes/UIScene.wscene </summary>
            public const string UIScene = "Content/Scenes/UIScene.wscene";
        }
    }
}
