//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// File generated on 10/08/2017 12:42:08
namespace WaveOculusDemo
{
    using System;
    
    
    public sealed class WaveContent
    {
        
        /// <summary> Path to Content/WaveOculusDemo.wgame </summary>
        public const string GameInfo = "Content/WaveOculusDemo.wgame";
        
        public sealed class Assets
        {
            
            public sealed class Materials
            {
                
                /// <summary> Path to Content/Assets/Materials/AsteroidMat.wmat </summary>
                public const string AsteroidMat = "Content/Assets/Materials/AsteroidMat.wmat";
                
                /// <summary> Path to Content/Assets/Materials/BlasterMat.wmat </summary>
                public const string BlasterMat = "Content/Assets/Materials/BlasterMat.wmat";
                
                /// <summary> Path to Content/Assets/Materials/BlasterMatVC.wmat </summary>
                public const string BlasterMatVC = "Content/Assets/Materials/BlasterMatVC.wmat";
                
                /// <summary> Path to Content/Assets/Materials/BlueLaserMat.wmat </summary>
                public const string BlueLaserMat = "Content/Assets/Materials/BlueLaserMat.wmat";
                
                /// <summary> Path to Content/Assets/Materials/CockpitMat.wmat </summary>
                public const string CockpitMat = "Content/Assets/Materials/CockpitMat.wmat";
                
                /// <summary> Path to Content/Assets/Materials/EnemyFighterGlowMat.wmat </summary>
                public const string EnemyFighterGlowMat = "Content/Assets/Materials/EnemyFighterGlowMat.wmat";
                
                /// <summary> Path to Content/Assets/Materials/EnemyFighterMat.wmat </summary>
                public const string EnemyFighterMat = "Content/Assets/Materials/EnemyFighterMat.wmat";
                
                /// <summary> Path to Content/Assets/Materials/EnemyThrustMat.wmat </summary>
                public const string EnemyThrustMat = "Content/Assets/Materials/EnemyThrustMat.wmat";
                
                /// <summary> Path to Content/Assets/Materials/EnemyTrailMat.wmat </summary>
                public const string EnemyTrailMat = "Content/Assets/Materials/EnemyTrailMat.wmat";
                
                /// <summary> Path to Content/Assets/Materials/FighterGlowMat.wmat </summary>
                public const string FighterGlowMat = "Content/Assets/Materials/FighterGlowMat.wmat";
                
                /// <summary> Path to Content/Assets/Materials/FighterMat.wmat </summary>
                public const string FighterMat = "Content/Assets/Materials/FighterMat.wmat";
                
                /// <summary> Path to Content/Assets/Materials/LaunchBaseGlowMat.wmat </summary>
                public const string LaunchBaseGlowMat = "Content/Assets/Materials/LaunchBaseGlowMat.wmat";
                
                /// <summary> Path to Content/Assets/Materials/LaunchBaseMat.wmat </summary>
                public const string LaunchBaseMat = "Content/Assets/Materials/LaunchBaseMat.wmat";
                
                /// <summary> Path to Content/Assets/Materials/PlanetMat.wmat </summary>
                public const string PlanetMat = "Content/Assets/Materials/PlanetMat.wmat";
                
                /// <summary> Path to Content/Assets/Materials/StarFieldMat.wmat </summary>
                public const string StarFieldMat = "Content/Assets/Materials/StarFieldMat.wmat";
                
                /// <summary> Path to Content/Assets/Materials/StarShineMat1.wmat </summary>
                public const string StarShineMat1 = "Content/Assets/Materials/StarShineMat1.wmat";
                
                /// <summary> Path to Content/Assets/Materials/StarShineMat2.wmat </summary>
                public const string StarShineMat2 = "Content/Assets/Materials/StarShineMat2.wmat";
                
                /// <summary> Path to Content/Assets/Materials/ThrustMat.wmat </summary>
                public const string ThrustMat = "Content/Assets/Materials/ThrustMat.wmat";
                
                /// <summary> Path to Content/Assets/Materials/TrailsMat.wmat </summary>
                public const string TrailsMat = "Content/Assets/Materials/TrailsMat.wmat";
                
                public sealed class Explosion
                {
                    
                    /// <summary> Path to Content/Assets/Materials/Explosion/Explosion_1.wmat </summary>
                    public const string Explosion_1 = "Content/Assets/Materials/Explosion/Explosion_1.wmat";
                    
                    /// <summary> Path to Content/Assets/Materials/Explosion/Explosion_2.wmat </summary>
                    public const string Explosion_2 = "Content/Assets/Materials/Explosion/Explosion_2.wmat";
                    
                    /// <summary> Path to Content/Assets/Materials/Explosion/Explosion_3.wmat </summary>
                    public const string Explosion_3 = "Content/Assets/Materials/Explosion/Explosion_3.wmat";
                    
                    /// <summary> Path to Content/Assets/Materials/Explosion/Explosion_5.wmat </summary>
                    public const string Explosion_5 = "Content/Assets/Materials/Explosion/Explosion_5.wmat";
                    
                    /// <summary> Path to Content/Assets/Materials/Explosion/Explosion_Ring.wmat </summary>
                    public const string Explosion_Ring = "Content/Assets/Materials/Explosion/Explosion_Ring.wmat";
                }
                
                public sealed class Hud
                {
                    
                    /// <summary> Path to Content/Assets/Materials/Hud/HudRadarMat.wmat </summary>
                    public const string HudRadarMat = "Content/Assets/Materials/Hud/HudRadarMat.wmat";
                    
                    /// <summary> Path to Content/Assets/Materials/Hud/Hud_1Mat.wmat </summary>
                    public const string Hud_1Mat = "Content/Assets/Materials/Hud/Hud_1Mat.wmat";
                    
                    /// <summary> Path to Content/Assets/Materials/Hud/RadarTickMat.wmat </summary>
                    public const string RadarTickMat = "Content/Assets/Materials/Hud/RadarTickMat.wmat";
                }
            }
            
            public sealed class Models
            {
                
                /// <summary> Path to Content/Assets/Models/Cockpit.fbx </summary>
                public const string Cockpit_fbx = "Content/Assets/Models/Cockpit.fbx";
                
                /// <summary> Path to Content/Assets/Models/EnemyFighter.fbx </summary>
                public const string EnemyFighter_fbx = "Content/Assets/Models/EnemyFighter.fbx";
                
                /// <summary> Path to Content/Assets/Models/Fighter.fbx </summary>
                public const string Fighter_fbx = "Content/Assets/Models/Fighter.fbx";
                
                /// <summary> Path to Content/Assets/Models/LaunchBase.fbx </summary>
                public const string LaunchBase_fbx = "Content/Assets/Models/LaunchBase.fbx";
                
                /// <summary> Path to Content/Assets/Models/Plane.fbx </summary>
                public const string Plane_fbx = "Content/Assets/Models/Plane.fbx";
                
                /// <summary> Path to Content/Assets/Models/Planet.fbx </summary>
                public const string Planet_fbx = "Content/Assets/Models/Planet.fbx";
                
                public sealed class Asteroids
                {
                    
                    /// <summary> Path to Content/Assets/Models/Asteroids/Asteroids_0_0.FBX </summary>
                    public const string Asteroids_0_0_FBX = "Content/Assets/Models/Asteroids/Asteroids_0_0.FBX";
                    
                    /// <summary> Path to Content/Assets/Models/Asteroids/Asteroids_0_1.FBX </summary>
                    public const string Asteroids_0_1_FBX = "Content/Assets/Models/Asteroids/Asteroids_0_1.FBX";
                    
                    /// <summary> Path to Content/Assets/Models/Asteroids/Asteroids_0_2.FBX </summary>
                    public const string Asteroids_0_2_FBX = "Content/Assets/Models/Asteroids/Asteroids_0_2.FBX";
                    
                    /// <summary> Path to Content/Assets/Models/Asteroids/Asteroids_1_0.FBX </summary>
                    public const string Asteroids_1_0_FBX = "Content/Assets/Models/Asteroids/Asteroids_1_0.FBX";
                    
                    /// <summary> Path to Content/Assets/Models/Asteroids/Asteroids_1_1.FBX </summary>
                    public const string Asteroids_1_1_FBX = "Content/Assets/Models/Asteroids/Asteroids_1_1.FBX";
                    
                    /// <summary> Path to Content/Assets/Models/Asteroids/Asteroids_1_2.FBX </summary>
                    public const string Asteroids_1_2_FBX = "Content/Assets/Models/Asteroids/Asteroids_1_2.FBX";
                    
                    /// <summary> Path to Content/Assets/Models/Asteroids/Asteroids_2_0.FBX </summary>
                    public const string Asteroids_2_0_FBX = "Content/Assets/Models/Asteroids/Asteroids_2_0.FBX";
                    
                    /// <summary> Path to Content/Assets/Models/Asteroids/Asteroids_2_1.FBX </summary>
                    public const string Asteroids_2_1_FBX = "Content/Assets/Models/Asteroids/Asteroids_2_1.FBX";
                    
                    /// <summary> Path to Content/Assets/Models/Asteroids/Asteroids_2_2.FBX </summary>
                    public const string Asteroids_2_2_FBX = "Content/Assets/Models/Asteroids/Asteroids_2_2.FBX";
                }
                
                public sealed class Hud
                {
                    
                    /// <summary> Path to Content/Assets/Models/Hud/HudRadarRotation1.FBX </summary>
                    public const string HudRadarRotation1_FBX = "Content/Assets/Models/Hud/HudRadarRotation1.FBX";
                    
                    /// <summary> Path to Content/Assets/Models/Hud/HudRadarRotation2.FBX </summary>
                    public const string HudRadarRotation2_FBX = "Content/Assets/Models/Hud/HudRadarRotation2.FBX";
                    
                    /// <summary> Path to Content/Assets/Models/Hud/HudRadarRotation3.FBX </summary>
                    public const string HudRadarRotation3_FBX = "Content/Assets/Models/Hud/HudRadarRotation3.FBX";
                    
                    /// <summary> Path to Content/Assets/Models/Hud/HudRadarStatic.FBX </summary>
                    public const string HudRadarStatic_FBX = "Content/Assets/Models/Hud/HudRadarStatic.FBX";
                    
                    /// <summary> Path to Content/Assets/Models/Hud/HudRadarTick.FBX </summary>
                    public const string HudRadarTick_FBX = "Content/Assets/Models/Hud/HudRadarTick.FBX";
                    
                    /// <summary> Path to Content/Assets/Models/Hud/HudRotation.FBX </summary>
                    public const string HudRotation_FBX = "Content/Assets/Models/Hud/HudRotation.FBX";
                    
                    /// <summary> Path to Content/Assets/Models/Hud/HudStatic.FBX </summary>
                    public const string HudStatic_FBX = "Content/Assets/Models/Hud/HudStatic.FBX";
                }
            }
            
            public sealed class Music
            {
                
                /// <summary> Path to Content/Assets/Music/music.mp3 </summary>
                public const string music_mp3 = "Content/Assets/Music/music.mp3";
            }
            
            public sealed class Paths
            {
                
                /// <summary> Path to Content/Assets/Paths/EnemyFighter.txt </summary>
                public const string EnemyFighter_txt = "Content/Assets/Paths/EnemyFighter.txt";
                
                /// <summary> Path to Content/Assets/Paths/Enemy_Lasers.txt </summary>
                public const string Enemy_Lasers_txt = "Content/Assets/Paths/Enemy_Lasers.txt";
                
                /// <summary> Path to Content/Assets/Paths/Fighter1_Lasers.txt </summary>
                public const string Fighter1_Lasers_txt = "Content/Assets/Paths/Fighter1_Lasers.txt";
                
                /// <summary> Path to Content/Assets/Paths/Fighter2_Lasers.txt </summary>
                public const string Fighter2_Lasers_txt = "Content/Assets/Paths/Fighter2_Lasers.txt";
                
                /// <summary> Path to Content/Assets/Paths/Fighter_1.txt </summary>
                public const string Fighter_1_txt = "Content/Assets/Paths/Fighter_1.txt";
                
                /// <summary> Path to Content/Assets/Paths/Fighter_2.txt </summary>
                public const string Fighter_2_txt = "Content/Assets/Paths/Fighter_2.txt";
            }
            
            public sealed class Sounds
            {
                
                /// <summary> Path to Content/Assets/Sounds/engines_1.wav </summary>
                public const string engines_1_wav = "Content/Assets/Sounds/engines_1.wav";
                
                /// <summary> Path to Content/Assets/Sounds/engines_2.wav </summary>
                public const string engines_2_wav = "Content/Assets/Sounds/engines_2.wav";
                
                /// <summary> Path to Content/Assets/Sounds/explosion.wav </summary>
                public const string explosion_wav = "Content/Assets/Sounds/explosion.wav";
                
                /// <summary> Path to Content/Assets/Sounds/shoot_1.wav </summary>
                public const string shoot_1_wav = "Content/Assets/Sounds/shoot_1.wav";
                
                /// <summary> Path to Content/Assets/Sounds/shoot_2.wav </summary>
                public const string shoot_2_wav = "Content/Assets/Sounds/shoot_2.wav";
                
                /// <summary> Path to Content/Assets/Sounds/shoot_3.wav </summary>
                public const string shoot_3_wav = "Content/Assets/Sounds/shoot_3.wav";
            }
            
            public sealed class Textures
            {
                
                /// <summary> Path to Content/Assets/Textures/Blaster.png </summary>
                public const string Blaster_png = "Content/Assets/Textures/Blaster.png";
                
                /// <summary> Path to Content/Assets/Textures/Cockpit.png </summary>
                public const string Cockpit_png = "Content/Assets/Textures/Cockpit.png";
                
                /// <summary> Path to Content/Assets/Textures/enemyfighter_diffuse.jpg </summary>
                public const string enemyfighter_diffuse_jpg = "Content/Assets/Textures/enemyfighter_diffuse.jpg";
                
                /// <summary> Path to Content/Assets/Textures/enemyfighter_normal.png </summary>
                public const string enemyfighter_normal_png = "Content/Assets/Textures/enemyfighter_normal.png";
                
                /// <summary> Path to Content/Assets/Textures/enemyfighter_spec.png </summary>
                public const string enemyfighter_spec_png = "Content/Assets/Textures/enemyfighter_spec.png";
                
                /// <summary> Path to Content/Assets/Textures/EnemyThrust.png </summary>
                public const string EnemyThrust_png = "Content/Assets/Textures/EnemyThrust.png";
                
                /// <summary> Path to Content/Assets/Textures/EnemyTrail.png </summary>
                public const string EnemyTrail_png = "Content/Assets/Textures/EnemyTrail.png";
                
                /// <summary> Path to Content/Assets/Textures/fighter_diffuse.png </summary>
                public const string fighter_diffuse_png = "Content/Assets/Textures/fighter_diffuse.png";
                
                /// <summary> Path to Content/Assets/Textures/fighter_normal.png </summary>
                public const string fighter_normal_png = "Content/Assets/Textures/fighter_normal.png";
                
                /// <summary> Path to Content/Assets/Textures/fighter_spec.png </summary>
                public const string fighter_spec_png = "Content/Assets/Textures/fighter_spec.png";
                
                /// <summary> Path to Content/Assets/Textures/planet.png </summary>
                public const string planet_png = "Content/Assets/Textures/planet.png";
                
                /// <summary> Path to Content/Assets/Textures/Skybox.cubemap </summary>
                public const string Skybox_cubemap = "Content/Assets/Textures/Skybox.cubemap";
                
                /// <summary> Path to Content/Assets/Textures/spacestation_diffuse.jpg </summary>
                public const string spacestation_diffuse_jpg = "Content/Assets/Textures/spacestation_diffuse.jpg";
                
                /// <summary> Path to Content/Assets/Textures/spacestation_glow.jpg </summary>
                public const string spacestation_glow_jpg = "Content/Assets/Textures/spacestation_glow.jpg";
                
                /// <summary> Path to Content/Assets/Textures/spacestation_normal.png </summary>
                public const string spacestation_normal_png = "Content/Assets/Textures/spacestation_normal.png";
                
                /// <summary> Path to Content/Assets/Textures/spacestation_spec.png </summary>
                public const string spacestation_spec_png = "Content/Assets/Textures/spacestation_spec.png";
                
                /// <summary> Path to Content/Assets/Textures/StarField.png </summary>
                public const string StarField_png = "Content/Assets/Textures/StarField.png";
                
                /// <summary> Path to Content/Assets/Textures/StarShine.png </summary>
                public const string StarShine_png = "Content/Assets/Textures/StarShine.png";
                
                /// <summary> Path to Content/Assets/Textures/Thrust.png </summary>
                public const string Thrust_png = "Content/Assets/Textures/Thrust.png";
                
                /// <summary> Path to Content/Assets/Textures/Trail.png </summary>
                public const string Trail_png = "Content/Assets/Textures/Trail.png";
                
                public sealed class Asteroids
                {
                    
                    /// <summary> Path to Content/Assets/Textures/Asteroids/Asteroid_diffuse.png </summary>
                    public const string Asteroid_diffuse_png = "Content/Assets/Textures/Asteroids/Asteroid_diffuse.png";
                    
                    /// <summary> Path to Content/Assets/Textures/Asteroids/Asteroid_norm.png </summary>
                    public const string Asteroid_norm_png = "Content/Assets/Textures/Asteroids/Asteroid_norm.png";
                    
                    /// <summary> Path to Content/Assets/Textures/Asteroids/Asteroid_spec.png </summary>
                    public const string Asteroid_spec_png = "Content/Assets/Textures/Asteroids/Asteroid_spec.png";
                }
                
                public sealed class Explosion
                {
                    
                    /// <summary> Path to Content/Assets/Textures/Explosion/Explosion_1.png </summary>
                    public const string Explosion_1_png = "Content/Assets/Textures/Explosion/Explosion_1.png";
                    
                    /// <summary> Path to Content/Assets/Textures/Explosion/Explosion_2.png </summary>
                    public const string Explosion_2_png = "Content/Assets/Textures/Explosion/Explosion_2.png";
                    
                    /// <summary> Path to Content/Assets/Textures/Explosion/Explosion_3.png </summary>
                    public const string Explosion_3_png = "Content/Assets/Textures/Explosion/Explosion_3.png";
                    
                    /// <summary> Path to Content/Assets/Textures/Explosion/Explosion_4.png </summary>
                    public const string Explosion_4_png = "Content/Assets/Textures/Explosion/Explosion_4.png";
                    
                    /// <summary> Path to Content/Assets/Textures/Explosion/Explosion_5.png </summary>
                    public const string Explosion_5_png = "Content/Assets/Textures/Explosion/Explosion_5.png";
                }
                
                public sealed class Hud
                {
                    
                    /// <summary> Path to Content/Assets/Textures/Hud/HudRadar.png </summary>
                    public const string HudRadar_png = "Content/Assets/Textures/Hud/HudRadar.png";
                    
                    /// <summary> Path to Content/Assets/Textures/Hud/Hud_1.png </summary>
                    public const string Hud_1_png = "Content/Assets/Textures/Hud/Hud_1.png";
                    
                    /// <summary> Path to Content/Assets/Textures/Hud/RadarTick.png </summary>
                    public const string RadarTick_png = "Content/Assets/Textures/Hud/RadarTick.png";
                }
            }
        }
        
        public sealed class Scenes
        {
            
            /// <summary> Path to Content/Scenes/MyScene.wscene </summary>
            public const string MyScene = "Content/Scenes/MyScene.wscene";
        }
    }
}
