//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// File generated on 07/02/2017 16:03:16
namespace StickyProjectiles
{
    using System;
    
    
    public sealed class WaveContent
    {
        
        public sealed class Assets
        {
            
            /// <summary> Path to Content/Assets/arc.png </summary>
            public const string arc_png = "Content/Assets/arc.png";
            
            /// <summary> Path to Content/Assets/Arial_16.ttf </summary>
            public const string Arial_16_ttf = "Content/Assets/Arial_16.ttf";
            
            /// <summary> Path to Content/Assets/Arrow.png </summary>
            public const string Arrow_png = "Content/Assets/Arrow.png";
            
            /// <summary> Path to Content/Assets/Arrow2.png </summary>
            public const string Arrow2_png = "Content/Assets/Arrow2.png";
            
            /// <summary> Path to Content/Assets/ArrowCollision.png </summary>
            public const string ArrowCollision_png = "Content/Assets/ArrowCollision.png";
            
            /// <summary> Path to Content/Assets/ArrowCollision2.png </summary>
            public const string ArrowCollision2_png = "Content/Assets/ArrowCollision2.png";
            
            /// <summary> Path to Content/Assets/blue_grass.png </summary>
            public const string blue_grass_png = "Content/Assets/blue_grass.png";
            
            /// <summary> Path to Content/Assets/elementStone025.png </summary>
            public const string elementStone025_png = "Content/Assets/elementStone025.png";
            
            /// <summary> Path to Content/Assets/elementWood051.png </summary>
            public const string elementWood051_png = "Content/Assets/elementWood051.png";
            
            /// <summary> Path to Content/Assets/ground.png </summary>
            public const string ground_png = "Content/Assets/ground.png";
            
            /// <summary> Path to Content/Assets/arrow1.wpref </summary>
            public const string arrow1 = "Content/Assets/arrow1.wpref";
            
            /// <summary> Path to Content/Assets/arrow2.wpref </summary>
            public const string arrow2 = "Content/Assets/arrow2.wpref";
        }
        
        public sealed class Scenes
        {
            
            /// <summary> Path to Content/Scenes/MyScene.wscene </summary>
            public const string MyScene = "Content/Scenes/MyScene.wscene";
        }
    }
}
