//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// File generated on 11/10/2015 3:38:08 PM
namespace PerPixelColliderSample
{
    using System;
    
    
    public sealed class WaveContent
    {
        
        public sealed class Assets
        {
            
            /// <summary> Path to Content/Assets/asteroid.png </summary>
            public const string asteroid_png = "Content/Assets/asteroid.png";
            
            /// <summary> Path to Content/Assets/background.jpg </summary>
            public const string background_jpg = "Content/Assets/background.jpg";
            
            /// <summary> Path to Content/Assets/explosionSpriteSheet.spritesheet </summary>
            public const string explosionSpriteSheet_spritesheet = "Content/Assets/explosionSpriteSheet.spritesheet";
            
            /// <summary> Path to Content/Assets/landScape.png </summary>
            public const string landScape_png = "Content/Assets/landScape.png";
            
            /// <summary> Path to Content/Assets/spaceShip.png </summary>
            public const string spaceShip_png = "Content/Assets/spaceShip.png";
            
            /// <summary> Path to Content/Assets/spaceShipBurst.jpg </summary>
            public const string spaceShipBurst_jpg = "Content/Assets/spaceShipBurst.jpg";
            
            /// <summary> Path to Content/Assets/spaceShipBurst.png </summary>
            public const string spaceShipBurst_png = "Content/Assets/spaceShipBurst.png";
            
            /// <summary> Texture names from spritesheet Content/Assets/explosionSpriteSheet.spritesheet </summary>
            public struct explosionSpriteSheet_spritesheet_TextureName
            {
                
                public const string explosion_01 = "explosion_01";
                
                public const string explosion_02 = "explosion_02";
                
                public const string explosion_03 = "explosion_03";
                
                public const string explosion_04 = "explosion_04";
                
                public const string explosion_05 = "explosion_05";
                
                public const string explosion_06 = "explosion_06";
                
                public const string explosion_07 = "explosion_07";
                
                public const string explosion_08 = "explosion_08";
                
                public const string explosion_09 = "explosion_09";
                
                public const string explosion_10 = "explosion_10";
                
                public const string explosion_11 = "explosion_11";
                
                public const string explosion_12 = "explosion_12";
                
                public const string explosion_13 = "explosion_13";
                
                public const string explosion_14 = "explosion_14";
                
                public const string explosion_15 = "explosion_15";
                
                public const string explosion_16 = "explosion_16";
            }
        }
        
        public sealed class Scenes
        {
            
            /// <summary> Path to Content/Scenes/MyScene.wscene </summary>
            public const string MyScene = "Content/Scenes/MyScene.wscene";
        }
    }
}
