//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// File generated on 21/06/2018 10:38:09
namespace Transitions
{
    using System;
    
    
    public sealed class WaveContent
    {
        
        /// <summary> Path to Content/Transitions.wgame </summary>
        public const string GameInfo = "Content/Transitions.wgame";
        
        public sealed class RenderLayers
        {
            
            /// <summary>Id of Opaque</summary>
            public const int Opaque = 0;
            
            /// <summary>Id of Skybox</summary>
            public const int Skybox = 1;
            
            /// <summary>Id of Alpha</summary>
            public const int Alpha = 2;
            
            /// <summary>Id of Additive</summary>
            public const int Additive = 3;
            
            /// <summary>Id of GUI</summary>
            public const int GUI = 4;
            
            /// <summary>Id of Debug</summary>
            public const int Debug = 5;
        }
        
        public sealed class Assets
        {
            
            /// <summary> Path to Content/Assets/BasicMaterial.wmat </summary>
            public const string BasicMaterial = "Content/Assets/BasicMaterial.wmat";
        }
        
        public sealed class Scenes
        {
            
            /// <summary> Path to Content/Scenes/MyScene.wscene </summary>
            public const string MyScene = "Content/Scenes/MyScene.wscene";
            
            /// <summary> Path to Content/Scenes/Scene0.wscene </summary>
            public const string Scene0 = "Content/Scenes/Scene0.wscene";
            
            /// <summary> Path to Content/Scenes/Scene1.wscene </summary>
            public const string Scene1 = "Content/Scenes/Scene1.wscene";
            
            /// <summary> Path to Content/Scenes/Scene10.wscene </summary>
            public const string Scene10 = "Content/Scenes/Scene10.wscene";
            
            /// <summary> Path to Content/Scenes/Scene11.wscene </summary>
            public const string Scene11 = "Content/Scenes/Scene11.wscene";
            
            /// <summary> Path to Content/Scenes/Scene12.wscene </summary>
            public const string Scene12 = "Content/Scenes/Scene12.wscene";
            
            /// <summary> Path to Content/Scenes/Scene13.wscene </summary>
            public const string Scene13 = "Content/Scenes/Scene13.wscene";
            
            /// <summary> Path to Content/Scenes/Scene14.wscene </summary>
            public const string Scene14 = "Content/Scenes/Scene14.wscene";
            
            /// <summary> Path to Content/Scenes/Scene15.wscene </summary>
            public const string Scene15 = "Content/Scenes/Scene15.wscene";
            
            /// <summary> Path to Content/Scenes/Scene2.wscene </summary>
            public const string Scene2 = "Content/Scenes/Scene2.wscene";
            
            /// <summary> Path to Content/Scenes/Scene3.wscene </summary>
            public const string Scene3 = "Content/Scenes/Scene3.wscene";
            
            /// <summary> Path to Content/Scenes/Scene4.wscene </summary>
            public const string Scene4 = "Content/Scenes/Scene4.wscene";
            
            /// <summary> Path to Content/Scenes/Scene5.wscene </summary>
            public const string Scene5 = "Content/Scenes/Scene5.wscene";
            
            /// <summary> Path to Content/Scenes/Scene6.wscene </summary>
            public const string Scene6 = "Content/Scenes/Scene6.wscene";
            
            /// <summary> Path to Content/Scenes/Scene7.wscene </summary>
            public const string Scene7 = "Content/Scenes/Scene7.wscene";
            
            /// <summary> Path to Content/Scenes/Scene8.wscene </summary>
            public const string Scene8 = "Content/Scenes/Scene8.wscene";
            
            /// <summary> Path to Content/Scenes/Scene9.wscene </summary>
            public const string Scene9 = "Content/Scenes/Scene9.wscene";
        }
    }
}
