//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// File generated on 28/10/2015 17:32:50
namespace Transition
{
    using System;
    
    
    public sealed class WaveContent
    {
        
        public sealed class Scenes
        {
            
            /// <summary> Path to Content/Scenes/Scene0.wscene </summary>
            public const string Scene0 = "Content/Scenes/Scene0.wscene";
            
            /// <summary> Path to Content/Scenes/Scene1.wscene </summary>
            public const string Scene1 = "Content/Scenes/Scene1.wscene";
            
            /// <summary> Path to Content/Scenes/Scene10.wscene </summary>
            public const string Scene10 = "Content/Scenes/Scene10.wscene";
            
            /// <summary> Path to Content/Scenes/Scene11.wscene </summary>
            public const string Scene11 = "Content/Scenes/Scene11.wscene";
            
            /// <summary> Path to Content/Scenes/Scene12.wscene </summary>
            public const string Scene12 = "Content/Scenes/Scene12.wscene";
            
            /// <summary> Path to Content/Scenes/Scene13.wscene </summary>
            public const string Scene13 = "Content/Scenes/Scene13.wscene";
            
            /// <summary> Path to Content/Scenes/Scene14.wscene </summary>
            public const string Scene14 = "Content/Scenes/Scene14.wscene";
            
            /// <summary> Path to Content/Scenes/Scene15.wscene </summary>
            public const string Scene15 = "Content/Scenes/Scene15.wscene";
            
            /// <summary> Path to Content/Scenes/Scene2.wscene </summary>
            public const string Scene2 = "Content/Scenes/Scene2.wscene";
            
            /// <summary> Path to Content/Scenes/Scene3.wscene </summary>
            public const string Scene3 = "Content/Scenes/Scene3.wscene";
            
            /// <summary> Path to Content/Scenes/Scene4.wscene </summary>
            public const string Scene4 = "Content/Scenes/Scene4.wscene";
            
            /// <summary> Path to Content/Scenes/Scene5.wscene </summary>
            public const string Scene5 = "Content/Scenes/Scene5.wscene";
            
            /// <summary> Path to Content/Scenes/Scene6.wscene </summary>
            public const string Scene6 = "Content/Scenes/Scene6.wscene";
            
            /// <summary> Path to Content/Scenes/Scene7.wscene </summary>
            public const string Scene7 = "Content/Scenes/Scene7.wscene";
            
            /// <summary> Path to Content/Scenes/Scene8.wscene </summary>
            public const string Scene8 = "Content/Scenes/Scene8.wscene";
            
            /// <summary> Path to Content/Scenes/Scene9.wscene </summary>
            public const string Scene9 = "Content/Scenes/Scene9.wscene";
        }
    }
}
