//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// File generated on 14/08/2017 15:06:31
namespace XamarinFormsProfileSample
{
    using System;
    
    
    public sealed class WaveContent
    {
        
        /// <summary> Path to Content/XamarinFormsProfileSample.wgame </summary>
        public const string GameInfo = "Content/XamarinFormsProfileSample.wgame";
        
        public sealed class Assets
        {
            
            public sealed class Models
            {
                
                /// <summary> Path to Content/Assets/Models/venus.fbx </summary>
                public const string venus_fbx = "Content/Assets/Models/venus.fbx";
            }
            
            public sealed class Textures
            {
                
                /// <summary> Path to Content/Assets/Textures/pushpin.png </summary>
                public const string pushpin_png = "Content/Assets/Textures/pushpin.png";
                
                /// <summary> Path to Content/Assets/Textures/venusLightingMap.png </summary>
                public const string venusLightingMap_png = "Content/Assets/Textures/venusLightingMap.png";
            }
            
            public sealed class Materials
            {
                
                /// <summary> Path to Content/Assets/Materials/floorMaterial.wmat </summary>
                public const string floorMaterial = "Content/Assets/Materials/floorMaterial.wmat";
                
                /// <summary> Path to Content/Assets/Materials/pushpinMaterial.wmat </summary>
                public const string pushpinMaterial = "Content/Assets/Materials/pushpinMaterial.wmat";
                
                /// <summary> Path to Content/Assets/Materials/VenusLightmapMaterial.wmat </summary>
                public const string VenusLightmapMaterial = "Content/Assets/Materials/VenusLightmapMaterial.wmat";
            }
        }
        
        public sealed class Scenes
        {
            
            /// <summary> Path to Content/Scenes/MyScene.wscene </summary>
            public const string MyScene = "Content/Scenes/MyScene.wscene";
        }
    }
}
