//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// File generated on 8/3/2017 12:59:24 PM
namespace Sounds
{
    using System;
    
    
    public sealed class WaveContent
    {
        
        /// <summary> Path to Content/Sounds.wgame </summary>
        public const string GameInfo = "Content/Sounds.wgame";
        
        public sealed class Assets
        {
            
            /// <summary> Path to Content/Assets/Menu.wav </summary>
            public const string Menu_wav = "Content/Assets/Menu.wav";
            
            /// <summary> Path to Content/Assets/Pistol.wav </summary>
            public const string Pistol_wav = "Content/Assets/Pistol.wav";
            
            /// <summary> Path to Content/Assets/Sell.wav </summary>
            public const string Sell_wav = "Content/Assets/Sell.wav";
            
            /// <summary> Path to Content/Assets/Upgrade.wav </summary>
            public const string Upgrade_wav = "Content/Assets/Upgrade.wav";
        }
        
        public sealed class Scenes
        {
            
            /// <summary> Path to Content/Scenes/MyScene.wscene </summary>
            public const string MyScene = "Content/Scenes/MyScene.wscene";
        }
    }
}
