//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// File generated on 10/08/2017 15:01:45
namespace SocialService
{
    using System;
    
    
    public sealed class WaveContent
    {
        
        /// <summary> Path to Content/SocialService.wgame </summary>
        public const string GameInfo = "Content/SocialService.wgame";
        
        public sealed class Assets
        {
            
            /// <summary> Path to Content/Assets/arial.spr </summary>
            public const string arial_spr = "Content/Assets/arial.spr";
        }
        
        public sealed class Fonts
        {
            
            /// <summary> Path to Content/Fonts/ahronbd.ttf </summary>
            public const string ahronbd_ttf = "Content/Fonts/ahronbd.ttf";
            
            /// <summary> Path to Content/Fonts/arial.ttf </summary>
            public const string arial_ttf = "Content/Fonts/arial.ttf";
        }
        
        public sealed class Scenes
        {
            
            /// <summary> Path to Content/Scenes/MyScene.wscene </summary>
            public const string MyScene = "Content/Scenes/MyScene.wscene";
        }
    }
}
