// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

// File generated on 07/09/2016 10:53:39
namespace SocialService
{
    using System;
    
    
    public sealed class WaveContent
    {
        
        public sealed class Assets
        {
            
            /// <summary> Path to Content/Assets/arial.spr </summary>
            public const string arial_spr = "Content/Assets/arial.spr";
        }
        
        public sealed class Fonts
        {
            
            /// <summary> Path to Content/Fonts/ahronbd.ttf </summary>
            public const string ahronbd_ttf = "Content/Fonts/ahronbd.ttf";
            
            /// <summary> Path to Content/Fonts/arial.ttf </summary>
            public const string arial_ttf = "Content/Fonts/arial.ttf";
        }
        
        public sealed class Scenes
        {
            
            /// <summary> Path to Content/Scenes/MyScene.wscene </summary>
            public const string MyScene = "Content/Scenes/MyScene.wscene";
        }
    }
}
