//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// File generated on 19/08/2016 15:14:01
namespace MeshCollider
{
    using System;
    
    
    public sealed class WaveContent
    {
        
        public sealed class Assets
        {
            
            /// <summary> Path to Content/Assets/checkered.jpg </summary>
            public const string checkered_jpg = "Content/Assets/checkered.jpg";
            
            /// <summary> Path to Content/Assets/Terrain.FBX </summary>
            public const string Terrain_FBX = "Content/Assets/Terrain.FBX";
            
            /// <summary> Path to Content/Assets/basicMaterial.wmat </summary>
            public const string basicMaterial = "Content/Assets/basicMaterial.wmat";
        }
        
        public sealed class Scenes
        {
            
            /// <summary> Path to Content/Scenes/MyScene.wscene </summary>
            public const string MyScene = "Content/Scenes/MyScene.wscene";
        }
    }
}
