//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// File generated on 8/8/2017 1:53:59 PM
namespace MeshCollider
{
    using System;
    
    
    public sealed class WaveContent
    {
        
        /// <summary> Path to Content/MeshCollider.wgame </summary>
        public const string GameInfo = "Content/MeshCollider.wgame";
        
        public sealed class Assets
        {
            
            /// <summary> Path to Content/Assets/checkered.jpg </summary>
            public const string checkered_jpg = "Content/Assets/checkered.jpg";
            
            /// <summary> Path to Content/Assets/basicMaterial.wmat </summary>
            public const string basicMaterial = "Content/Assets/basicMaterial.wmat";
            
            /// <summary> Path to Content/Assets/capsule.wpref </summary>
            public const string capsule = "Content/Assets/capsule.wpref";
            
            /// <summary> Path to Content/Assets/cube.wpref </summary>
            public const string cube = "Content/Assets/cube.wpref";
            
            /// <summary> Path to Content/Assets/sphere.wpref </summary>
            public const string sphere = "Content/Assets/sphere.wpref";
        }
        
        public sealed class Scenes
        {
            
            /// <summary> Path to Content/Scenes/MyScene.wscene </summary>
            public const string MyScene = "Content/Scenes/MyScene.wscene";
        }
    }
}
