//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// File generated on 22/06/2018 12:14:37
namespace SpineSkeletalAnimation
{
    using System;
    
    
    public sealed class WaveContent
    {
        
        /// <summary> Path to Content/SpineSkeletalAnimation.wgame </summary>
        public const string GameInfo = "Content/SpineSkeletalAnimation.wgame";
        
        public sealed class Assets
        {
            
            public sealed class Alien
            {
                
                /// <summary> Path to Content/Assets/Alien/alien.atlas </summary>
                public const string alien_atlas = "Content/Assets/Alien/alien.atlas";
                
                /// <summary> Path to Content/Assets/Alien/alien.json </summary>
                public const string alien_json = "Content/Assets/Alien/alien.json";
                
                /// <summary> Path to Content/Assets/Alien/alien.png </summary>
                public const string alien_png = "Content/Assets/Alien/alien.png";
            }
            
            public sealed class Dragon
            {
                
                /// <summary> Path to Content/Assets/Dragon/dragon.atlas </summary>
                public const string dragon_atlas = "Content/Assets/Dragon/dragon.atlas";
                
                /// <summary> Path to Content/Assets/Dragon/dragon.json </summary>
                public const string dragon_json = "Content/Assets/Dragon/dragon.json";
                
                /// <summary> Path to Content/Assets/Dragon/dragon.png </summary>
                public const string dragon_png = "Content/Assets/Dragon/dragon.png";
                
                /// <summary> Path to Content/Assets/Dragon/dragon2.png </summary>
                public const string dragon2_png = "Content/Assets/Dragon/dragon2.png";
            }
            
            public sealed class Goblins
            {
                
                /// <summary> Path to Content/Assets/Goblins/goblins-ffd.atlas </summary>
                public const string goblins_ffd_atlas = "Content/Assets/Goblins/goblins-ffd.atlas";
                
                /// <summary> Path to Content/Assets/Goblins/goblins-ffd.json </summary>
                public const string goblins_ffd_json = "Content/Assets/Goblins/goblins-ffd.json";
                
                /// <summary> Path to Content/Assets/Goblins/goblins-ffd.png </summary>
                public const string goblins_ffd_png = "Content/Assets/Goblins/goblins-ffd.png";
                
                /// <summary> Path to Content/Assets/Goblins/goblins.atlas </summary>
                public const string goblins_atlas = "Content/Assets/Goblins/goblins.atlas";
                
                /// <summary> Path to Content/Assets/Goblins/goblins.json </summary>
                public const string goblins_json = "Content/Assets/Goblins/goblins.json";
                
                /// <summary> Path to Content/Assets/Goblins/goblins.png </summary>
                public const string goblins_png = "Content/Assets/Goblins/goblins.png";
            }
            
            public sealed class Hero
            {
                
                /// <summary> Path to Content/Assets/Hero/hero-mesh.atlas </summary>
                public const string hero_mesh_atlas = "Content/Assets/Hero/hero-mesh.atlas";
                
                /// <summary> Path to Content/Assets/Hero/hero-mesh.json </summary>
                public const string hero_mesh_json = "Content/Assets/Hero/hero-mesh.json";
                
                /// <summary> Path to Content/Assets/Hero/hero-mesh.png </summary>
                public const string hero_mesh_png = "Content/Assets/Hero/hero-mesh.png";
                
                /// <summary> Path to Content/Assets/Hero/hero-mesh.skel </summary>
                public const string hero_mesh_skel = "Content/Assets/Hero/hero-mesh.skel";
            }
            
            public sealed class PowerUp
            {
                
                /// <summary> Path to Content/Assets/PowerUp/powerup.atlas </summary>
                public const string powerup_atlas = "Content/Assets/PowerUp/powerup.atlas";
                
                /// <summary> Path to Content/Assets/PowerUp/powerup.json </summary>
                public const string powerup_json = "Content/Assets/PowerUp/powerup.json";
                
                /// <summary> Path to Content/Assets/PowerUp/powerup.png </summary>
                public const string powerup_png = "Content/Assets/PowerUp/powerup.png";
            }
            
            public sealed class Raptor
            {
                
                /// <summary> Path to Content/Assets/Raptor/raptor.atlas </summary>
                public const string raptor_atlas = "Content/Assets/Raptor/raptor.atlas";
                
                /// <summary> Path to Content/Assets/Raptor/raptor.json </summary>
                public const string raptor_json = "Content/Assets/Raptor/raptor.json";
                
                /// <summary> Path to Content/Assets/Raptor/raptor.png </summary>
                public const string raptor_png = "Content/Assets/Raptor/raptor.png";
            }
            
            public sealed class SpineBoy
            {
                
                /// <summary> Path to Content/Assets/SpineBoy/spineboy-hoverboard.json </summary>
                public const string spineboy_hoverboard_json = "Content/Assets/SpineBoy/spineboy-hoverboard.json";
                
                /// <summary> Path to Content/Assets/SpineBoy/spineboy-mesh.json </summary>
                public const string spineboy_mesh_json = "Content/Assets/SpineBoy/spineboy-mesh.json";
                
                /// <summary> Path to Content/Assets/SpineBoy/spineboy.atlas </summary>
                public const string spineboy_atlas = "Content/Assets/SpineBoy/spineboy.atlas";
                
                /// <summary> Path to Content/Assets/SpineBoy/spineboy.json </summary>
                public const string spineboy_json = "Content/Assets/SpineBoy/spineboy.json";
                
                /// <summary> Path to Content/Assets/SpineBoy/spineboy.png </summary>
                public const string spineboy_png = "Content/Assets/SpineBoy/spineboy.png";
            }
        }
        
        public sealed class RenderLayers
        {
            
            /// <summary>Id of Opaque</summary>
            public const int Opaque = 0;
            
            /// <summary>Id of Skybox</summary>
            public const int Skybox = 1;
            
            /// <summary>Id of Alpha</summary>
            public const int Alpha = 2;
            
            /// <summary>Id of Additive</summary>
            public const int Additive = 3;
            
            /// <summary>Id of GUI</summary>
            public const int GUI = 4;
            
            /// <summary>Id of Debug</summary>
            public const int Debug = 5;
        }
        
        public sealed class Scenes
        {
            
            /// <summary> Path to Content/Scenes/MyScene.wscene </summary>
            public const string MyScene = "Content/Scenes/MyScene.wscene";
        }
    }
}
