//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// File generated on 3/14/2017 3:30:31 PM
namespace SpineSkeletalAnimation
{
    using System;
    
    
    public sealed class WaveContent
    {
        
        public sealed class Assets
        {
            
            /// <summary> Path to Content/Assets/alien.atlas </summary>
            public const string alien_atlas = "Content/Assets/alien.atlas";
            
            /// <summary> Path to Content/Assets/alien.json </summary>
            public const string alien_json = "Content/Assets/alien.json";
            
            /// <summary> Path to Content/Assets/alien.png </summary>
            public const string alien_png = "Content/Assets/alien.png";
            
            /// <summary> Path to Content/Assets/dragon.atlas </summary>
            public const string dragon_atlas = "Content/Assets/dragon.atlas";
            
            /// <summary> Path to Content/Assets/dragon.json </summary>
            public const string dragon_json = "Content/Assets/dragon.json";
            
            /// <summary> Path to Content/Assets/dragon.png </summary>
            public const string dragon_png = "Content/Assets/dragon.png";
            
            /// <summary> Path to Content/Assets/dragon2.png </summary>
            public const string dragon2_png = "Content/Assets/dragon2.png";
            
            /// <summary> Path to Content/Assets/goblins-ffd.atlas </summary>
            public const string goblins_ffd_atlas = "Content/Assets/goblins-ffd.atlas";
            
            /// <summary> Path to Content/Assets/goblins-ffd.json </summary>
            public const string goblins_ffd_json = "Content/Assets/goblins-ffd.json";
            
            /// <summary> Path to Content/Assets/goblins-ffd.png </summary>
            public const string goblins_ffd_png = "Content/Assets/goblins-ffd.png";
            
            /// <summary> Path to Content/Assets/goblins.atlas </summary>
            public const string goblins_atlas = "Content/Assets/goblins.atlas";
            
            /// <summary> Path to Content/Assets/goblins.json </summary>
            public const string goblins_json = "Content/Assets/goblins.json";
            
            /// <summary> Path to Content/Assets/goblins.png </summary>
            public const string goblins_png = "Content/Assets/goblins.png";
            
            /// <summary> Path to Content/Assets/hero-mesh.atlas </summary>
            public const string hero_mesh_atlas = "Content/Assets/hero-mesh.atlas";
            
            /// <summary> Path to Content/Assets/hero-mesh.json </summary>
            public const string hero_mesh_json = "Content/Assets/hero-mesh.json";
            
            /// <summary> Path to Content/Assets/hero-mesh.png </summary>
            public const string hero_mesh_png = "Content/Assets/hero-mesh.png";
            
            /// <summary> Path to Content/Assets/hero-mesh.skel </summary>
            public const string hero_mesh_skel = "Content/Assets/hero-mesh.skel";
            
            /// <summary> Path to Content/Assets/powerup.atlas </summary>
            public const string powerup_atlas = "Content/Assets/powerup.atlas";
            
            /// <summary> Path to Content/Assets/powerup.json </summary>
            public const string powerup_json = "Content/Assets/powerup.json";
            
            /// <summary> Path to Content/Assets/powerup.png </summary>
            public const string powerup_png = "Content/Assets/powerup.png";
            
            /// <summary> Path to Content/Assets/raptor.atlas </summary>
            public const string raptor_atlas = "Content/Assets/raptor.atlas";
            
            /// <summary> Path to Content/Assets/raptor.json </summary>
            public const string raptor_json = "Content/Assets/raptor.json";
            
            /// <summary> Path to Content/Assets/raptor.png </summary>
            public const string raptor_png = "Content/Assets/raptor.png";
            
            /// <summary> Path to Content/Assets/spineboy-hoverboard.json </summary>
            public const string spineboy_hoverboard_json = "Content/Assets/spineboy-hoverboard.json";
            
            /// <summary> Path to Content/Assets/spineboy-mesh.json </summary>
            public const string spineboy_mesh_json = "Content/Assets/spineboy-mesh.json";
            
            /// <summary> Path to Content/Assets/spineboy.atlas </summary>
            public const string spineboy_atlas = "Content/Assets/spineboy.atlas";
            
            /// <summary> Path to Content/Assets/spineboy.json </summary>
            public const string spineboy_json = "Content/Assets/spineboy.json";
            
            /// <summary> Path to Content/Assets/spineboy.png </summary>
            public const string spineboy_png = "Content/Assets/spineboy.png";
        }
        
        public sealed class Scenes
        {
            
            /// <summary> Path to Content/Scenes/MyScene.wscene </summary>
            public const string MyScene = "Content/Scenes/MyScene.wscene";
        }
    }
}
