//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// File generated on 20/08/2015 15:04:36
namespace SpineSkeletalAnimation
{
    using System;
    
    
    public sealed class WaveContent
    {
        
        public sealed class Assets
        {
            
            /// <summary> Path to Content/Assets/spineboy.atlas </summary>
            public const string spineboy_atlas = "Content/Assets/spineboy.atlas";
            
            /// <summary> Path to Content/Assets/spineboy.json </summary>
            public const string spineboy_json = "Content/Assets/spineboy.json";
            
            /// <summary> Path to Content/Assets/spineboy.png </summary>
            public const string spineboy_png = "Content/Assets/spineboy.png";
        }
        
        public sealed class Scenes
        {
            
            /// <summary> Path to Content/Scenes/MyScene.wscene </summary>
            public const string MyScene = "Content/Scenes/MyScene.wscene";
        }
    }
}
