//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// File generated on 16/12/2016 11:36:37
namespace BasicPhysic2D
{
    using System;
    
    
    public sealed class WaveContent
    {
        
        public sealed class Assets
        {
            
            public sealed class Textures
            {
                
                /// <summary> Path to Content/Assets/Textures/alienBeige_suit.png </summary>
                public const string alienBeige_suit_png = "Content/Assets/Textures/alienBeige_suit.png";
                
                /// <summary> Path to Content/Assets/Textures/alienPink_round.png </summary>
                public const string alienPink_round_png = "Content/Assets/Textures/alienPink_round.png";
                
                /// <summary> Path to Content/Assets/Textures/blue_land.png </summary>
                public const string blue_land_png = "Content/Assets/Textures/blue_land.png";
                
                /// <summary> Path to Content/Assets/Textures/chain.png </summary>
                public const string chain_png = "Content/Assets/Textures/chain.png";
                
                /// <summary> Path to Content/Assets/Textures/debrisWood_1.png </summary>
                public const string debrisWood_1_png = "Content/Assets/Textures/debrisWood_1.png";
                
                /// <summary> Path to Content/Assets/Textures/debrisWood_2.png </summary>
                public const string debrisWood_2_png = "Content/Assets/Textures/debrisWood_2.png";
                
                /// <summary> Path to Content/Assets/Textures/debrisWood_3.png </summary>
                public const string debrisWood_3_png = "Content/Assets/Textures/debrisWood_3.png";
                
                /// <summary> Path to Content/Assets/Textures/elementStone000.png </summary>
                public const string elementStone000_png = "Content/Assets/Textures/elementStone000.png";
                
                /// <summary> Path to Content/Assets/Textures/elementStone001.png </summary>
                public const string elementStone001_png = "Content/Assets/Textures/elementStone001.png";
                
                /// <summary> Path to Content/Assets/Textures/elementStone013.png </summary>
                public const string elementStone013_png = "Content/Assets/Textures/elementStone013.png";
                
                /// <summary> Path to Content/Assets/Textures/elementStone028.png </summary>
                public const string elementStone028_png = "Content/Assets/Textures/elementStone028.png";
                
                /// <summary> Path to Content/Assets/Textures/elementStone032.png </summary>
                public const string elementStone032_png = "Content/Assets/Textures/elementStone032.png";
                
                /// <summary> Path to Content/Assets/Textures/elementStone033.png </summary>
                public const string elementStone033_png = "Content/Assets/Textures/elementStone033.png";
                
                /// <summary> Path to Content/Assets/Textures/elementWood012.png </summary>
                public const string elementWood012_png = "Content/Assets/Textures/elementWood012.png";
                
                /// <summary> Path to Content/Assets/Textures/grass.png </summary>
                public const string grass_png = "Content/Assets/Textures/grass.png";
                
                /// <summary> Path to Content/Assets/Textures/weightChained.png </summary>
                public const string weightChained_png = "Content/Assets/Textures/weightChained.png";
            }
        }
        
        public sealed class Scenes
        {
            
            /// <summary> Path to Content/Scenes/MyScene.wscene </summary>
            public const string MyScene = "Content/Scenes/MyScene.wscene";
        }
    }
}
