//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// File generated on 12/04/2018 18:50:49
namespace BasicPhysic2D
{
    using System;
    
    
    public sealed class WaveContent
    {
        
        /// <summary> Path to Content/BasicPhysic2D.wgame </summary>
        public const string GameInfo = "Content/BasicPhysic2D.wgame";
        
        public sealed class Assets
        {
            
            public sealed class Textures
            {
                
                /// <summary> Path to Content/Assets/Textures/alienBeige_suit.png </summary>
                public const string alienBeige_suit_png = "Content/Assets/Textures/alienBeige_suit.png";
                
                /// <summary> Path to Content/Assets/Textures/alienPink_round.png </summary>
                public const string alienPink_round_png = "Content/Assets/Textures/alienPink_round.png";
                
                /// <summary> Path to Content/Assets/Textures/blue_land.png </summary>
                public const string blue_land_png = "Content/Assets/Textures/blue_land.png";
                
                /// <summary> Path to Content/Assets/Textures/chain.png </summary>
                public const string chain_png = "Content/Assets/Textures/chain.png";
                
                /// <summary> Path to Content/Assets/Textures/debrisWood_1.png </summary>
                public const string debrisWood_1_png = "Content/Assets/Textures/debrisWood_1.png";
                
                /// <summary> Path to Content/Assets/Textures/debrisWood_2.png </summary>
                public const string debrisWood_2_png = "Content/Assets/Textures/debrisWood_2.png";
                
                /// <summary> Path to Content/Assets/Textures/debrisWood_3.png </summary>
                public const string debrisWood_3_png = "Content/Assets/Textures/debrisWood_3.png";
                
                /// <summary> Path to Content/Assets/Textures/elementStone000.png </summary>
                public const string elementStone000_png = "Content/Assets/Textures/elementStone000.png";
                
                /// <summary> Path to Content/Assets/Textures/elementStone001.png </summary>
                public const string elementStone001_png = "Content/Assets/Textures/elementStone001.png";
                
                /// <summary> Path to Content/Assets/Textures/elementStone013.png </summary>
                public const string elementStone013_png = "Content/Assets/Textures/elementStone013.png";
                
                /// <summary> Path to Content/Assets/Textures/elementStone028.png </summary>
                public const string elementStone028_png = "Content/Assets/Textures/elementStone028.png";
                
                /// <summary> Path to Content/Assets/Textures/elementStone032.png </summary>
                public const string elementStone032_png = "Content/Assets/Textures/elementStone032.png";
                
                /// <summary> Path to Content/Assets/Textures/elementStone033.png </summary>
                public const string elementStone033_png = "Content/Assets/Textures/elementStone033.png";
                
                /// <summary> Path to Content/Assets/Textures/elementWood012.png </summary>
                public const string elementWood012_png = "Content/Assets/Textures/elementWood012.png";
                
                /// <summary> Path to Content/Assets/Textures/grass.png </summary>
                public const string grass_png = "Content/Assets/Textures/grass.png";
                
                /// <summary> Path to Content/Assets/Textures/weightChained.png </summary>
                public const string weightChained_png = "Content/Assets/Textures/weightChained.png";
            }
        }
        
        public sealed class RenderLayers
        {
            
            /// <summary>Id of Opaque</summary>
            public const int Opaque = 0;
            
            /// <summary>Id of Skybox</summary>
            public const int Skybox = 1;
            
            /// <summary>Id of Alpha</summary>
            public const int Alpha = 2;
            
            /// <summary>Id of Additive</summary>
            public const int Additive = 3;
            
            /// <summary>Id of GUI</summary>
            public const int GUI = 4;
            
            /// <summary>Id of Debug</summary>
            public const int Debug = 5;
        }
        
        public sealed class Scenes
        {
            
            /// <summary> Path to Content/Scenes/MyScene.wscene </summary>
            public const string MyScene = "Content/Scenes/MyScene.wscene";
        }
    }
}
