//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// File generated on 6/25/2018 6:03:20 PM
namespace Sound3D
{
    using System;
    
    
    public sealed class WaveContent
    {
        
        /// <summary> Path to Content/Sound3D.wgame </summary>
        public const string GameInfo = "Content/Sound3D.wgame";
        
        public sealed class Assets
        {
            
            /// <summary> Path to Content/Assets/engines_1.wav </summary>
            public const string engines_1_wav = "Content/Assets/engines_1.wav";
            
            /// <summary> Path to Content/Assets/spaceship.fbx </summary>
            public const string spaceship_fbx = "Content/Assets/spaceship.fbx";
            
            /// <summary> Path to Content/Assets/RedMat.wmat </summary>
            public const string RedMat = "Content/Assets/RedMat.wmat";
            
            /// <summary> Path to Content/Assets/ShipMat.wmat </summary>
            public const string ShipMat = "Content/Assets/ShipMat.wmat";
            
            public sealed class spaceship_Textures
            {
                
                /// <summary> Path to Content/Assets/spaceship_Textures/spaceship_0.jpg </summary>
                public const string spaceship_0_jpg = "Content/Assets/spaceship_Textures/spaceship_0.jpg";
                
                /// <summary> Path to Content/Assets/spaceship_Textures/spaceship_1.jpg </summary>
                public const string spaceship_1_jpg = "Content/Assets/spaceship_Textures/spaceship_1.jpg";
                
                /// <summary> Path to Content/Assets/spaceship_Textures/spaceship_2.png </summary>
                public const string spaceship_2_png = "Content/Assets/spaceship_Textures/spaceship_2.png";
                
                /// <summary> Path to Content/Assets/spaceship_Textures/spaceship_3.jpg </summary>
                public const string spaceship_3_jpg = "Content/Assets/spaceship_Textures/spaceship_3.jpg";
                
                /// <summary> Path to Content/Assets/spaceship_Textures/spaceship_4.jpg </summary>
                public const string spaceship_4_jpg = "Content/Assets/spaceship_Textures/spaceship_4.jpg";
            }
            
            public sealed class Materials
            {
                
                /// <summary> Path to Content/Assets/Materials/Fighter.wmat </summary>
                public const string Fighter = "Content/Assets/Materials/Fighter.wmat";
                
                /// <summary> Path to Content/Assets/Materials/Thrust.wmat </summary>
                public const string Thrust = "Content/Assets/Materials/Thrust.wmat";
            }
        }
        
        public sealed class RenderLayers
        {
            
            /// <summary>Id of Opaque</summary>
            public const int Opaque = 0;
            
            /// <summary>Id of Skybox</summary>
            public const int Skybox = 1;
            
            /// <summary>Id of Alpha</summary>
            public const int Alpha = 2;
            
            /// <summary>Id of Additive</summary>
            public const int Additive = 3;
            
            /// <summary>Id of GUI</summary>
            public const int GUI = 4;
            
            /// <summary>Id of Debug</summary>
            public const int Debug = 5;
        }
        
        public sealed class Scenes
        {
            
            /// <summary> Path to Content/Scenes/MyScene.wscene </summary>
            public const string MyScene = "Content/Scenes/MyScene.wscene";
        }
    }
}
