//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// File generated on 13/09/2015 12:13:30
namespace Sound3D
{
    using System;
    
    
    public sealed class WaveContent
    {
        
        public sealed class Assets
        {
            
            /// <summary> Path to Content/Assets/engines_1.wav </summary>
            public const string engines_1_wav = "Content/Assets/engines_1.wav";
            
            /// <summary> Path to Content/Assets/Fighter.fbx </summary>
            public const string Fighter_fbx = "Content/Assets/Fighter.fbx";
            
            /// <summary> Path to Content/Assets/fighter_diffuse.png </summary>
            public const string fighter_diffuse_png = "Content/Assets/fighter_diffuse.png";
            
            /// <summary> Path to Content/Assets/fighter_normal_spec.png </summary>
            public const string fighter_normal_spec_png = "Content/Assets/fighter_normal_spec.png";
            
            /// <summary> Path to Content/Assets/Thrust.png </summary>
            public const string Thrust_png = "Content/Assets/Thrust.png";
            
            /// <summary> Path to Content/Assets/MyMaterial(1).wmat </summary>
            public const string MyMaterial_1_ = "Content/Assets/MyMaterial(1).wmat";
            
            /// <summary> Path to Content/Assets/MyMaterial(2).wmat </summary>
            public const string MyMaterial_2_ = "Content/Assets/MyMaterial(2).wmat";
            
            /// <summary> Path to Content/Assets/MyMaterial.wmat </summary>
            public const string MyMaterial = "Content/Assets/MyMaterial.wmat";
        }
        
        public sealed class Scenes
        {
            
            /// <summary> Path to Content/Scenes/MyScene.wscene </summary>
            public const string MyScene = "Content/Scenes/MyScene.wscene";
        }
    }
}
