//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// File generated on 1/26/2016 9:15:43 PM
namespace CustomGeometry
{
    using System;
    
    
    public sealed class WaveContent
    {
        
        public sealed class Assets
        {
            
            /// <summary> Path to Content/Assets/boxSprite.png </summary>
            public const string boxSprite_png = "Content/Assets/boxSprite.png";
            
            /// <summary> Path to Content/Assets/MyMaterial.wmat </summary>
            public const string MyMaterial = "Content/Assets/MyMaterial.wmat";
        }
        
        public sealed class Scenes
        {
            
            /// <summary> Path to Content/Scenes/MyScene.wscene </summary>
            public const string MyScene = "Content/Scenes/MyScene.wscene";
        }
    }
}
