//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// File generated on 14/01/2016 11:14:13
namespace StaticBatching
{
    using System;
    
    
    public sealed class WaveContent
    {
        
        public sealed class Assets
        {
            
            /// <summary> Path to Content/Assets/mainColumn.fbx </summary>
            public const string mainColumn_fbx = "Content/Assets/mainColumn.fbx";
            
            /// <summary> Path to Content/Assets/material1.wmat </summary>
            public const string material1 = "Content/Assets/material1.wmat";
            
            /// <summary> Path to Content/Assets/material2.wmat </summary>
            public const string material2 = "Content/Assets/material2.wmat";
            
            public sealed class textures
            {
                
                /// <summary> Path to Content/Assets/textures/column1.png </summary>
                public const string column1_png = "Content/Assets/textures/column1.png";
                
                /// <summary> Path to Content/Assets/textures/column1_normal.png </summary>
                public const string column1_normal_png = "Content/Assets/textures/column1_normal.png";
                
                /// <summary> Path to Content/Assets/textures/column2.png </summary>
                public const string column2_png = "Content/Assets/textures/column2.png";
                
                /// <summary> Path to Content/Assets/textures/column2_normal.png </summary>
                public const string column2_normal_png = "Content/Assets/textures/column2_normal.png";
            }
        }
        
        public sealed class Scenes
        {
            
            /// <summary> Path to Content/Scenes/MyScene.wscene </summary>
            public const string MyScene = "Content/Scenes/MyScene.wscene";
        }
    }
}
