//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// File generated on 8/8/2017 11:41:42 AM
namespace StaticBatching
{
    using System;
    
    
    public sealed class WaveContent
    {
        
        /// <summary> Path to Content/StaticBatching.wgame </summary>
        public const string GameInfo = "Content/StaticBatching.wgame";
        
        public sealed class Assets
        {
            
            /// <summary> Path to Content/Assets/mainColumn.fbx </summary>
            public const string mainColumn_fbx = "Content/Assets/mainColumn.fbx";
            
            /// <summary> Path to Content/Assets/material1.wmat </summary>
            public const string material1 = "Content/Assets/material1.wmat";
            
            public sealed class textures
            {
                
                /// <summary> Path to Content/Assets/textures/column2.png </summary>
                public const string column2_png = "Content/Assets/textures/column2.png";
                
                /// <summary> Path to Content/Assets/textures/column2_normal.png </summary>
                public const string column2_normal_png = "Content/Assets/textures/column2_normal.png";
            }
            
            public sealed class Materials
            {
                
                /// <summary> Path to Content/Assets/Materials/MainColumn.wmat </summary>
                public const string MainColumn = "Content/Assets/Materials/MainColumn.wmat";
            }
        }
        
        public sealed class Scenes
        {
            
            /// <summary> Path to Content/Scenes/MyScene.wscene </summary>
            public const string MyScene = "Content/Scenes/MyScene.wscene";
        }
    }
}
