//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// File generated on 08/08/2017 14:57:49
namespace HololensSample
{
    using System;
    
    
    public sealed class WaveContent
    {
        
        /// <summary> Path to Content/HololensSample.wgame </summary>
        public const string GameInfo = "Content/HololensSample.wgame";
        
        public sealed class Assets
        {
            
            /// <summary> Path to Content/Assets/a380.fbx </summary>
            public const string a380_fbx = "Content/Assets/a380.fbx";
            
            /// <summary> Path to Content/Assets/AirbusLightingMap.png </summary>
            public const string AirbusLightingMap_png = "Content/Assets/AirbusLightingMap.png";
            
            /// <summary> Path to Content/Assets/ColorPalete.png </summary>
            public const string ColorPalete_png = "Content/Assets/ColorPalete.png";
            
            /// <summary> Path to Content/Assets/engines.wav </summary>
            public const string engines_wav = "Content/Assets/engines.wav";
            
            /// <summary> Path to Content/Assets/A380Mat.wmat </summary>
            public const string A380Mat = "Content/Assets/A380Mat.wmat";
        }
        
        public sealed class Scenes
        {
            
            /// <summary> Path to Content/Scenes/MyScene.wscene </summary>
            public const string MyScene = "Content/Scenes/MyScene.wscene";
        }
    }
}
