//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// File generated on 21/03/2018 13:27:11
namespace ParticleSystem3D
{
    using System;
    
    
    public sealed class WaveContent
    {
        
        /// <summary> Path to Content/ParticleSystem3D.wgame </summary>
        public const string GameInfo = "Content/ParticleSystem3D.wgame";
        
        public sealed class Assets
        {
            
            public sealed class Models
            {
                
                /// <summary> Path to Content/Assets/Models/Label.FBX </summary>
                public const string Label_FBX = "Content/Assets/Models/Label.FBX";
                
                public sealed class Materials
                {
                    
                    /// <summary> Path to Content/Assets/Models/Materials/02 - Default.wmat </summary>
                    public const string _02_Default = "Content/Assets/Models/Materials/02 - Default.wmat";
                }
            }
            
            public sealed class Sounds
            {
                
                /// <summary> Path to Content/Assets/Sounds/bubbles.wav </summary>
                public const string bubbles_wav = "Content/Assets/Sounds/bubbles.wav";
                
                /// <summary> Path to Content/Assets/Sounds/fire.wav </summary>
                public const string fire_wav = "Content/Assets/Sounds/fire.wav";
                
                /// <summary> Path to Content/Assets/Sounds/sparkSound.wav </summary>
                public const string sparkSound_wav = "Content/Assets/Sounds/sparkSound.wav";
                
                /// <summary> Path to Content/Assets/Sounds/waterFall.wav </summary>
                public const string waterFall_wav = "Content/Assets/Sounds/waterFall.wav";
            }
            
            public sealed class Textures
            {
                
                /// <summary> Path to Content/Assets/Textures/BubblesLabel.png </summary>
                public const string BubblesLabel_png = "Content/Assets/Textures/BubblesLabel.png";
                
                /// <summary> Path to Content/Assets/Textures/bubbleTexture.png </summary>
                public const string bubbleTexture_png = "Content/Assets/Textures/bubbleTexture.png";
                
                /// <summary> Path to Content/Assets/Textures/ConfettiLabel.png </summary>
                public const string ConfettiLabel_png = "Content/Assets/Textures/ConfettiLabel.png";
                
                /// <summary> Path to Content/Assets/Textures/FireLabel2.png </summary>
                public const string FireLabel2_png = "Content/Assets/Textures/FireLabel2.png";
                
                /// <summary> Path to Content/Assets/Textures/particleFire.png </summary>
                public const string particleFire_png = "Content/Assets/Textures/particleFire.png";
                
                /// <summary> Path to Content/Assets/Textures/smoke.png </summary>
                public const string smoke_png = "Content/Assets/Textures/smoke.png";
                
                /// <summary> Path to Content/Assets/Textures/SmokeLabel.png </summary>
                public const string SmokeLabel_png = "Content/Assets/Textures/SmokeLabel.png";
                
                /// <summary> Path to Content/Assets/Textures/SmokeParticle.png </summary>
                public const string SmokeParticle_png = "Content/Assets/Textures/SmokeParticle.png";
                
                /// <summary> Path to Content/Assets/Textures/SnowLabel.png </summary>
                public const string SnowLabel_png = "Content/Assets/Textures/SnowLabel.png";
                
                /// <summary> Path to Content/Assets/Textures/snowParticle.png </summary>
                public const string snowParticle_png = "Content/Assets/Textures/snowParticle.png";
                
                /// <summary> Path to Content/Assets/Textures/spark.png </summary>
                public const string spark_png = "Content/Assets/Textures/spark.png";
                
                /// <summary> Path to Content/Assets/Textures/SparkLabel.png </summary>
                public const string SparkLabel_png = "Content/Assets/Textures/SparkLabel.png";
                
                /// <summary> Path to Content/Assets/Textures/water2.png </summary>
                public const string water2_png = "Content/Assets/Textures/water2.png";
                
                /// <summary> Path to Content/Assets/Textures/water3.png </summary>
                public const string water3_png = "Content/Assets/Textures/water3.png";
                
                /// <summary> Path to Content/Assets/Textures/WaterLabel.png </summary>
                public const string WaterLabel_png = "Content/Assets/Textures/WaterLabel.png";
            }
            
            public sealed class Materials
            {
                
                /// <summary> Path to Content/Assets/Materials/bubble.wmat </summary>
                public const string bubble = "Content/Assets/Materials/bubble.wmat";
                
                /// <summary> Path to Content/Assets/Materials/BubblesMat.wmat </summary>
                public const string BubblesMat = "Content/Assets/Materials/BubblesMat.wmat";
                
                /// <summary> Path to Content/Assets/Materials/fire.wmat </summary>
                public const string fire = "Content/Assets/Materials/fire.wmat";
                
                /// <summary> Path to Content/Assets/Materials/FireLMat.wmat </summary>
                public const string FireLMat = "Content/Assets/Materials/FireLMat.wmat";
                
                /// <summary> Path to Content/Assets/Materials/smoke.wmat </summary>
                public const string smoke = "Content/Assets/Materials/smoke.wmat";
                
                /// <summary> Path to Content/Assets/Materials/SmokeLMat.wmat </summary>
                public const string SmokeLMat = "Content/Assets/Materials/SmokeLMat.wmat";
                
                /// <summary> Path to Content/Assets/Materials/SmokeMaterial.wmat </summary>
                public const string SmokeMaterial = "Content/Assets/Materials/SmokeMaterial.wmat";
                
                /// <summary> Path to Content/Assets/Materials/snow.wmat </summary>
                public const string snow = "Content/Assets/Materials/snow.wmat";
                
                /// <summary> Path to Content/Assets/Materials/SnowLMat.wmat </summary>
                public const string SnowLMat = "Content/Assets/Materials/SnowLMat.wmat";
                
                /// <summary> Path to Content/Assets/Materials/spark.wmat </summary>
                public const string spark = "Content/Assets/Materials/spark.wmat";
                
                /// <summary> Path to Content/Assets/Materials/SparkMat.wmat </summary>
                public const string SparkMat = "Content/Assets/Materials/SparkMat.wmat";
                
                /// <summary> Path to Content/Assets/Materials/Water.wmat </summary>
                public const string Water = "Content/Assets/Materials/Water.wmat";
                
                /// <summary> Path to Content/Assets/Materials/Water2.wmat </summary>
                public const string Water2 = "Content/Assets/Materials/Water2.wmat";
                
                /// <summary> Path to Content/Assets/Materials/Water3.wmat </summary>
                public const string Water3 = "Content/Assets/Materials/Water3.wmat";
                
                /// <summary> Path to Content/Assets/Materials/WaterLMat.wmat </summary>
                public const string WaterLMat = "Content/Assets/Materials/WaterLMat.wmat";
            }
        }
        
        public sealed class RenderLayers
        {
            
            /// <summary>Id of Opaque</summary>
            public const int Opaque = 0;
            
            /// <summary>Id of Skybox</summary>
            public const int Skybox = 1;
            
            /// <summary>Id of Alpha</summary>
            public const int Alpha = 2;
            
            /// <summary>Id of Additive</summary>
            public const int Additive = 3;
            
            /// <summary>Id of GUI</summary>
            public const int GUI = 4;
            
            /// <summary>Id of Debug</summary>
            public const int Debug = 5;
        }
        
        public sealed class Scenes
        {
            
            /// <summary> Path to Content/Scenes/MyScene.wscene </summary>
            public const string MyScene = "Content/Scenes/MyScene.wscene";
        }
    }
}
