//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// File generated on 07/02/2017 16:02:00
namespace Diagnostics
{
    using System;
    
    
    public sealed class WaveContent
    {
        
        public sealed class Assets
        {
            
            /// <summary> Path to Content/Assets/BlueMaterial.wmat </summary>
            public const string BlueMaterial = "Content/Assets/BlueMaterial.wmat";
            
            /// <summary> Path to Content/Assets/GreedMaterial.wmat </summary>
            public const string GreedMaterial = "Content/Assets/GreedMaterial.wmat";
            
            /// <summary> Path to Content/Assets/RedMaterial.wmat </summary>
            public const string RedMaterial = "Content/Assets/RedMaterial.wmat";
        }
        
        public sealed class Scenes
        {
            
            /// <summary> Path to Content/Scenes/MyScene.wscene </summary>
            public const string MyScene = "Content/Scenes/MyScene.wscene";
        }
    }
}
