//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// File generated on 6/25/2018 4:53:26 PM
namespace Accelerometer
{
    using System;
    
    
    public sealed class WaveContent
    {
        
        /// <summary> Path to Content/Accelerometer.wgame </summary>
        public const string GameInfo = "Content/Accelerometer.wgame";
        
        public sealed class Assets
        {
            
            public sealed class Materials
            {
                
                /// <summary> Path to Content/Assets/Materials/BallMat.wmat </summary>
                public const string BallMat = "Content/Assets/Materials/BallMat.wmat";
                
                /// <summary> Path to Content/Assets/Materials/BlueMat.wmat </summary>
                public const string BlueMat = "Content/Assets/Materials/BlueMat.wmat";
                
                /// <summary> Path to Content/Assets/Materials/CyanMat.wmat </summary>
                public const string CyanMat = "Content/Assets/Materials/CyanMat.wmat";
                
                /// <summary> Path to Content/Assets/Materials/GreenMat.wmat </summary>
                public const string GreenMat = "Content/Assets/Materials/GreenMat.wmat";
                
                /// <summary> Path to Content/Assets/Materials/PinkMat.wmat </summary>
                public const string PinkMat = "Content/Assets/Materials/PinkMat.wmat";
                
                /// <summary> Path to Content/Assets/Materials/RedMat.wmat </summary>
                public const string RedMat = "Content/Assets/Materials/RedMat.wmat";
                
                /// <summary> Path to Content/Assets/Materials/YellowMat.wmat </summary>
                public const string YellowMat = "Content/Assets/Materials/YellowMat.wmat";
            }
            
            public sealed class Prefabs
            {
                
                /// <summary> Path to Content/Assets/Prefabs/ball.wpref </summary>
                public const string ball = "Content/Assets/Prefabs/ball.wpref";
            }
        }
        
        public sealed class RenderLayers
        {
            
            /// <summary>Id of Opaque</summary>
            public const int Opaque = 0;
            
            /// <summary>Id of Skybox</summary>
            public const int Skybox = 1;
            
            /// <summary>Id of Alpha</summary>
            public const int Alpha = 2;
            
            /// <summary>Id of Additive</summary>
            public const int Additive = 3;
            
            /// <summary>Id of GUI</summary>
            public const int GUI = 4;
            
            /// <summary>Id of Debug</summary>
            public const int Debug = 5;
        }
        
        public sealed class Scenes
        {
            
            /// <summary> Path to Content/Scenes/MyScene.wscene </summary>
            public const string MyScene = "Content/Scenes/MyScene.wscene";
        }
    }
}
