//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// File generated on 16/12/2016 11:32:40
namespace Accelerometer
{
    using System;
    
    
    public sealed class WaveContent
    {
        
        public sealed class Assets
        {
            
            public sealed class Materials
            {
                
                /// <summary> Path to Content/Assets/Materials/MyMaterial(1).wmat </summary>
                public const string MyMaterial_1_ = "Content/Assets/Materials/MyMaterial(1).wmat";
                
                /// <summary> Path to Content/Assets/Materials/MyMaterial(2).wmat </summary>
                public const string MyMaterial_2_ = "Content/Assets/Materials/MyMaterial(2).wmat";
                
                /// <summary> Path to Content/Assets/Materials/MyMaterial(3).wmat </summary>
                public const string MyMaterial_3_ = "Content/Assets/Materials/MyMaterial(3).wmat";
                
                /// <summary> Path to Content/Assets/Materials/MyMaterial(4).wmat </summary>
                public const string MyMaterial_4_ = "Content/Assets/Materials/MyMaterial(4).wmat";
                
                /// <summary> Path to Content/Assets/Materials/MyMaterial(5).wmat </summary>
                public const string MyMaterial_5_ = "Content/Assets/Materials/MyMaterial(5).wmat";
                
                /// <summary> Path to Content/Assets/Materials/MyMaterial.wmat </summary>
                public const string MyMaterial = "Content/Assets/Materials/MyMaterial.wmat";
            }
        }
        
        public sealed class Scenes
        {
            
            /// <summary> Path to Content/Scenes/MyScene.wscene </summary>
            public const string MyScene = "Content/Scenes/MyScene.wscene";
        }
    }
}
