//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// File generated on 10/08/2017 14:59:24
namespace VuforiaTest
{
    using System;
    
    
    public sealed class WaveContent
    {
        
        /// <summary> Path to Content/VuforiaTest.wgame </summary>
        public const string GameInfo = "Content/VuforiaTest.wgame";
        
        public sealed class Assets
        {
            
            public sealed class AR
            {
                
                /// <summary> Path to Content/Assets/AR/StonesAndChips.dat </summary>
                public const string StonesAndChips_dat = "Content/Assets/AR/StonesAndChips.dat";
                
                /// <summary> Path to Content/Assets/AR/StonesAndChips.xml </summary>
                public const string StonesAndChips_xml = "Content/Assets/AR/StonesAndChips.xml";
            }
            
            public sealed class Models
            {
                
                /// <summary> Path to Content/Assets/Models/ball.fbx </summary>
                public const string ball_fbx = "Content/Assets/Models/ball.fbx";
                
                /// <summary> Path to Content/Assets/Models/crate.fbx </summary>
                public const string crate_fbx = "Content/Assets/Models/crate.fbx";
            }
            
            public sealed class Textures
            {
                
                /// <summary> Path to Content/Assets/Textures/ball_diffuse.png </summary>
                public const string ball_diffuse_png = "Content/Assets/Textures/ball_diffuse.png";
                
                /// <summary> Path to Content/Assets/Textures/chips_scaled.jpg </summary>
                public const string chips_scaled_jpg = "Content/Assets/Textures/chips_scaled.jpg";
                
                /// <summary> Path to Content/Assets/Textures/stones_scaled.jpg </summary>
                public const string stones_scaled_jpg = "Content/Assets/Textures/stones_scaled.jpg";
                
                /// <summary> Path to Content/Assets/Textures/woodCrate_diffuse.png </summary>
                public const string woodCrate_diffuse_png = "Content/Assets/Textures/woodCrate_diffuse.png";
            }
            
            public sealed class Materials
            {
                
                /// <summary> Path to Content/Assets/Materials/ballMat.wmat </summary>
                public const string ballMat = "Content/Assets/Materials/ballMat.wmat";
                
                /// <summary> Path to Content/Assets/Materials/chipsPatternMat.wmat </summary>
                public const string chipsPatternMat = "Content/Assets/Materials/chipsPatternMat.wmat";
                
                /// <summary> Path to Content/Assets/Materials/crateMat.wmat </summary>
                public const string crateMat = "Content/Assets/Materials/crateMat.wmat";
                
                /// <summary> Path to Content/Assets/Materials/stonesPatternMat.wmat </summary>
                public const string stonesPatternMat = "Content/Assets/Materials/stonesPatternMat.wmat";
            }
        }
        
        public sealed class Scenes
        {
            
            /// <summary> Path to Content/Scenes/MyScene.wscene </summary>
            public const string MyScene = "Content/Scenes/MyScene.wscene";
        }
    }
}
