//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// File generated on 10/28/2015 6:22:54 PM
namespace VuforiaTest
{
    using System;
    
    
    public sealed class WaveContent
    {
        
        public sealed class Assets
        {
            
            public sealed class AR
            {
                
                /// <summary> Path to Content/Assets/AR/TestVuforia.dat </summary>
                public const string TestVuforia_dat = "Content/Assets/AR/TestVuforia.dat";
                
                /// <summary> Path to Content/Assets/AR/TestVuforia.xml </summary>
                public const string TestVuforia_xml = "Content/Assets/AR/TestVuforia.xml";
            }
            
            public sealed class Models
            {
                
                /// <summary> Path to Content/Assets/Models/ball.fbx </summary>
                public const string ball_fbx = "Content/Assets/Models/ball.fbx";
                
                /// <summary> Path to Content/Assets/Models/crate.fbx </summary>
                public const string crate_fbx = "Content/Assets/Models/crate.fbx";
            }
            
            public sealed class Textures
            {
                
                /// <summary> Path to Content/Assets/Textures/ball_diffuse.png </summary>
                public const string ball_diffuse_png = "Content/Assets/Textures/ball_diffuse.png";
                
                /// <summary> Path to Content/Assets/Textures/woodCrate_diffuse.png </summary>
                public const string woodCrate_diffuse_png = "Content/Assets/Textures/woodCrate_diffuse.png";
            }
            
            public sealed class Materials
            {
                
                /// <summary> Path to Content/Assets/Materials/ballMat.wmat </summary>
                public const string ballMat = "Content/Assets/Materials/ballMat.wmat";
                
                /// <summary> Path to Content/Assets/Materials/crateMat.wmat </summary>
                public const string crateMat = "Content/Assets/Materials/crateMat.wmat";
            }
        }
        
        public sealed class Scenes
        {
            
            /// <summary> Path to Content/Scenes/MyScene.wscene </summary>
            public const string MyScene = "Content/Scenes/MyScene.wscene";
        }
    }
}
