//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// File generated on 21/06/2018 17:35:07
namespace OculusCockpit
{
    using System;
    
    
    public sealed class WaveContent
    {
        
        /// <summary> Path to Content/OculusCockpit.wgame </summary>
        public const string GameInfo = "Content/OculusCockpit.wgame";
        
        public sealed class Assets
        {
            
            /// <summary> Path to Content/Assets/ShoperCockpit.fbx </summary>
            public const string ShoperCockpit_fbx = "Content/Assets/ShoperCockpit.fbx";
            
            public sealed class Model
            {
                
                /// <summary> Path to Content/Assets/Model/ShoperCockpit.fbx </summary>
                public const string ShoperCockpit_fbx = "Content/Assets/Model/ShoperCockpit.fbx";
            }
            
            public sealed class Sounds
            {
                
                /// <summary> Path to Content/Assets/Sounds/helicopter.wav </summary>
                public const string helicopter_wav = "Content/Assets/Sounds/helicopter.wav";
            }
            
            public sealed class Texture
            {
                
                /// <summary> Path to Content/Assets/Texture/fuse.png </summary>
                public const string fuse_png = "Content/Assets/Texture/fuse.png";
                
                /// <summary> Path to Content/Assets/Texture/gazelle_interior.png </summary>
                public const string gazelle_interior_png = "Content/Assets/Texture/gazelle_interior.png";
                
                /// <summary> Path to Content/Assets/Texture/inn.png </summary>
                public const string inn_png = "Content/Assets/Texture/inn.png";
                
                /// <summary> Path to Content/Assets/Texture/interior04LightingMap.png </summary>
                public const string interior04LightingMap_png = "Content/Assets/Texture/interior04LightingMap.png";
                
                /// <summary> Path to Content/Assets/Texture/Skybox.cubemap </summary>
                public const string Skybox_cubemap = "Content/Assets/Texture/Skybox.cubemap";
            }
            
            public sealed class Materials
            {
                
                /// <summary> Path to Content/Assets/Materials/04 - Default.wmat </summary>
                public const string _04_Default = "Content/Assets/Materials/04 - Default.wmat";
                
                /// <summary> Path to Content/Assets/Materials/06 - Default.wmat </summary>
                public const string _06_Default = "Content/Assets/Materials/06 - Default.wmat";
                
                /// <summary> Path to Content/Assets/Materials/Mat.001_gazelle_interior.png.wmat </summary>
                public const string Mat_001_gazelle_interior_png = "Content/Assets/Materials/Mat.001_gazelle_interior.png.wmat";
                
                /// <summary> Path to Content/Assets/Materials/Mat_fuse.png.wmat </summary>
                public const string Mat_fuse_png = "Content/Assets/Materials/Mat_fuse.png.wmat";
            }
        }
        
        public sealed class RenderLayers
        {
            
            /// <summary>Id of Opaque</summary>
            public const int Opaque = 0;
            
            /// <summary>Id of Skybox</summary>
            public const int Skybox = 1;
            
            /// <summary>Id of Alpha</summary>
            public const int Alpha = 2;
            
            /// <summary>Id of Additive</summary>
            public const int Additive = 3;
            
            /// <summary>Id of GUI</summary>
            public const int GUI = 4;
            
            /// <summary>Id of Debug</summary>
            public const int Debug = 5;
        }
        
        public sealed class Scenes
        {
            
            /// <summary> Path to Content/Scenes/MyScene.wscene </summary>
            public const string MyScene = "Content/Scenes/MyScene.wscene";
        }
    }
}
