//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// File generated on 8/2/2017 1:54:28 PM
namespace Touch
{
    using System;
    
    
    public sealed class WaveContent
    {
        
        /// <summary> Path to Content/Touch.wgame </summary>
        public const string GameInfo = "Content/Touch.wgame";
        
        public sealed class Assets
        {
            
            /// <summary> Path to Content/Assets/Touch.png </summary>
            public const string Touch_png = "Content/Assets/Touch.png";
        }
        
        public sealed class Scenes
        {
            
            /// <summary> Path to Content/Scenes/MyScene.wscene </summary>
            public const string MyScene = "Content/Scenes/MyScene.wscene";
        }
    }
}
