//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// File generated on 6/25/2018 4:44:28 PM
namespace Project
{
    using System;
    
    
    public sealed class WaveContent
    {
        
        /// <summary> Path to Content/Project.wgame </summary>
        public const string GameInfo = "Content/Project.wgame";
        
        public sealed class RenderLayers
        {
            
            /// <summary>Id of Opaque</summary>
            public const int Opaque = 0;
            
            /// <summary>Id of Skybox</summary>
            public const int Skybox = 1;
            
            /// <summary>Id of Alpha</summary>
            public const int Alpha = 2;
            
            /// <summary>Id of Additive</summary>
            public const int Additive = 3;
            
            /// <summary>Id of GUI</summary>
            public const int GUI = 4;
            
            /// <summary>Id of Debug</summary>
            public const int Debug = 5;
        }
        
        public sealed class Assets
        {
            
            /// <summary> Path to Content/Assets/blueMat.wmat </summary>
            public const string blueMat = "Content/Assets/blueMat.wmat";
            
            /// <summary> Path to Content/Assets/grayMat.wmat </summary>
            public const string grayMat = "Content/Assets/grayMat.wmat";
            
            /// <summary> Path to Content/Assets/greenMat.wmat </summary>
            public const string greenMat = "Content/Assets/greenMat.wmat";
            
            /// <summary> Path to Content/Assets/lightBlueMat.wmat </summary>
            public const string lightBlueMat = "Content/Assets/lightBlueMat.wmat";
            
            /// <summary> Path to Content/Assets/orangeMat.wmat </summary>
            public const string orangeMat = "Content/Assets/orangeMat.wmat";
            
            /// <summary> Path to Content/Assets/redMat.wmat </summary>
            public const string redMat = "Content/Assets/redMat.wmat";
            
            /// <summary> Path to Content/Assets/violetMat.wmat </summary>
            public const string violetMat = "Content/Assets/violetMat.wmat";
            
            /// <summary> Path to Content/Assets/yellowMat.wmat </summary>
            public const string yellowMat = "Content/Assets/yellowMat.wmat";
        }
        
        public sealed class Scenes
        {
            
            /// <summary> Path to Content/Scenes/MyScene.wscene </summary>
            public const string MyScene = "Content/Scenes/MyScene.wscene";
        }
    }
}
