//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// File generated on 8/9/2017 9:45:13 AM
namespace Motor3D
{
    using System;
    
    
    public sealed class WaveContent
    {
        
        /// <summary> Path to Content/Motor3D.wgame </summary>
        public const string GameInfo = "Content/Motor3D.wgame";
        
        public sealed class Assets
        {
            
            /// <summary> Path to Content/Assets/checkered.jpg </summary>
            public const string checkered_jpg = "Content/Assets/checkered.jpg";
            
            /// <summary> Path to Content/Assets/Terrain.fbx </summary>
            public const string Terrain_fbx = "Content/Assets/Terrain.fbx";
            
            /// <summary> Path to Content/Assets/basicMaterial.wmat </summary>
            public const string basicMaterial = "Content/Assets/basicMaterial.wmat";
            
            public sealed class Materials
            {
                
                /// <summary> Path to Content/Assets/Materials/DefaultMaterial.wmat </summary>
                public const string DefaultMaterial = "Content/Assets/Materials/DefaultMaterial.wmat";
            }
        }
        
        public sealed class Scenes
        {
            
            /// <summary> Path to Content/Scenes/MyScene.wscene </summary>
            public const string MyScene = "Content/Scenes/MyScene.wscene";
        }
    }
}
