//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// File generated on 07/02/2017 16:04:54
namespace Jenga
{
    using System;
    
    
    public sealed class WaveContent
    {
        
        public sealed class Assets
        {
            
            /// <summary> Path to Content/Assets/cardpaper.jpg </summary>
            public const string cardpaper_jpg = "Content/Assets/cardpaper.jpg";
            
            /// <summary> Path to Content/Assets/wood.jpg </summary>
            public const string wood_jpg = "Content/Assets/wood.jpg";
            
            /// <summary> Path to Content/Assets/brick_mat.wmat </summary>
            public const string brick_mat = "Content/Assets/brick_mat.wmat";
            
            /// <summary> Path to Content/Assets/wood_mat.wmat </summary>
            public const string wood_mat = "Content/Assets/wood_mat.wmat";
        }
        
        public sealed class Scenes
        {
            
            /// <summary> Path to Content/Scenes/MyScene.wscene </summary>
            public const string MyScene = "Content/Scenes/MyScene.wscene";
        }
    }
}
