//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// File generated on 1/18/2016 2:33:49 PM
namespace OnPhysics2dCollisionEvent
{
    using System;
    
    
    public sealed class WaveContent
    {
        
        public sealed class Assets
        {
            
            /// <summary> Path to Content/Assets/Arrow.png </summary>
            public const string Arrow_png = "Content/Assets/Arrow.png";
            
            /// <summary> Path to Content/Assets/CircleSprite.png </summary>
            public const string CircleSprite_png = "Content/Assets/CircleSprite.png";
            
            /// <summary> Path to Content/Assets/CrateA.png </summary>
            public const string CrateA_png = "Content/Assets/CrateA.png";
            
            /// <summary> Path to Content/Assets/GroundSprite.png </summary>
            public const string GroundSprite_png = "Content/Assets/GroundSprite.png";
            
            /// <summary> Path to Content/Assets/Mark.png </summary>
            public const string Mark_png = "Content/Assets/Mark.png";
        }
        
        public sealed class Scenes
        {
            
            /// <summary> Path to Content/Scenes/MyScene.wscene </summary>
            public const string MyScene = "Content/Scenes/MyScene.wscene";
        }
    }
}
