// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

// File generated on 1/18/2016 7:14:09 AM
namespace FixedJoint
{
    using System;
    
    
    public sealed class WaveContent
    {
        
        public sealed class Assets
        {
            
            /// <summary> Path to Content/Assets/BallMaterial.wmat </summary>
            public const string BallMaterial = "Content/Assets/BallMaterial.wmat";
            
            /// <summary> Path to Content/Assets/BoxAMaterial.wmat </summary>
            public const string BoxAMaterial = "Content/Assets/BoxAMaterial.wmat";
            
            /// <summary> Path to Content/Assets/BoxBMaterial.wmat </summary>
            public const string BoxBMaterial = "Content/Assets/BoxBMaterial.wmat";
            
            /// <summary> Path to Content/Assets/GroundMaterial.wmat </summary>
            public const string GroundMaterial = "Content/Assets/GroundMaterial.wmat";
        }
        
        public sealed class Scenes
        {
            
            /// <summary> Path to Content/Scenes/MyScene.wscene </summary>
            public const string MyScene = "Content/Scenes/MyScene.wscene";
        }
    }
}
