//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// File generated on 4/19/2018 3:18:26 PM
namespace LensFlare
{
    using System;
    
    
    public sealed class WaveContent
    {
        
        /// <summary> Path to Content/LensFlare.wgame </summary>
        public const string GameInfo = "Content/LensFlare.wgame";
        
        public sealed class Assets
        {
            
            public sealed class Models
            {
                
                /// <summary> Path to Content/Assets/Models/planet.fbx </summary>
                public const string planet_fbx = "Content/Assets/Models/planet.fbx";
                
                public sealed class Materials
                {
                    
                    /// <summary> Path to Content/Assets/Models/Materials/01 - Default.wmat </summary>
                    public const string _01_Default = "Content/Assets/Models/Materials/01 - Default.wmat";
                }
            }
            
            public sealed class Textures
            {
                
                /// <summary> Path to Content/Assets/Textures/EarthDiffuseMap.png </summary>
                public const string EarthDiffuseMap_png = "Content/Assets/Textures/EarthDiffuseMap.png";
                
                /// <summary> Path to Content/Assets/Textures/EarthNormalMap.png </summary>
                public const string EarthNormalMap_png = "Content/Assets/Textures/EarthNormalMap.png";
                
                /// <summary> Path to Content/Assets/Textures/EarthSpecMap.png </summary>
                public const string EarthSpecMap_png = "Content/Assets/Textures/EarthSpecMap.png";
                
                /// <summary> Path to Content/Assets/Textures/MoonDiffuseMap.png </summary>
                public const string MoonDiffuseMap_png = "Content/Assets/Textures/MoonDiffuseMap.png";
                
                /// <summary> Path to Content/Assets/Textures/MoonNormMap.png </summary>
                public const string MoonNormMap_png = "Content/Assets/Textures/MoonNormMap.png";
                
                /// <summary> Path to Content/Assets/Textures/MoonSpecMap.png </summary>
                public const string MoonSpecMap_png = "Content/Assets/Textures/MoonSpecMap.png";
                
                public sealed class Flares
                {
                    
                    /// <summary> Path to Content/Assets/Textures/Flares/flare1.png </summary>
                    public const string flare1_png = "Content/Assets/Textures/Flares/flare1.png";
                    
                    /// <summary> Path to Content/Assets/Textures/Flares/flare2.png </summary>
                    public const string flare2_png = "Content/Assets/Textures/Flares/flare2.png";
                    
                    /// <summary> Path to Content/Assets/Textures/Flares/flare3.png </summary>
                    public const string flare3_png = "Content/Assets/Textures/Flares/flare3.png";
                    
                    /// <summary> Path to Content/Assets/Textures/Flares/flare4.png </summary>
                    public const string flare4_png = "Content/Assets/Textures/Flares/flare4.png";
                    
                    /// <summary> Path to Content/Assets/Textures/Flares/flare5.png </summary>
                    public const string flare5_png = "Content/Assets/Textures/Flares/flare5.png";
                    
                    /// <summary> Path to Content/Assets/Textures/Flares/flareTexture.png </summary>
                    public const string flareTexture_png = "Content/Assets/Textures/Flares/flareTexture.png";
                }
            }
            
            public sealed class Materials
            {
                
                /// <summary> Path to Content/Assets/Materials/earthMaterial.wmat </summary>
                public const string earthMaterial = "Content/Assets/Materials/earthMaterial.wmat";
                
                /// <summary> Path to Content/Assets/Materials/MoonMaterial.wmat </summary>
                public const string MoonMaterial = "Content/Assets/Materials/MoonMaterial.wmat";
            }
        }
        
        public sealed class RenderLayers
        {
            
            /// <summary>Id of Opaque</summary>
            public const int Opaque = 0;
            
            /// <summary>Id of Skybox</summary>
            public const int Skybox = 1;
            
            /// <summary>Id of Alpha</summary>
            public const int Alpha = 2;
            
            /// <summary>Id of Additive</summary>
            public const int Additive = 3;
            
            /// <summary>Id of GUI</summary>
            public const int GUI = 4;
            
            /// <summary>Id of Debug</summary>
            public const int Debug = 5;
        }
        
        public sealed class Scenes
        {
            
            /// <summary> Path to Content/Scenes/MyScene.wscene </summary>
            public const string MyScene = "Content/Scenes/MyScene.wscene";
        }
    }
}
