//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// File generated on 9/11/2015 7:27:13 PM
namespace LensFlare
{
    using System;
    
    
    public sealed class WaveContent
    {
        
        public sealed class Assets
        {
            
            public sealed class Models
            {
                
                /// <summary> Path to Content/Assets/Models/planet.fbx </summary>
                public const string planet_fbx = "Content/Assets/Models/planet.fbx";
            }
            
            public sealed class Textures
            {
                
                /// <summary> Path to Content/Assets/Textures/EarthDiffuseMap.png </summary>
                public const string EarthDiffuseMap_png = "Content/Assets/Textures/EarthDiffuseMap.png";
                
                /// <summary> Path to Content/Assets/Textures/MoonDiffuseMap.jpg </summary>
                public const string MoonDiffuseMap_jpg = "Content/Assets/Textures/MoonDiffuseMap.jpg";
                
                public sealed class Flares
                {
                    
                    /// <summary> Path to Content/Assets/Textures/Flares/flare1.png </summary>
                    public const string flare1_png = "Content/Assets/Textures/Flares/flare1.png";
                    
                    /// <summary> Path to Content/Assets/Textures/Flares/flare2.png </summary>
                    public const string flare2_png = "Content/Assets/Textures/Flares/flare2.png";
                    
                    /// <summary> Path to Content/Assets/Textures/Flares/flare3.png </summary>
                    public const string flare3_png = "Content/Assets/Textures/Flares/flare3.png";
                    
                    /// <summary> Path to Content/Assets/Textures/Flares/flare4.png </summary>
                    public const string flare4_png = "Content/Assets/Textures/Flares/flare4.png";
                    
                    /// <summary> Path to Content/Assets/Textures/Flares/flare5.png </summary>
                    public const string flare5_png = "Content/Assets/Textures/Flares/flare5.png";
                    
                    /// <summary> Path to Content/Assets/Textures/Flares/flareTexture.jpg </summary>
                    public const string flareTexture_jpg = "Content/Assets/Textures/Flares/flareTexture.jpg";
                }
            }
            
            public sealed class Materials
            {
                
                /// <summary> Path to Content/Assets/Materials/earthMaterial.wmat </summary>
                public const string earthMaterial = "Content/Assets/Materials/earthMaterial.wmat";
                
                /// <summary> Path to Content/Assets/Materials/MoonMaterial.wmat </summary>
                public const string MoonMaterial = "Content/Assets/Materials/MoonMaterial.wmat";
            }
        }
        
        public sealed class Scenes
        {
            
            /// <summary> Path to Content/Scenes/MyScene.wscene </summary>
            public const string MyScene = "Content/Scenes/MyScene.wscene";
        }
    }
}
