//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// File generated on 12/04/2018 16:56:33
namespace Loading
{
    using System;
    
    
    public sealed class WaveContent
    {
        
        /// <summary> Path to Content/Loading.wgame </summary>
        public const string GameInfo = "Content/Loading.wgame";
        
        public sealed class Assets
        {
            
            /// <summary> Path to Content/Assets/Background.png </summary>
            public const string Background_png = "Content/Assets/Background.png";
            
            /// <summary> Path to Content/Assets/LoadingSpankerImg.png </summary>
            public const string LoadingSpankerImg_png = "Content/Assets/LoadingSpankerImg.png";
            
            /// <summary> Path to Content/Assets/LoadingSpankerText.png </summary>
            public const string LoadingSpankerText_png = "Content/Assets/LoadingSpankerText.png";
            
            /// <summary> Path to Content/Assets/Start.png </summary>
            public const string Start_png = "Content/Assets/Start.png";
        }
        
        public sealed class RenderLayers
        {
            
            /// <summary>Id of Opaque</summary>
            public const int Opaque = 0;
            
            /// <summary>Id of Skybox</summary>
            public const int Skybox = 1;
            
            /// <summary>Id of Alpha</summary>
            public const int Alpha = 2;
            
            /// <summary>Id of Additive</summary>
            public const int Additive = 3;
            
            /// <summary>Id of GUI</summary>
            public const int GUI = 4;
            
            /// <summary>Id of Debug</summary>
            public const int Debug = 5;
        }
        
        public sealed class Scenes
        {
            
            /// <summary> Path to Content/Scenes/GameScene.wscene </summary>
            public const string GameScene = "Content/Scenes/GameScene.wscene";
            
            /// <summary> Path to Content/Scenes/LoadingScene.wscene </summary>
            public const string LoadingScene = "Content/Scenes/LoadingScene.wscene";
        }
    }
}
