//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// File generated on 14/09/2015 8:59:58
namespace Loading
{
    using System;
    
    
    public sealed class WaveContent
    {
        
        public sealed class Assets
        {
            
            /// <summary> Path to Content/Assets/Background.png </summary>
            public const string Background_png = "Content/Assets/Background.png";
            
            /// <summary> Path to Content/Assets/LoadingSpankerImg.png </summary>
            public const string LoadingSpankerImg_png = "Content/Assets/LoadingSpankerImg.png";
            
            /// <summary> Path to Content/Assets/LoadingSpankerText.png </summary>
            public const string LoadingSpankerText_png = "Content/Assets/LoadingSpankerText.png";
            
            /// <summary> Path to Content/Assets/Start.png </summary>
            public const string Start_png = "Content/Assets/Start.png";
        }
        
        public sealed class Scenes
        {
            
            /// <summary> Path to Content/Scenes/GameScene.wscene </summary>
            public const string GameScene = "Content/Scenes/GameScene.wscene";
            
            /// <summary> Path to Content/Scenes/LoadingScene.wscene </summary>
            public const string LoadingScene = "Content/Scenes/LoadingScene.wscene";
        }
    }
}
