//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// File generated on 10/15/2015 4:51:10 PM
namespace AnalyticsDemo
{
    using System;
    
    
    public sealed class WaveContent
    {
        
        public sealed class Assets
        {
            
            /// <summary> Path to Content/Assets/colonel.png </summary>
            public const string colonel_png = "Content/Assets/colonel.png";
            
            /// <summary> Path to Content/Assets/colonelPressed.png </summary>
            public const string colonelPressed_png = "Content/Assets/colonelPressed.png";
            
            /// <summary> Path to Content/Assets/fuzz.png </summary>
            public const string fuzz_png = "Content/Assets/fuzz.png";
            
            /// <summary> Path to Content/Assets/fuzzPressed.png </summary>
            public const string fuzzPressed_png = "Content/Assets/fuzzPressed.png";
            
            /// <summary> Path to Content/Assets/spanker.png </summary>
            public const string spanker_png = "Content/Assets/spanker.png";
            
            /// <summary> Path to Content/Assets/spankerPressed.png </summary>
            public const string spankerPressed_png = "Content/Assets/spankerPressed.png";
        }
        
        public sealed class Scenes
        {
            
            /// <summary> Path to Content/Scenes/MyScene.wscene </summary>
            public const string MyScene = "Content/Scenes/MyScene.wscene";
        }
    }
}
