//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// File generated on 18/08/2015 14:37:50
namespace CameraCapture
{
    using System;
    
    
    public sealed class WaveContent
    {
        
        public sealed class Assets
        {
            
            /// <summary> Path to Content/Assets/TvRoomLightingMap.png </summary>
            public const string TvRoomLightingMap_png = "Content/Assets/TvRoomLightingMap.png";
            
            public sealed class Model
            {
                
                /// <summary> Path to Content/Assets/Model/TvRoom.fbx </summary>
                public const string TvRoom_fbx = "Content/Assets/Model/TvRoom.fbx";
            }
            
            public sealed class Texture
            {
                
                /// <summary> Path to Content/Assets/Texture/Chair_Difuse.png </summary>
                public const string Chair_Difuse_png = "Content/Assets/Texture/Chair_Difuse.png";
                
                /// <summary> Path to Content/Assets/Texture/parketFloor_Difuse.png </summary>
                public const string parketFloor_Difuse_png = "Content/Assets/Texture/parketFloor_Difuse.png";
                
                /// <summary> Path to Content/Assets/Texture/table_Difuse.png </summary>
                public const string table_Difuse_png = "Content/Assets/Texture/table_Difuse.png";
                
                /// <summary> Path to Content/Assets/Texture/Tv_Difuse.png </summary>
                public const string Tv_Difuse_png = "Content/Assets/Texture/Tv_Difuse.png";
            }
            
            public sealed class Material
            {
                
                /// <summary> Path to Content/Assets/Material/black_Difuse.wmat.wmat </summary>
                public const string black_Difuse_wmat = "Content/Assets/Material/black_Difuse.wmat.wmat";
                
                /// <summary> Path to Content/Assets/Material/chair_Difuse.wmat.wmat </summary>
                public const string chair_Difuse_wmat = "Content/Assets/Material/chair_Difuse.wmat.wmat";
                
                /// <summary> Path to Content/Assets/Material/parketFloor_Difuse.wmat.wmat </summary>
                public const string parketFloor_Difuse_wmat = "Content/Assets/Material/parketFloor_Difuse.wmat.wmat";
                
                /// <summary> Path to Content/Assets/Material/table_Difuse.wmat.wmat </summary>
                public const string table_Difuse_wmat = "Content/Assets/Material/table_Difuse.wmat.wmat";
                
                /// <summary> Path to Content/Assets/Material/tv_Difuse.wmat </summary>
                public const string tv_Difuse = "Content/Assets/Material/tv_Difuse.wmat";
            }
        }
        
        public sealed class Scenes
        {
            
            /// <summary> Path to Content/Scenes/MyScene.wscene </summary>
            public const string MyScene = "Content/Scenes/MyScene.wscene";
        }
    }
}
