//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// File generated on 8/3/2017 12:36:43 PM
namespace CameraCapture
{
    using System;
    
    
    public sealed class WaveContent
    {
        
        /// <summary> Path to Content/CameraCapture.wgame </summary>
        public const string GameInfo = "Content/CameraCapture.wgame";
        
        public sealed class Assets
        {
            
            /// <summary> Path to Content/Assets/TvRoomLightingMap.png </summary>
            public const string TvRoomLightingMap_png = "Content/Assets/TvRoomLightingMap.png";
            
            public sealed class Model
            {
                
                /// <summary> Path to Content/Assets/Model/TvRoom.fbx </summary>
                public const string TvRoom_fbx = "Content/Assets/Model/TvRoom.fbx";
            }
            
            public sealed class Texture
            {
                
                /// <summary> Path to Content/Assets/Texture/Chair_Difuse.png </summary>
                public const string Chair_Difuse_png = "Content/Assets/Texture/Chair_Difuse.png";
                
                /// <summary> Path to Content/Assets/Texture/parketFloor_Difuse.png </summary>
                public const string parketFloor_Difuse_png = "Content/Assets/Texture/parketFloor_Difuse.png";
                
                /// <summary> Path to Content/Assets/Texture/table_Difuse.png </summary>
                public const string table_Difuse_png = "Content/Assets/Texture/table_Difuse.png";
                
                /// <summary> Path to Content/Assets/Texture/Tv_Difuse.png </summary>
                public const string Tv_Difuse_png = "Content/Assets/Texture/Tv_Difuse.png";
            }
            
            public sealed class Material
            {
                
                /// <summary> Path to Content/Assets/Material/ChairMaterial.wmat </summary>
                public const string ChairMaterial = "Content/Assets/Material/ChairMaterial.wmat";
                
                /// <summary> Path to Content/Assets/Material/ParketMaterial.wmat </summary>
                public const string ParketMaterial = "Content/Assets/Material/ParketMaterial.wmat";
                
                /// <summary> Path to Content/Assets/Material/TableMaterial.wmat </summary>
                public const string TableMaterial = "Content/Assets/Material/TableMaterial.wmat";
                
                /// <summary> Path to Content/Assets/Material/TVMaterial.wmat </summary>
                public const string TVMaterial = "Content/Assets/Material/TVMaterial.wmat";
                
                /// <summary> Path to Content/Assets/Material/TVScreenMaterial.wmat </summary>
                public const string TVScreenMaterial = "Content/Assets/Material/TVScreenMaterial.wmat";
            }
        }
        
        public sealed class Scenes
        {
            
            /// <summary> Path to Content/Scenes/MyScene.wscene </summary>
            public const string MyScene = "Content/Scenes/MyScene.wscene";
        }
    }
}
