//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// File generated on 10/04/2018 16:49:02
namespace CameraCapture
{
    using System;
    
    
    public sealed class WaveContent
    {
        
        /// <summary> Path to Content/CameraCapture.wgame </summary>
        public const string GameInfo = "Content/CameraCapture.wgame";
        
        public sealed class Assets
        {
            
            /// <summary> Path to Content/Assets/TvRoom.fbx </summary>
            public const string TvRoom_fbx = "Content/Assets/TvRoom.fbx";
            
            public sealed class Texture
            {
                
                /// <summary> Path to Content/Assets/Texture/Chair_Difuse.png </summary>
                public const string Chair_Difuse_png = "Content/Assets/Texture/Chair_Difuse.png";
                
                /// <summary> Path to Content/Assets/Texture/parketFloor_Difuse.png </summary>
                public const string parketFloor_Difuse_png = "Content/Assets/Texture/parketFloor_Difuse.png";
                
                /// <summary> Path to Content/Assets/Texture/table_Difuse.png </summary>
                public const string table_Difuse_png = "Content/Assets/Texture/table_Difuse.png";
                
                /// <summary> Path to Content/Assets/Texture/TvRoomLightingMap.png </summary>
                public const string TvRoomLightingMap_png = "Content/Assets/Texture/TvRoomLightingMap.png";
                
                /// <summary> Path to Content/Assets/Texture/Tv_Difuse.png </summary>
                public const string Tv_Difuse_png = "Content/Assets/Texture/Tv_Difuse.png";
            }
            
            public sealed class Materials
            {
                
                /// <summary> Path to Content/Assets/Materials/chairMat.wmat </summary>
                public const string chairMat = "Content/Assets/Materials/chairMat.wmat";
                
                /// <summary> Path to Content/Assets/Materials/floorMat.wmat </summary>
                public const string floorMat = "Content/Assets/Materials/floorMat.wmat";
                
                /// <summary> Path to Content/Assets/Materials/screenMat.wmat </summary>
                public const string screenMat = "Content/Assets/Materials/screenMat.wmat";
                
                /// <summary> Path to Content/Assets/Materials/tableMat.wmat </summary>
                public const string tableMat = "Content/Assets/Materials/tableMat.wmat";
                
                /// <summary> Path to Content/Assets/Materials/tvMat.wmat </summary>
                public const string tvMat = "Content/Assets/Materials/tvMat.wmat";
            }
        }
        
        public sealed class RenderLayers
        {
            
            /// <summary>Id of Opaque</summary>
            public const int Opaque = 0;
            
            /// <summary>Id of Skybox</summary>
            public const int Skybox = 1;
            
            /// <summary>Id of Alpha</summary>
            public const int Alpha = 2;
            
            /// <summary>Id of Additive</summary>
            public const int Additive = 3;
            
            /// <summary>Id of GUI</summary>
            public const int GUI = 4;
            
            /// <summary>Id of Debug</summary>
            public const int Debug = 5;
        }
        
        public sealed class Scenes
        {
            
            /// <summary> Path to Content/Scenes/MyScene.wscene </summary>
            public const string MyScene = "Content/Scenes/MyScene.wscene";
        }
    }
}
