//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// File generated on 4/5/2018 4:26:05 PM
namespace BokehSample
{
    using System;
    
    
    public sealed class WaveContent
    {
        
        /// <summary> Path to Content/BokehSample.wgame </summary>
        public const string GameInfo = "Content/BokehSample.wgame";
        
        public sealed class Assets
        {
            
            /// <summary> Path to Content/Assets/dust.fbx </summary>
            public const string dust_fbx = "Content/Assets/dust.fbx";
            
            /// <summary> Path to Content/Assets/dust.png </summary>
            public const string dust_png = "Content/Assets/dust.png";
            
            /// <summary> Path to Content/Assets/fantasyTrees.fbx </summary>
            public const string fantasyTrees_fbx = "Content/Assets/fantasyTrees.fbx";
            
            /// <summary> Path to Content/Assets/forestLightingMap.png </summary>
            public const string forestLightingMap_png = "Content/Assets/forestLightingMap.png";
            
            /// <summary> Path to Content/Assets/forestSprite.png </summary>
            public const string forestSprite_png = "Content/Assets/forestSprite.png";
            
            /// <summary> Path to Content/Assets/skybox.jpg </summary>
            public const string skybox_jpg = "Content/Assets/skybox.jpg";
            
            /// <summary> Path to Content/Assets/skydome.fbx </summary>
            public const string skydome_fbx = "Content/Assets/skydome.fbx";
            
            public sealed class Materials
            {
                
                /// <summary> Path to Content/Assets/Materials/01 - Default.wmat </summary>
                public const string _01_Default = "Content/Assets/Materials/01 - Default.wmat";
                
                /// <summary> Path to Content/Assets/Materials/DefaultMaterial.wmat </summary>
                public const string DefaultMaterial = "Content/Assets/Materials/DefaultMaterial.wmat";
                
                /// <summary> Path to Content/Assets/Materials/dustMaterial.wmat </summary>
                public const string dustMaterial = "Content/Assets/Materials/dustMaterial.wmat";
                
                /// <summary> Path to Content/Assets/Materials/Material__507.wmat </summary>
                public const string Material__507 = "Content/Assets/Materials/Material__507.wmat";
                
                /// <summary> Path to Content/Assets/Materials/skyBox.wmat </summary>
                public const string skyBox = "Content/Assets/Materials/skyBox.wmat";
            }
        }
        
        public sealed class RenderLayers
        {
            
            /// <summary>Id of Opaque</summary>
            public const int Opaque = 0;
            
            /// <summary>Id of Skybox</summary>
            public const int Skybox = 1;
            
            /// <summary>Id of Alpha</summary>
            public const int Alpha = 2;
            
            /// <summary>Id of Additive</summary>
            public const int Additive = 3;
            
            /// <summary>Id of GUI</summary>
            public const int GUI = 4;
            
            /// <summary>Id of Debug</summary>
            public const int Debug = 5;
        }
        
        public sealed class Scenes
        {
            
            /// <summary> Path to Content/Scenes/MyScene.wscene </summary>
            public const string MyScene = "Content/Scenes/MyScene.wscene";
        }
    }
}
