//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// File generated on 9/9/2016 12:55:42 PM
namespace BokehSample
{
    using System;
    
    
    public sealed class WaveContent
    {
        
        public sealed class Assets
        {
            
            /// <summary> Path to Content/Assets/dust.fbx </summary>
            public const string dust_fbx = "Content/Assets/dust.fbx";
            
            /// <summary> Path to Content/Assets/dust.png </summary>
            public const string dust_png = "Content/Assets/dust.png";
            
            /// <summary> Path to Content/Assets/fantasyTrees.fbx </summary>
            public const string fantasyTrees_fbx = "Content/Assets/fantasyTrees.fbx";
            
            /// <summary> Path to Content/Assets/forestLightingMap.png </summary>
            public const string forestLightingMap_png = "Content/Assets/forestLightingMap.png";
            
            /// <summary> Path to Content/Assets/forestSprite.png </summary>
            public const string forestSprite_png = "Content/Assets/forestSprite.png";
            
            /// <summary> Path to Content/Assets/skybox.jpg </summary>
            public const string skybox_jpg = "Content/Assets/skybox.jpg";
            
            /// <summary> Path to Content/Assets/skydome.fbx </summary>
            public const string skydome_fbx = "Content/Assets/skydome.fbx";
            
            /// <summary> Path to Content/Assets/dustMaterial.wmat </summary>
            public const string dustMaterial = "Content/Assets/dustMaterial.wmat";
            
            /// <summary> Path to Content/Assets/forest.wmat </summary>
            public const string forest = "Content/Assets/forest.wmat";
            
            /// <summary> Path to Content/Assets/skybox.wmat </summary>
            public const string skybox = "Content/Assets/skybox.wmat";
        }
        
        public sealed class Scenes
        {
            
            /// <summary> Path to Content/Scenes/MyScene.wscene </summary>
            public const string MyScene = "Content/Scenes/MyScene.wscene";
        }
    }
}
