// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

// File generated on 1/18/2016 4:19:39 AM
namespace FixedMouseJoint2DSample
{
    using System;
    
    
    public sealed class WaveContent
    {
        
        public sealed class Assets
        {
            
            /// <summary> Path to Content/Assets/boxSprite.png </summary>
            public const string boxSprite_png = "Content/Assets/boxSprite.png";
            
            /// <summary> Path to Content/Assets/groundSprite.png </summary>
            public const string groundSprite_png = "Content/Assets/groundSprite.png";
        }
        
        public sealed class Scenes
        {
            
            /// <summary> Path to Content/Scenes/MyScene.wscene </summary>
            public const string MyScene = "Content/Scenes/MyScene.wscene";
        }
    }
}
