//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// File generated on 8/3/2017 12:40:55 PM
namespace Music
{
    using System;
    
    
    public sealed class WaveContent
    {
        
        /// <summary> Path to Content/Music.wgame </summary>
        public const string GameInfo = "Content/Music.wgame";
        
        public sealed class Assets
        {
            
            /// <summary> Path to Content/Assets/ByeByeBrain.mp3 </summary>
            public const string ByeByeBrain_mp3 = "Content/Assets/ByeByeBrain.mp3";
        }
        
        public sealed class Scenes
        {
            
            /// <summary> Path to Content/Scenes/MyScene.wscene </summary>
            public const string MyScene = "Content/Scenes/MyScene.wscene";
        }
    }
}
