// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

// File generated on 1/27/2016 8:30:38 AM
namespace RenderTarget
{
    using System;
    
    
    public sealed class WaveContent
    {
        
        public sealed class Assets
        {
            
            /// <summary> Path to Content/Assets/MyMaterial.wmat </summary>
            public const string MyMaterial = "Content/Assets/MyMaterial.wmat";
        }
        
        public sealed class Scenes
        {
            
            /// <summary> Path to Content/Scenes/MyScene.wscene </summary>
            public const string MyScene = "Content/Scenes/MyScene.wscene";
            
            /// <summary> Path to Content/Scenes/RenderTargetScene.wscene </summary>
            public const string RenderTargetScene = "Content/Scenes/RenderTargetScene.wscene";
        }
    }
}
