//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// File generated on 25/08/2015 14:57:23
namespace StockRoom
{
    using System;
    
    
    public sealed class WaveContent
    {
        
        public sealed class Assets
        {
            
            /// <summary> Path to Content/Assets/box.fbx </summary>
            public const string box_fbx = "Content/Assets/box.fbx";
            
            /// <summary> Path to Content/Assets/boxTexture.png </summary>
            public const string boxTexture_png = "Content/Assets/boxTexture.png";
            
            /// <summary> Path to Content/Assets/pallet.fbx </summary>
            public const string pallet_fbx = "Content/Assets/pallet.fbx";
            
            /// <summary> Path to Content/Assets/PalletTexture.png </summary>
            public const string PalletTexture_png = "Content/Assets/PalletTexture.png";
            
            /// <summary> Path to Content/Assets/roomTexture.png </summary>
            public const string roomTexture_png = "Content/Assets/roomTexture.png";
            
            /// <summary> Path to Content/Assets/stockRoom.fbx </summary>
            public const string stockRoom_fbx = "Content/Assets/stockRoom.fbx";
            
            /// <summary> Path to Content/Assets/stockRoomFull.fbx </summary>
            public const string stockRoomFull_fbx = "Content/Assets/stockRoomFull.fbx";
            
            /// <summary> Path to Content/Assets/MyMaterial.wmat </summary>
            public const string MyMaterial = "Content/Assets/MyMaterial.wmat";
        }
        
        public sealed class Scenes
        {
            
            /// <summary> Path to Content/Scenes/MyScene.wscene </summary>
            public const string MyScene = "Content/Scenes/MyScene.wscene";
        }
    }
}
