//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// File generated on 07/02/2017 16:05:41
namespace StockRoom
{
    using System;
    
    
    public sealed class WaveContent
    {
        
        public sealed class Assets
        {
            
            /// <summary> Path to Content/Assets/crate.png </summary>
            public const string crate_png = "Content/Assets/crate.png";
            
            /// <summary> Path to Content/Assets/roomTexture.png </summary>
            public const string roomTexture_png = "Content/Assets/roomTexture.png";
            
            /// <summary> Path to Content/Assets/stockRoomFull.fbx </summary>
            public const string stockRoomFull_fbx = "Content/Assets/stockRoomFull.fbx";
            
            public sealed class Material
            {
                
                /// <summary> Path to Content/Assets/Material/CrateMat.wmat </summary>
                public const string CrateMat = "Content/Assets/Material/CrateMat.wmat";
                
                /// <summary> Path to Content/Assets/Material/RoomMat.wmat </summary>
                public const string RoomMat = "Content/Assets/Material/RoomMat.wmat";
                
                /// <summary> Path to Content/Assets/Material/RopeMat.wmat </summary>
                public const string RopeMat = "Content/Assets/Material/RopeMat.wmat";
                
                /// <summary> Path to Content/Assets/Material/TableMaterial.wmat </summary>
                public const string TableMaterial = "Content/Assets/Material/TableMaterial.wmat";
            }
        }
        
        public sealed class Scenes
        {
            
            /// <summary> Path to Content/Scenes/BridgeScene.wscene </summary>
            public const string BridgeScene = "Content/Scenes/BridgeScene.wscene";
            
            /// <summary> Path to Content/Scenes/EmitterScene.wscene </summary>
            public const string EmitterScene = "Content/Scenes/EmitterScene.wscene";
            
            /// <summary> Path to Content/Scenes/WallScene.wscene </summary>
            public const string WallScene = "Content/Scenes/WallScene.wscene";
        }
    }
}
