//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// File generated on 1/20/2016 3:33:56 PM
namespace WallDemo
{
    using System;
    
    
    public sealed class WaveContent
    {
        
        public sealed class Assets
        {
            
            /// <summary> Path to Content/Assets/brickModel.fbx </summary>
            public const string brickModel_fbx = "Content/Assets/brickModel.fbx";
            
            /// <summary> Path to Content/Assets/brickTexture.png </summary>
            public const string brickTexture_png = "Content/Assets/brickTexture.png";
            
            /// <summary> Path to Content/Assets/brickMaterial.wmat </summary>
            public const string brickMaterial = "Content/Assets/brickMaterial.wmat";
        }
        
        public sealed class Scenes
        {
            
            /// <summary> Path to Content/Scenes/MyScene.wscene </summary>
            public const string MyScene = "Content/Scenes/MyScene.wscene";
        }
    }
}
