//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// File generated on 07/02/2017 16:03:07
namespace PhysicExplosion
{
    using System;
    
    
    public sealed class WaveContent
    {
        
        public sealed class Assets
        {
            
            /// <summary> Path to Content/Assets/alienBlue_round.png </summary>
            public const string alienBlue_round_png = "Content/Assets/alienBlue_round.png";
            
            /// <summary> Path to Content/Assets/alienGreen_square.png </summary>
            public const string alienGreen_square_png = "Content/Assets/alienGreen_square.png";
            
            /// <summary> Path to Content/Assets/alienYellow_round.png </summary>
            public const string alienYellow_round_png = "Content/Assets/alienYellow_round.png";
            
            /// <summary> Path to Content/Assets/bomb.png </summary>
            public const string bomb_png = "Content/Assets/bomb.png";
            
            /// <summary> Path to Content/Assets/colored_desert.png </summary>
            public const string colored_desert_png = "Content/Assets/colored_desert.png";
            
            /// <summary> Path to Content/Assets/elementMetal013.png </summary>
            public const string elementMetal013_png = "Content/Assets/elementMetal013.png";
            
            /// <summary> Path to Content/Assets/elementWood013.png </summary>
            public const string elementWood013_png = "Content/Assets/elementWood013.png";
            
            /// <summary> Path to Content/Assets/ground.png </summary>
            public const string ground_png = "Content/Assets/ground.png";
            
            /// <summary> Path to Content/Assets/particle.png </summary>
            public const string particle_png = "Content/Assets/particle.png";
        }
        
        public sealed class Scenes
        {
            
            /// <summary> Path to Content/Scenes/MyScene.wscene </summary>
            public const string MyScene = "Content/Scenes/MyScene.wscene";
        }
    }
}
