//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// File generated on 09/08/2017 14:09:32
namespace Networking
{
    using System;
    
    
    public sealed class WaveContent
    {
        
        /// <summary> Path to Content/Networking.wgame </summary>
        public const string GameInfo = "Content/Networking.wgame";
        
        public sealed class Assets
        {
            
            /// <summary> Path to Content/Assets/Players.spritesheet </summary>
            public const string Players_spritesheet = "Content/Assets/Players.spritesheet";
            
            /// <summary> Texture names from spritesheet Content/Assets/Players.spritesheet </summary>
            public struct Players_spritesheet_TextureName
            {
                
                public const string c1 = "c1";
                
                public const string c2 = "c2";
                
                public const string c3 = "c3";
                
                public const string c4 = "c4";
                
                public const string c5 = "c5";
            }
        }
        
        public sealed class Prefabs
        {
            
            /// <summary> Path to Content/Prefabs/PlayerEntity.wpref </summary>
            public const string PlayerEntity = "Content/Prefabs/PlayerEntity.wpref";
        }
        
        public sealed class Scenes
        {
            
            /// <summary> Path to Content/Scenes/GameScene.wscene </summary>
            public const string GameScene = "Content/Scenes/GameScene.wscene";
            
            /// <summary> Path to Content/Scenes/MainScene.wscene </summary>
            public const string MainScene = "Content/Scenes/MainScene.wscene";
            
            /// <summary> Path to Content/Scenes/SelectPlayerScene.wscene </summary>
            public const string SelectPlayerScene = "Content/Scenes/SelectPlayerScene.wscene";
        }
    }
}
