// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

// File generated on 07/09/2016 10:50:18
namespace Networking
{
    using System;
    
    
    public sealed class WaveContent
    {
        
        public sealed class Assets
        {
            
            /// <summary> Path to Content/Assets/c1.png </summary>
            public const string c1_png = "Content/Assets/c1.png";
            
            /// <summary> Path to Content/Assets/c2.png </summary>
            public const string c2_png = "Content/Assets/c2.png";
            
            /// <summary> Path to Content/Assets/c3.png </summary>
            public const string c3_png = "Content/Assets/c3.png";
            
            /// <summary> Path to Content/Assets/c4.png </summary>
            public const string c4_png = "Content/Assets/c4.png";
            
            /// <summary> Path to Content/Assets/c5.png </summary>
            public const string c5_png = "Content/Assets/c5.png";
        }
        
        public sealed class Scenes
        {
            
            /// <summary> Path to Content/Scenes/MyScene.wscene </summary>
            public const string MyScene = "Content/Scenes/MyScene.wscene";
        }
    }
}
