//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// File generated on 10/04/2018 16:22:26
namespace VideoPlayer
{
    using System;
    
    
    public sealed class WaveContent
    {
        
        /// <summary> Path to Content/VideoPlayer.wgame </summary>
        public const string GameInfo = "Content/VideoPlayer.wgame";
        
        public sealed class Assets
        {
            
            /// <summary> Path to Content/Assets/TvRoom.fbx </summary>
            public const string TvRoom_fbx = "Content/Assets/TvRoom.fbx";
            
            /// <summary> Path to Content/Assets/TvRoomLightingMap.png </summary>
            public const string TvRoomLightingMap_png = "Content/Assets/TvRoomLightingMap.png";
            
            public sealed class textures
            {
                
                /// <summary> Path to Content/Assets/textures/Chair_Difuse.png </summary>
                public const string Chair_Difuse_png = "Content/Assets/textures/Chair_Difuse.png";
                
                /// <summary> Path to Content/Assets/textures/parketFloor_Difuse.png </summary>
                public const string parketFloor_Difuse_png = "Content/Assets/textures/parketFloor_Difuse.png";
                
                /// <summary> Path to Content/Assets/textures/table_Difuse.png </summary>
                public const string table_Difuse_png = "Content/Assets/textures/table_Difuse.png";
                
                /// <summary> Path to Content/Assets/textures/Tv_Difuse.png </summary>
                public const string Tv_Difuse_png = "Content/Assets/textures/Tv_Difuse.png";
            }
            
            public sealed class Video
            {
                
                /// <summary> Path to Content/Assets/Video/bear.mp4 </summary>
                public const string bear_mp4 = "Content/Assets/Video/bear.mp4";
                
                /// <summary> Path to Content/Assets/Video/bunny.mp4 </summary>
                public const string bunny_mp4 = "Content/Assets/Video/bunny.mp4";
            }
            
            public sealed class Materials
            {
                
                /// <summary> Path to Content/Assets/Materials/02 - Default.wmat </summary>
                public const string _02_Default = "Content/Assets/Materials/02 - Default.wmat";
                
                /// <summary> Path to Content/Assets/Materials/Material #1.wmat </summary>
                public const string Material_1 = "Content/Assets/Materials/Material #1.wmat";
                
                /// <summary> Path to Content/Assets/Materials/Material #2.wmat </summary>
                public const string Material_2 = "Content/Assets/Materials/Material #2.wmat";
                
                /// <summary> Path to Content/Assets/Materials/Material #28.wmat </summary>
                public const string Material_28 = "Content/Assets/Materials/Material #28.wmat";
                
                /// <summary> Path to Content/Assets/Materials/_TVtv.wmat </summary>
                public const string _TVtv = "Content/Assets/Materials/_TVtv.wmat";
            }
        }
        
        public sealed class RenderLayers
        {
            
            /// <summary>Id of Opaque</summary>
            public const int Opaque = 0;
            
            /// <summary>Id of Skybox</summary>
            public const int Skybox = 1;
            
            /// <summary>Id of Alpha</summary>
            public const int Alpha = 2;
            
            /// <summary>Id of Additive</summary>
            public const int Additive = 3;
            
            /// <summary>Id of GUI</summary>
            public const int GUI = 4;
            
            /// <summary>Id of Debug</summary>
            public const int Debug = 5;
        }
        
        public sealed class Scenes
        {
            
            /// <summary> Path to Content/Scenes/MyScene.wscene </summary>
            public const string MyScene = "Content/Scenes/MyScene.wscene";
        }
    }
}
