//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// File generated on 13/09/2015 12:22:44
namespace VideoPlayer
{
    using System;
    
    
    public sealed class WaveContent
    {
        
        public sealed class Assets
        {
            
            /// <summary> Path to Content/Assets/TvRoom.fbx </summary>
            public const string TvRoom_fbx = "Content/Assets/TvRoom.fbx";
            
            /// <summary> Path to Content/Assets/TvRoomLightingMap.png </summary>
            public const string TvRoomLightingMap_png = "Content/Assets/TvRoomLightingMap.png";
            
            public sealed class textures
            {
                
                /// <summary> Path to Content/Assets/textures/Chair_Difuse.png </summary>
                public const string Chair_Difuse_png = "Content/Assets/textures/Chair_Difuse.png";
                
                /// <summary> Path to Content/Assets/textures/parketFloor_Difuse.png </summary>
                public const string parketFloor_Difuse_png = "Content/Assets/textures/parketFloor_Difuse.png";
                
                /// <summary> Path to Content/Assets/textures/table_Difuse.png </summary>
                public const string table_Difuse_png = "Content/Assets/textures/table_Difuse.png";
                
                /// <summary> Path to Content/Assets/textures/Tv_Difuse.png </summary>
                public const string Tv_Difuse_png = "Content/Assets/textures/Tv_Difuse.png";
            }
            
            public sealed class Video
            {
                
                /// <summary> Path to Content/Assets/Video/bear.mp4 </summary>
                public const string bear_mp4 = "Content/Assets/Video/bear.mp4";
                
                /// <summary> Path to Content/Assets/Video/bunny.mp4 </summary>
                public const string bunny_mp4 = "Content/Assets/Video/bunny.mp4";
            }
            
            public sealed class Materials
            {
                
                /// <summary> Path to Content/Assets/Materials/black_diffuse.wmat </summary>
                public const string black_diffuse = "Content/Assets/Materials/black_diffuse.wmat";
                
                /// <summary> Path to Content/Assets/Materials/chair_diffuse.wmat </summary>
                public const string chair_diffuse = "Content/Assets/Materials/chair_diffuse.wmat";
                
                /// <summary> Path to Content/Assets/Materials/parket_diffuse.wmat </summary>
                public const string parket_diffuse = "Content/Assets/Materials/parket_diffuse.wmat";
                
                /// <summary> Path to Content/Assets/Materials/table_diffuse.wmat </summary>
                public const string table_diffuse = "Content/Assets/Materials/table_diffuse.wmat";
            }
        }
        
        public sealed class Scenes
        {
            
            /// <summary> Path to Content/Scenes/MyScene.wscene </summary>
            public const string MyScene = "Content/Scenes/MyScene.wscene";
        }
    }
}
