//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// File generated on 27/03/2018 17:27:03
namespace KeyEventsAnimation
{
    using System;
    
    
    public sealed class WaveContent
    {
        
        /// <summary> Path to Content/KeyEventsAnimation.wgame </summary>
        public const string GameInfo = "Content/KeyEventsAnimation.wgame";
        
        public sealed class Assets
        {
            
            public sealed class Models
            {
                
                /// <summary> Path to Content/Assets/Models/isis.fbx </summary>
                public const string isis_fbx = "Content/Assets/Models/isis.fbx";
                
                public sealed class Materials
                {
                    
                    /// <summary> Path to Content/Assets/Models/Materials/Isis.wmat </summary>
                    public const string Isis = "Content/Assets/Models/Materials/Isis.wmat";
                }
            }
            
            public sealed class Sounds
            {
                
                /// <summary> Path to Content/Assets/Sounds/footstep1.wav </summary>
                public const string footstep1_wav = "Content/Assets/Sounds/footstep1.wav";
                
                /// <summary> Path to Content/Assets/Sounds/footstep2.wav </summary>
                public const string footstep2_wav = "Content/Assets/Sounds/footstep2.wav";
            }
            
            public sealed class Textures
            {
                
                /// <summary> Path to Content/Assets/Textures/isis_diffuse.png </summary>
                public const string isis_diffuse_png = "Content/Assets/Textures/isis_diffuse.png";
                
                /// <summary> Path to Content/Assets/Textures/isis_normal.png </summary>
                public const string isis_normal_png = "Content/Assets/Textures/isis_normal.png";
                
                /// <summary> Path to Content/Assets/Textures/isis_spec.png </summary>
                public const string isis_spec_png = "Content/Assets/Textures/isis_spec.png";
            }
            
            public sealed class Material
            {
                
                /// <summary> Path to Content/Assets/Material/IsisMaterial.wmat </summary>
                public const string IsisMaterial = "Content/Assets/Material/IsisMaterial.wmat";
            }
        }
        
        public sealed class RenderLayers
        {
            
            /// <summary>Id of Opaque</summary>
            public const int Opaque = 0;
            
            /// <summary>Id of Skybox</summary>
            public const int Skybox = 1;
            
            /// <summary>Id of Alpha</summary>
            public const int Alpha = 2;
            
            /// <summary>Id of Additive</summary>
            public const int Additive = 3;
            
            /// <summary>Id of GUI</summary>
            public const int GUI = 4;
            
            /// <summary>Id of Debug</summary>
            public const int Debug = 5;
        }
        
        public sealed class Scenes
        {
            
            /// <summary> Path to Content/Scenes/MyScene.wscene </summary>
            public const string MyScene = "Content/Scenes/MyScene.wscene";
        }
    }
}
