// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

// File generated on 1/28/2016 2:18:42 AM
namespace KeyEventsAnimation
{
    using System;
    
    
    public sealed class WaveContent
    {
        
        public sealed class Assets
        {
            
            public sealed class Models
            {
                
                /// <summary> Path to Content/Assets/Models/isis.fbx </summary>
                public const string isis_fbx = "Content/Assets/Models/isis.fbx";
            }
            
            public sealed class Sounds
            {
                
                /// <summary> Path to Content/Assets/Sounds/footstep1.wav </summary>
                public const string footstep1_wav = "Content/Assets/Sounds/footstep1.wav";
                
                /// <summary> Path to Content/Assets/Sounds/footstep2.wav </summary>
                public const string footstep2_wav = "Content/Assets/Sounds/footstep2.wav";
            }
            
            public sealed class Textures
            {
                
                /// <summary> Path to Content/Assets/Textures/isis_diffuse.png </summary>
                public const string isis_diffuse_png = "Content/Assets/Textures/isis_diffuse.png";
                
                /// <summary> Path to Content/Assets/Textures/isis_normal.png </summary>
                public const string isis_normal_png = "Content/Assets/Textures/isis_normal.png";
                
                /// <summary> Path to Content/Assets/Textures/isis_spec.png </summary>
                public const string isis_spec_png = "Content/Assets/Textures/isis_spec.png";
            }
            
            public sealed class Material
            {
                
                /// <summary> Path to Content/Assets/Material/IsisMaterial.wmat </summary>
                public const string IsisMaterial = "Content/Assets/Material/IsisMaterial.wmat";
            }
        }
        
        public sealed class Scenes
        {
            
            /// <summary> Path to Content/Scenes/MyScene.wscene </summary>
            public const string MyScene = "Content/Scenes/MyScene.wscene";
        }
    }
}
