//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// File generated on 8/3/2017 11:12:22 AM
namespace NormalMap
{
    using System;
    
    
    public sealed class WaveContent
    {
        
        /// <summary> Path to Content/NormalMap.wgame </summary>
        public const string GameInfo = "Content/NormalMap.wgame";
        
        public sealed class Assets
        {
            
            /// <summary> Path to Content/Assets/floor.png </summary>
            public const string floor_png = "Content/Assets/floor.png";
            
            /// <summary> Path to Content/Assets/floor_normal.png </summary>
            public const string floor_normal_png = "Content/Assets/floor_normal.png";
            
            /// <summary> Path to Content/Assets/floor_spec.png </summary>
            public const string floor_spec_png = "Content/Assets/floor_spec.png";
            
            /// <summary> Path to Content/Assets/lightmap.png </summary>
            public const string lightmap_png = "Content/Assets/lightmap.png";
            
            /// <summary> Path to Content/Assets/material.wmat </summary>
            public const string material = "Content/Assets/material.wmat";
        }
        
        public sealed class Scenes
        {
            
            /// <summary> Path to Content/Scenes/MyScene.wscene </summary>
            public const string MyScene = "Content/Scenes/MyScene.wscene";
        }
    }
}
