//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// File generated on 21/06/2018 10:33:58
namespace GettingStarted
{
    using System;
    
    
    public sealed class WaveContent
    {
        
        /// <summary> Path to Content/GettingStarted.wgame </summary>
        public const string GameInfo = "Content/GettingStarted.wgame";
        
        public sealed class Assets
        {
            
            /// <summary> Path to Content/Assets/crate.png </summary>
            public const string crate_png = "Content/Assets/crate.png";
        }
        
        public sealed class RenderLayers
        {
            
            /// <summary>Id of Opaque</summary>
            public const int Opaque = 0;
            
            /// <summary>Id of Skybox</summary>
            public const int Skybox = 1;
            
            /// <summary>Id of Alpha</summary>
            public const int Alpha = 2;
            
            /// <summary>Id of Additive</summary>
            public const int Additive = 3;
            
            /// <summary>Id of GUI</summary>
            public const int GUI = 4;
            
            /// <summary>Id of Debug</summary>
            public const int Debug = 5;
        }
        
        public sealed class Materials
        {
            
            /// <summary> Path to Content/Materials/MyMaterial.wmat </summary>
            public const string MyMaterial = "Content/Materials/MyMaterial.wmat";
        }
        
        public sealed class Scenes
        {
            
            /// <summary> Path to Content/Scenes/MyScene.wscene </summary>
            public const string MyScene = "Content/Scenes/MyScene.wscene";
        }
    }
}
