//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// File generated on 11/05/2017 10:16:20
namespace GettingStarted
{
    using System;
    
    
    public sealed class WaveContent
    {
        
        /// <summary> Path to  </summary>
        public const string GameInfo = null;
        
        public sealed class Assets
        {
            
            /// <summary> Path to Content/Assets/crate.png </summary>
            public const string crate_png = "Content/Assets/crate.png";
        }
        
        public sealed class Materials
        {
            
            /// <summary> Path to Content/Materials/MyMaterial.wmat </summary>
            public const string MyMaterial = "Content/Materials/MyMaterial.wmat";
        }
        
        public sealed class Scenes
        {
            
            /// <summary> Path to Content/Scenes/MyScene.wscene </summary>
            public const string MyScene = "Content/Scenes/MyScene.wscene";
        }
    }
}
