//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// File generated on 25/06/2018 12:50:38
namespace NoesisSample
{
    using System;
    
    
    public sealed class WaveContent
    {
        
        /// <summary> Path to Content/NoesisSample.wgame </summary>
        public const string GameInfo = "Content/NoesisSample.wgame";
        
        public sealed class Assets
        {
            
            public sealed class Models
            {
                
                /// <summary> Path to Content/Assets/Models/customPlane.fbx </summary>
                public const string customPlane_fbx = "Content/Assets/Models/customPlane.fbx";
                
                /// <summary> Path to Content/Assets/Models/marsElements.fbx </summary>
                public const string marsElements_fbx = "Content/Assets/Models/marsElements.fbx";
                
                /// <summary> Path to Content/Assets/Models/mgoProbe.fbx </summary>
                public const string mgoProbe_fbx = "Content/Assets/Models/mgoProbe.fbx";
                
                /// <summary> Path to Content/Assets/Models/stars.fbx </summary>
                public const string stars_fbx = "Content/Assets/Models/stars.fbx";
            }
            
            public sealed class Textures
            {
                
                /// <summary> Path to Content/Assets/Textures/atmosphere.png </summary>
                public const string atmosphere_png = "Content/Assets/Textures/atmosphere.png";
                
                /// <summary> Path to Content/Assets/Textures/floorShadow.png </summary>
                public const string floorShadow_png = "Content/Assets/Textures/floorShadow.png";
                
                /// <summary> Path to Content/Assets/Textures/foil_antenna_n.png </summary>
                public const string foil_antenna_n_png = "Content/Assets/Textures/foil_antenna_n.png";
                
                /// <summary> Path to Content/Assets/Textures/foil_n.png </summary>
                public const string foil_n_png = "Content/Assets/Textures/foil_n.png";
                
                /// <summary> Path to Content/Assets/Textures/mars.png </summary>
                public const string mars_png = "Content/Assets/Textures/mars.png";
                
                /// <summary> Path to Content/Assets/Textures/marsFloor.png </summary>
                public const string marsFloor_png = "Content/Assets/Textures/marsFloor.png";
                
                /// <summary> Path to Content/Assets/Textures/marsFuselage.png </summary>
                public const string marsFuselage_png = "Content/Assets/Textures/marsFuselage.png";
                
                /// <summary> Path to Content/Assets/Textures/roversLightmap.png </summary>
                public const string roversLightmap_png = "Content/Assets/Textures/roversLightmap.png";
                
                /// <summary> Path to Content/Assets/Textures/star.png </summary>
                public const string star_png = "Content/Assets/Textures/star.png";
            }
            
            public sealed class Xaml
            {
                
                /// <summary> Path to Content/Assets/Xaml/curiosityIcon.jpg </summary>
                public const string curiosityIcon_jpg = "Content/Assets/Xaml/curiosityIcon.jpg";
                
                /// <summary> Path to Content/Assets/Xaml/MainHUD.xaml </summary>
                public const string MainHUD_xaml = "Content/Assets/Xaml/MainHUD.xaml";
                
                /// <summary> Path to Content/Assets/Xaml/marsGlobe.png </summary>
                public const string marsGlobe_png = "Content/Assets/Xaml/marsGlobe.png";
                
                /// <summary> Path to Content/Assets/Xaml/mgoIcon.jpg </summary>
                public const string mgoIcon_jpg = "Content/Assets/Xaml/mgoIcon.jpg";
                
                /// <summary> Path to Content/Assets/Xaml/MissionPanel.xaml </summary>
                public const string MissionPanel_xaml = "Content/Assets/Xaml/MissionPanel.xaml";
                
                /// <summary> Path to Content/Assets/Xaml/nasa.png </summary>
                public const string nasa_png = "Content/Assets/Xaml/nasa.png";
                
                /// <summary> Path to Content/Assets/Xaml/PlanetHUD.xaml </summary>
                public const string PlanetHUD_xaml = "Content/Assets/Xaml/PlanetHUD.xaml";
                
                /// <summary> Path to Content/Assets/Xaml/spiritIcon.jpg </summary>
                public const string spiritIcon_jpg = "Content/Assets/Xaml/spiritIcon.jpg";
            }
            
            public sealed class Materials
            {
                
                /// <summary> Path to Content/Assets/Materials/Atmosphere.wmat </summary>
                public const string Atmosphere = "Content/Assets/Materials/Atmosphere.wmat";
                
                /// <summary> Path to Content/Assets/Materials/Dust.wmat </summary>
                public const string Dust = "Content/Assets/Materials/Dust.wmat";
                
                /// <summary> Path to Content/Assets/Materials/Floor.wmat </summary>
                public const string Floor = "Content/Assets/Materials/Floor.wmat";
                
                /// <summary> Path to Content/Assets/Materials/MarsFuselage.wmat </summary>
                public const string MarsFuselage = "Content/Assets/Materials/MarsFuselage.wmat";
                
                /// <summary> Path to Content/Assets/Materials/MarsMat.wmat </summary>
                public const string MarsMat = "Content/Assets/Materials/MarsMat.wmat";
                
                /// <summary> Path to Content/Assets/Materials/MGOGold.wmat </summary>
                public const string MGOGold = "Content/Assets/Materials/MGOGold.wmat";
                
                /// <summary> Path to Content/Assets/Materials/MGOGrey.wmat </summary>
                public const string MGOGrey = "Content/Assets/Materials/MGOGrey.wmat";
                
                /// <summary> Path to Content/Assets/Materials/MGOSilver.wmat </summary>
                public const string MGOSilver = "Content/Assets/Materials/MGOSilver.wmat";
                
                /// <summary> Path to Content/Assets/Materials/MGOTex.wmat </summary>
                public const string MGOTex = "Content/Assets/Materials/MGOTex.wmat";
                
                /// <summary> Path to Content/Assets/Materials/PanelMat.wmat </summary>
                public const string PanelMat = "Content/Assets/Materials/PanelMat.wmat";
                
                /// <summary> Path to Content/Assets/Materials/ShadowFloor.wmat </summary>
                public const string ShadowFloor = "Content/Assets/Materials/ShadowFloor.wmat";
                
                /// <summary> Path to Content/Assets/Materials/Starfield.wmat </summary>
                public const string Starfield = "Content/Assets/Materials/Starfield.wmat";
            }
        }
        
        public sealed class RenderLayers
        {
            
            /// <summary>Id of Opaque</summary>
            public const int Opaque = 0;
            
            /// <summary>Id of Skybox</summary>
            public const int Skybox = 1;
            
            /// <summary>Id of Stars</summary>
            public const int Stars = 1001;
            
            /// <summary>Id of Alpha</summary>
            public const int Alpha = 2;
            
            /// <summary>Id of Additive</summary>
            public const int Additive = 3;
            
            /// <summary>Id of GUI</summary>
            public const int GUI = 4;
            
            /// <summary>Id of Debug</summary>
            public const int Debug = 5;
        }
        
        public sealed class Scenes
        {
            
            /// <summary> Path to Content/Scenes/MyScene.wscene </summary>
            public const string MyScene = "Content/Scenes/MyScene.wscene";
        }
    }
}
