//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// File generated on 6/25/2018 3:25:27 PM
namespace Billboard
{
    using System;
    
    
    public sealed class WaveContent
    {
        
        /// <summary> Path to Content/Billboard.wgame </summary>
        public const string GameInfo = "Content/Billboard.wgame";
        
        public sealed class Assets
        {
            
            /// <summary> Path to Content/Assets/flare.png </summary>
            public const string flare_png = "Content/Assets/flare.png";
            
            /// <summary> Path to Content/Assets/ground.png </summary>
            public const string ground_png = "Content/Assets/ground.png";
            
            /// <summary> Path to Content/Assets/tree.png </summary>
            public const string tree_png = "Content/Assets/tree.png";
            
            /// <summary> Path to Content/Assets/groundMaterial.wmat </summary>
            public const string groundMaterial = "Content/Assets/groundMaterial.wmat";
        }
        
        public sealed class RenderLayers
        {
            
            /// <summary>Id of Opaque</summary>
            public const int Opaque = 0;
            
            /// <summary>Id of Skybox</summary>
            public const int Skybox = 1;
            
            /// <summary>Id of Alpha</summary>
            public const int Alpha = 2;
            
            /// <summary>Id of Additive</summary>
            public const int Additive = 3;
            
            /// <summary>Id of GUI</summary>
            public const int GUI = 4;
            
            /// <summary>Id of Debug</summary>
            public const int Debug = 5;
        }
        
        public sealed class Scenes
        {
            
            /// <summary> Path to Content/Scenes/MyScene.wscene </summary>
            public const string MyScene = "Content/Scenes/MyScene.wscene";
        }
    }
}
