//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// File generated on 16/12/2016 11:38:16
namespace Entity3DCollisionGroups
{
    using System;
    
    
    public sealed class WaveContent
    {
        
        public sealed class Assets
        {
            
            /// <summary> Path to Content/Assets/Ground.wmat </summary>
            public const string Ground = "Content/Assets/Ground.wmat";
            
            /// <summary> Path to Content/Assets/GroupA.wmat </summary>
            public const string GroupA = "Content/Assets/GroupA.wmat";
            
            /// <summary> Path to Content/Assets/GroupB.wmat </summary>
            public const string GroupB = "Content/Assets/GroupB.wmat";
        }
        
        public sealed class Scenes
        {
            
            /// <summary> Path to Content/Scenes/MyScene.wscene </summary>
            public const string MyScene = "Content/Scenes/MyScene.wscene";
        }
    }
}
