//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// File generated on 8/20/2015 3:00:08 PM
namespace EnvironmentMap
{
    using System;
    
    
    public sealed class WaveContent
    {
        
        public sealed class Assets
        {
            
            /// <summary> Path to Content/Assets/CupeMap.cubemap </summary>
            public const string CupeMap_cubemap = "Content/Assets/CupeMap.cubemap";
            
            /// <summary> Path to Content/Assets/tile1.png </summary>
            public const string tile1_png = "Content/Assets/tile1.png";
            
            /// <summary> Path to Content/Assets/SkyboxMaterial.wmat </summary>
            public const string SkyboxMaterial = "Content/Assets/SkyboxMaterial.wmat";
        }
        
        public sealed class Scenes
        {
            
            /// <summary> Path to Content/Scenes/MyScene.wscene </summary>
            public const string MyScene = "Content/Scenes/MyScene.wscene";
        }
    }
}
