//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// File generated on 9/5/2016 5:34:45 PM
namespace AnimatedModel
{
    using System;
    
    
    public sealed class WaveContent
    {
        
        public sealed class Assets
        {
            
            /// <summary> Path to Content/Assets/isis-difuse.png </summary>
            public const string isis_difuse_png = "Content/Assets/isis-difuse.png";
            
            /// <summary> Path to Content/Assets/isis.fbx </summary>
            public const string isis_fbx = "Content/Assets/isis.fbx";
            
            /// <summary> Path to Content/Assets/isisDifuseMaterial.wmat </summary>
            public const string isisDifuseMaterial = "Content/Assets/isisDifuseMaterial.wmat";
        }
        
        public sealed class Scenes
        {
            
            /// <summary> Path to Content/Scenes/MyScene.wscene </summary>
            public const string MyScene = "Content/Scenes/MyScene.wscene";
        }
    }
}
