//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// File generated on 03/08/2017 14:52:34
namespace AnimatedModel
{
    using System;
    
    
    public sealed class WaveContent
    {
        
        /// <summary> Path to Content/AnimatedModel.wgame </summary>
        public const string GameInfo = "Content/AnimatedModel.wgame";
        
        public sealed class Assets
        {
            
            /// <summary> Path to Content/Assets/isis.fbx </summary>
            public const string isis_fbx = "Content/Assets/isis.fbx";
            
            public sealed class Textures
            {
                
                /// <summary> Path to Content/Assets/Textures/isis-difuse.png </summary>
                public const string isis_difuse_png = "Content/Assets/Textures/isis-difuse.png";
                
                /// <summary> Path to Content/Assets/Textures/isis_normal.png </summary>
                public const string isis_normal_png = "Content/Assets/Textures/isis_normal.png";
                
                /// <summary> Path to Content/Assets/Textures/isis_spec.png </summary>
                public const string isis_spec_png = "Content/Assets/Textures/isis_spec.png";
            }
            
            public sealed class Materials
            {
                
                /// <summary> Path to Content/Assets/Materials/Isis.wmat </summary>
                public const string Isis = "Content/Assets/Materials/Isis.wmat";
            }
        }
        
        public sealed class Scenes
        {
            
            /// <summary> Path to Content/Scenes/MyScene.wscene </summary>
            public const string MyScene = "Content/Scenes/MyScene.wscene";
        }
    }
}
