//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// File generated on 23/11/2017 17:05:50
namespace AnimationSequence
{
    using System;
    
    
    public sealed class WaveContent
    {
        
        /// <summary> Path to Content/AnimationSequence.wgame </summary>
        public const string GameInfo = "Content/AnimationSequence.wgame";
        
        public sealed class Assets
        {
            
            /// <summary> Path to Content/Assets/arm.wav </summary>
            public const string arm_wav = "Content/Assets/arm.wav";
            
            /// <summary> Path to Content/Assets/coin.wav </summary>
            public const string coin_wav = "Content/Assets/coin.wav";
            
            /// <summary> Path to Content/Assets/robotic.fbx </summary>
            public const string robotic_fbx = "Content/Assets/robotic.fbx";
            
            /// <summary> Path to Content/Assets/redMaterial.wmat </summary>
            public const string redMaterial = "Content/Assets/redMaterial.wmat";
            
            /// <summary> Path to Content/Assets/whiteMaterial.wmat </summary>
            public const string whiteMaterial = "Content/Assets/whiteMaterial.wmat";
            
            public sealed class Materials
            {
                
                /// <summary> Path to Content/Assets/Materials/reflect.cubemap </summary>
                public const string reflect_cubemap = "Content/Assets/Materials/reflect.cubemap";
                
                /// <summary> Path to Content/Assets/Materials/metal.wmat </summary>
                public const string metal = "Content/Assets/Materials/metal.wmat";
                
                /// <summary> Path to Content/Assets/Materials/orange.wmat </summary>
                public const string orange = "Content/Assets/Materials/orange.wmat";
                
                /// <summary> Path to Content/Assets/Materials/rubber.wmat </summary>
                public const string rubber = "Content/Assets/Materials/rubber.wmat";
            }
        }
        
        public sealed class Scenes
        {
            
            /// <summary> Path to Content/Scenes/Scene1.wscene </summary>
            public const string Scene1 = "Content/Scenes/Scene1.wscene";
            
            /// <summary> Path to Content/Scenes/Scene2.wscene </summary>
            public const string Scene2 = "Content/Scenes/Scene2.wscene";
        }
    }
}
