//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// File generated on 3/22/2018 5:11:56 PM
namespace AnimationSequence
{
    using System;
    
    
    public sealed class WaveContent
    {
        
        /// <summary> Path to Content/AnimationSequence.wgame </summary>
        public const string GameInfo = "Content/AnimationSequence.wgame";
        
        public sealed class Assets
        {
            
            /// <summary> Path to Content/Assets/arm.wav </summary>
            public const string arm_wav = "Content/Assets/arm.wav";
            
            /// <summary> Path to Content/Assets/coin.wav </summary>
            public const string coin_wav = "Content/Assets/coin.wav";
            
            /// <summary> Path to Content/Assets/robotic.fbx </summary>
            public const string robotic_fbx = "Content/Assets/robotic.fbx";
            
            /// <summary> Path to Content/Assets/redMaterial.wmat </summary>
            public const string redMaterial = "Content/Assets/redMaterial.wmat";
            
            /// <summary> Path to Content/Assets/whiteMaterial.wmat </summary>
            public const string whiteMaterial = "Content/Assets/whiteMaterial.wmat";
            
            public sealed class Materials
            {
                
                /// <summary> Path to Content/Assets/Materials/reflect.cubemap </summary>
                public const string reflect_cubemap = "Content/Assets/Materials/reflect.cubemap";
                
                /// <summary> Path to Content/Assets/Materials/metal.wmat </summary>
                public const string metal = "Content/Assets/Materials/metal.wmat";
                
                /// <summary> Path to Content/Assets/Materials/orange.wmat </summary>
                public const string orange = "Content/Assets/Materials/orange.wmat";
                
                /// <summary> Path to Content/Assets/Materials/rubber.wmat </summary>
                public const string rubber = "Content/Assets/Materials/rubber.wmat";
            }
        }
        
        public sealed class RenderLayers
        {
            
            /// <summary>Id of Opaque</summary>
            public const int Opaque = 0;
            
            /// <summary>Id of Skybox</summary>
            public const int Skybox = 1;
            
            /// <summary>Id of Alpha</summary>
            public const int Alpha = 2;
            
            /// <summary>Id of Additive</summary>
            public const int Additive = 3;
            
            /// <summary>Id of GUI</summary>
            public const int GUI = 4;
            
            /// <summary>Id of Debug</summary>
            public const int Debug = 5;
        }
        
        public sealed class Scenes
        {
            
            /// <summary> Path to Content/Scenes/Scene1.wscene </summary>
            public const string Scene1 = "Content/Scenes/Scene1.wscene";
            
            /// <summary> Path to Content/Scenes/Scene2.wscene </summary>
            public const string Scene2 = "Content/Scenes/Scene2.wscene";
        }
    }
}
