//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// File generated on 14/06/2016 13:24:17
namespace AnimationSequence
{
    using System;
    
    
    public sealed class WaveContent
    {
        
        public sealed class Assets
        {
            
            /// <summary> Path to Content/Assets/base.FBX </summary>
            public const string base_FBX = "Content/Assets/base.FBX";
            
            /// <summary> Path to Content/Assets/reflect.cubemap </summary>
            public const string reflect_cubemap = "Content/Assets/reflect.cubemap";
            
            /// <summary> Path to Content/Assets/zone0.FBX </summary>
            public const string zone0_FBX = "Content/Assets/zone0.FBX";
            
            /// <summary> Path to Content/Assets/zone1.FBX </summary>
            public const string zone1_FBX = "Content/Assets/zone1.FBX";
            
            /// <summary> Path to Content/Assets/zone2.FBX </summary>
            public const string zone2_FBX = "Content/Assets/zone2.FBX";
            
            /// <summary> Path to Content/Assets/zone3.FBX </summary>
            public const string zone3_FBX = "Content/Assets/zone3.FBX";
            
            /// <summary> Path to Content/Assets/metalMaterial.wmat </summary>
            public const string metalMaterial = "Content/Assets/metalMaterial.wmat";
            
            /// <summary> Path to Content/Assets/redMaterial.wmat </summary>
            public const string redMaterial = "Content/Assets/redMaterial.wmat";
            
            /// <summary> Path to Content/Assets/rubberMaterial.wmat </summary>
            public const string rubberMaterial = "Content/Assets/rubberMaterial.wmat";
            
            /// <summary> Path to Content/Assets/whiteMaterial.wmat </summary>
            public const string whiteMaterial = "Content/Assets/whiteMaterial.wmat";
            
            /// <summary> Path to Content/Assets/yellowMaterial.wmat </summary>
            public const string yellowMaterial = "Content/Assets/yellowMaterial.wmat";
        }
        
        public sealed class Scenes
        {
            
            /// <summary> Path to Content/Scenes/Scene1.wscene </summary>
            public const string Scene1 = "Content/Scenes/Scene1.wscene";
            
            /// <summary> Path to Content/Scenes/Scene2.wscene </summary>
            public const string Scene2 = "Content/Scenes/Scene2.wscene";
        }
    }
}
