//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// File generated on 13/03/2018 17:29:54
namespace InternetTextureLoad
{
    using System;
    
    
    public sealed class WaveContent
    {
        
        /// <summary> Path to Content/InternetTextureLoad.wgame </summary>
        public const string GameInfo = "Content/InternetTextureLoad.wgame";
        
        public sealed class Assets
        {
            
            /// <summary> Path to Content/Assets/Loading.png </summary>
            public const string Loading_png = "Content/Assets/Loading.png";
        }
        
        public sealed class RenderLayers
        {
        }
        
        public sealed class Scenes
        {
            
            /// <summary> Path to Content/Scenes/MyScene.wscene </summary>
            public const string MyScene = "Content/Scenes/MyScene.wscene";
        }
    }
}
