//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// File generated on 19/01/2016 8:55:22
namespace ParticleSystem2D
{
    using System;
    
    
    public sealed class WaveContent
    {
        
        public sealed class Assets
        {
            
            /// <summary> Path to Content/Assets/backgroundMeteors.png </summary>
            public const string backgroundMeteors_png = "Content/Assets/backgroundMeteors.png";
            
            /// <summary> Path to Content/Assets/dinoParticle.png </summary>
            public const string dinoParticle_png = "Content/Assets/dinoParticle.png";
            
            /// <summary> Path to Content/Assets/meteorMountains.png </summary>
            public const string meteorMountains_png = "Content/Assets/meteorMountains.png";
            
            /// <summary> Path to Content/Assets/meteorSmoke.png </summary>
            public const string meteorSmoke_png = "Content/Assets/meteorSmoke.png";
            
            /// <summary> Path to Content/Assets/particleFire.png </summary>
            public const string particleFire_png = "Content/Assets/particleFire.png";
            
            /// <summary> Path to Content/Assets/dinoParticle_Texture.wmat </summary>
            public const string dinoParticle_Texture = "Content/Assets/dinoParticle_Texture.wmat";
            
            /// <summary> Path to Content/Assets/meteorSmoke_Texture.wmat </summary>
            public const string meteorSmoke_Texture = "Content/Assets/meteorSmoke_Texture.wmat";
            
            /// <summary> Path to Content/Assets/particleFire_Texture.wmat </summary>
            public const string particleFire_Texture = "Content/Assets/particleFire_Texture.wmat";
        }
        
        public sealed class Scenes
        {
            
            /// <summary> Path to Content/Scenes/MyScene.wscene </summary>
            public const string MyScene = "Content/Scenes/MyScene.wscene";
        }
    }
}
