//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// File generated on 9/5/2016 5:04:09 PM
namespace ParallaxCamera2D
{
    using System;
    
    
    public sealed class WaveContent
    {
        
        public sealed class Assets
        {
            
            public sealed class Textures
            {
                
                /// <summary> Path to Content/Assets/Textures/Crow.png </summary>
                public const string Crow_png = "Content/Assets/Textures/Crow.png";
                
                /// <summary> Path to Content/Assets/Textures/Darkness.png </summary>
                public const string Darkness_png = "Content/Assets/Textures/Darkness.png";
                
                /// <summary> Path to Content/Assets/Textures/DustParticle.png </summary>
                public const string DustParticle_png = "Content/Assets/Textures/DustParticle.png";
                
                /// <summary> Path to Content/Assets/Textures/Fence.png </summary>
                public const string Fence_png = "Content/Assets/Textures/Fence.png";
                
                /// <summary> Path to Content/Assets/Textures/Flare.png </summary>
                public const string Flare_png = "Content/Assets/Textures/Flare.png";
                
                /// <summary> Path to Content/Assets/Textures/ghost.png </summary>
                public const string ghost_png = "Content/Assets/Textures/ghost.png";
                
                /// <summary> Path to Content/Assets/Textures/GraveyardBackground.png </summary>
                public const string GraveyardBackground_png = "Content/Assets/Textures/GraveyardBackground.png";
                
                /// <summary> Path to Content/Assets/Textures/GraveyardForeground.png </summary>
                public const string GraveyardForeground_png = "Content/Assets/Textures/GraveyardForeground.png";
                
                /// <summary> Path to Content/Assets/Textures/HillMist.png </summary>
                public const string HillMist_png = "Content/Assets/Textures/HillMist.png";
                
                /// <summary> Path to Content/Assets/Textures/HountedHouse.png </summary>
                public const string HountedHouse_png = "Content/Assets/Textures/HountedHouse.png";
                
                /// <summary> Path to Content/Assets/Textures/HouseHill.png </summary>
                public const string HouseHill_png = "Content/Assets/Textures/HouseHill.png";
                
                /// <summary> Path to Content/Assets/Textures/HouseTower.png </summary>
                public const string HouseTower_png = "Content/Assets/Textures/HouseTower.png";
                
                /// <summary> Path to Content/Assets/Textures/LightBeam.png </summary>
                public const string LightBeam_png = "Content/Assets/Textures/LightBeam.png";
                
                /// <summary> Path to Content/Assets/Textures/Mist.png </summary>
                public const string Mist_png = "Content/Assets/Textures/Mist.png";
                
                /// <summary> Path to Content/Assets/Textures/scarecrow.png </summary>
                public const string scarecrow_png = "Content/Assets/Textures/scarecrow.png";
                
                /// <summary> Path to Content/Assets/Textures/Sun.png </summary>
                public const string Sun_png = "Content/Assets/Textures/Sun.png";
                
                public sealed class Dust
                {
                    
                    /// <summary> Path to Content/Assets/Textures/Dust/Dust.spritesheet </summary>
                    public const string Dust_spritesheet = "Content/Assets/Textures/Dust/Dust.spritesheet";
                    
                    /// <summary> Texture names from spritesheet Content/Assets/Textures/Dust/Dust.spritesheet </summary>
                    public struct Dust_spritesheet_TextureName
                    {
                        
                        public const string _01 = "01";
                        
                        public const string _02 = "02";
                        
                        public const string _03 = "03";
                        
                        public const string _04 = "04";
                        
                        public const string _05 = "05";
                        
                        public const string _06 = "06";
                        
                        public const string _07 = "07";
                        
                        public const string _08 = "08";
                        
                        public const string _09 = "09";
                        
                        public const string _10 = "10";
                        
                        public const string _11 = "11";
                        
                        public const string _12 = "12";
                        
                        public const string _13 = "13";
                    }
                }
                
                public sealed class Grass
                {
                    
                    /// <summary> Path to Content/Assets/Textures/Grass/grass_0.png </summary>
                    public const string grass_0_png = "Content/Assets/Textures/Grass/grass_0.png";
                    
                    /// <summary> Path to Content/Assets/Textures/Grass/grass_1.png </summary>
                    public const string grass_1_png = "Content/Assets/Textures/Grass/grass_1.png";
                    
                    /// <summary> Path to Content/Assets/Textures/Grass/grass_2.png </summary>
                    public const string grass_2_png = "Content/Assets/Textures/Grass/grass_2.png";
                }
                
                public sealed class Mushrooms
                {
                    
                    /// <summary> Path to Content/Assets/Textures/Mushrooms/mushroom_0.png </summary>
                    public const string mushroom_0_png = "Content/Assets/Textures/Mushrooms/mushroom_0.png";
                    
                    /// <summary> Path to Content/Assets/Textures/Mushrooms/mushroom_1.png </summary>
                    public const string mushroom_1_png = "Content/Assets/Textures/Mushrooms/mushroom_1.png";
                    
                    /// <summary> Path to Content/Assets/Textures/Mushrooms/mushroom_2.png </summary>
                    public const string mushroom_2_png = "Content/Assets/Textures/Mushrooms/mushroom_2.png";
                    
                    /// <summary> Path to Content/Assets/Textures/Mushrooms/mushroom_3.png </summary>
                    public const string mushroom_3_png = "Content/Assets/Textures/Mushrooms/mushroom_3.png";
                }
                
                public sealed class Trees
                {
                    
                    /// <summary> Path to Content/Assets/Textures/Trees/tree1st_0.png </summary>
                    public const string tree1st_0_png = "Content/Assets/Textures/Trees/tree1st_0.png";
                    
                    /// <summary> Path to Content/Assets/Textures/Trees/tree1st_1.png </summary>
                    public const string tree1st_1_png = "Content/Assets/Textures/Trees/tree1st_1.png";
                    
                    /// <summary> Path to Content/Assets/Textures/Trees/tree1st_2.png </summary>
                    public const string tree1st_2_png = "Content/Assets/Textures/Trees/tree1st_2.png";
                    
                    /// <summary> Path to Content/Assets/Textures/Trees/tree1st_3.png </summary>
                    public const string tree1st_3_png = "Content/Assets/Textures/Trees/tree1st_3.png";
                    
                    /// <summary> Path to Content/Assets/Textures/Trees/tree2nd_0.png </summary>
                    public const string tree2nd_0_png = "Content/Assets/Textures/Trees/tree2nd_0.png";
                    
                    /// <summary> Path to Content/Assets/Textures/Trees/tree2nd_1.png </summary>
                    public const string tree2nd_1_png = "Content/Assets/Textures/Trees/tree2nd_1.png";
                    
                    /// <summary> Path to Content/Assets/Textures/Trees/tree2nd_2.png </summary>
                    public const string tree2nd_2_png = "Content/Assets/Textures/Trees/tree2nd_2.png";
                    
                    /// <summary> Path to Content/Assets/Textures/Trees/tree2nd_3.png </summary>
                    public const string tree2nd_3_png = "Content/Assets/Textures/Trees/tree2nd_3.png";
                    
                    /// <summary> Path to Content/Assets/Textures/Trees/tree2nd_4.png </summary>
                    public const string tree2nd_4_png = "Content/Assets/Textures/Trees/tree2nd_4.png";
                    
                    /// <summary> Path to Content/Assets/Textures/Trees/tree3rd_0.png </summary>
                    public const string tree3rd_0_png = "Content/Assets/Textures/Trees/tree3rd_0.png";
                    
                    /// <summary> Path to Content/Assets/Textures/Trees/tree3rd_1.png </summary>
                    public const string tree3rd_1_png = "Content/Assets/Textures/Trees/tree3rd_1.png";
                    
                    /// <summary> Path to Content/Assets/Textures/Trees/tree3rd_2.png </summary>
                    public const string tree3rd_2_png = "Content/Assets/Textures/Trees/tree3rd_2.png";
                    
                    /// <summary> Path to Content/Assets/Textures/Trees/tree3rd_3.png </summary>
                    public const string tree3rd_3_png = "Content/Assets/Textures/Trees/tree3rd_3.png";
                }
            }
            
            public sealed class Yurei
            {
                
                /// <summary> Path to Content/Assets/Yurei/yurei.json </summary>
                public const string yurei_json = "Content/Assets/Yurei/yurei.json";
                
                /// <summary> Path to Content/Assets/Yurei/yurei.png </summary>
                public const string yurei_png = "Content/Assets/Yurei/yurei.png";
                
                /// <summary> Path to Content/Assets/Yurei/yurei.spine </summary>
                public const string yurei_spine = "Content/Assets/Yurei/yurei.spine";
            }
        }
        
        public sealed class Scenes
        {
            
            /// <summary> Path to Content/Scenes/MyScene.wscene </summary>
            public const string MyScene = "Content/Scenes/MyScene.wscene";
        }
    }
}
