//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// File generated on 8/3/2017 12:17:46 PM
namespace EnvironmentMap
{
    using System;
    
    
    public sealed class WaveContent
    {
        
        /// <summary> Path to Content/EnvironmentMap.wgame </summary>
        public const string GameInfo = "Content/EnvironmentMap.wgame";
        
        public sealed class Assets
        {
            
            /// <summary> Path to Content/Assets/CubeMap.cubemap </summary>
            public const string CubeMap_cubemap = "Content/Assets/CubeMap.cubemap";
            
            /// <summary> Path to Content/Assets/tile1.png </summary>
            public const string tile1_png = "Content/Assets/tile1.png";
            
            /// <summary> Path to Content/Assets/SkyboxMaterial.wmat </summary>
            public const string SkyboxMaterial = "Content/Assets/SkyboxMaterial.wmat";
        }
        
        public sealed class Scenes
        {
            
            /// <summary> Path to Content/Scenes/MyScene.wscene </summary>
            public const string MyScene = "Content/Scenes/MyScene.wscene";
        }
    }
}
