//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// File generated on 6/26/2018 1:58:54 PM
namespace VehiclePhysics2D
{
    using System;
    
    
    public sealed class WaveContent
    {
        
        /// <summary> Path to Content/VehiclePhysics2D.wgame </summary>
        public const string GameInfo = "Content/VehiclePhysics2D.wgame";
        
        public sealed class Assets
        {
            
            public sealed class Fonts
            {
                
                /// <summary> Path to Content/Assets/Fonts/Arial_16.ttf </summary>
                public const string Arial_16_ttf = "Content/Assets/Fonts/Arial_16.ttf";
            }
            
            public sealed class Textures
            {
                
                /// <summary> Path to Content/Assets/Textures/car.png </summary>
                public const string car_png = "Content/Assets/Textures/car.png";
                
                /// <summary> Path to Content/Assets/Textures/debrisStone_1.png </summary>
                public const string debrisStone_1_png = "Content/Assets/Textures/debrisStone_1.png";
                
                /// <summary> Path to Content/Assets/Textures/debrisStone_2.png </summary>
                public const string debrisStone_2_png = "Content/Assets/Textures/debrisStone_2.png";
                
                /// <summary> Path to Content/Assets/Textures/debrisStone_3.png </summary>
                public const string debrisStone_3_png = "Content/Assets/Textures/debrisStone_3.png";
                
                /// <summary> Path to Content/Assets/Textures/elementMetal014.png </summary>
                public const string elementMetal014_png = "Content/Assets/Textures/elementMetal014.png";
                
                /// <summary> Path to Content/Assets/Textures/elementWood010.png </summary>
                public const string elementWood010_png = "Content/Assets/Textures/elementWood010.png";
                
                /// <summary> Path to Content/Assets/Textures/elementWood054.png </summary>
                public const string elementWood054_png = "Content/Assets/Textures/elementWood054.png";
                
                /// <summary> Path to Content/Assets/Textures/road.png </summary>
                public const string road_png = "Content/Assets/Textures/road.png";
                
                /// <summary> Path to Content/Assets/Textures/SpriteSheet.spritesheet </summary>
                public const string SpriteSheet_spritesheet = "Content/Assets/Textures/SpriteSheet.spritesheet";
                
                /// <summary> Path to Content/Assets/Textures/trailer.png </summary>
                public const string trailer_png = "Content/Assets/Textures/trailer.png";
                
                /// <summary> Path to Content/Assets/Textures/wheel.png </summary>
                public const string wheel_png = "Content/Assets/Textures/wheel.png";
                
                /// <summary> Texture names from spritesheet Content/Assets/Textures/SpriteSheet.spritesheet </summary>
                public struct SpriteSheet_spritesheet_TextureName
                {
                    
                    public const string box = "box";
                    
                    public const string cloud1 = "cloud1";
                    
                    public const string cloud2 = "cloud2";
                    
                    public const string clouds1 = "clouds1";
                    
                    public const string fence = "fence";
                    
                    public const string fence_piece = "fence_piece";
                    
                    public const string grass5 = "grass5";
                    
                    public const string grass6 = "grass6";
                    
                    public const string hills1 = "hills1";
                    
                    public const string house_beige_front = "house_beige_front";
                    
                    public const string house_beige_side = "house_beige_side";
                    
                    public const string house_grey_front = "house_grey_front";
                    
                    public const string house_grey_side = "house_grey_side";
                    
                    public const string pointy_mountains = "pointy_mountains";
                    
                    public const string sun = "sun";
                    
                    public const string tree02 = "tree02";
                    
                    public const string tree08 = "tree08";
                    
                    public const string tree10 = "tree10";
                    
                    public const string tree13 = "tree13";
                    
                    public const string tree20 = "tree20";
                    
                    public const string tree23 = "tree23";
                    
                    public const string tree29 = "tree29";
                    
                    public const string tree31 = "tree31";
                    
                    public const string tree34 = "tree34";
                }
            }
        }
        
        public sealed class RenderLayers
        {
            
            /// <summary>Id of Opaque</summary>
            public const int Opaque = 0;
            
            /// <summary>Id of Skybox</summary>
            public const int Skybox = 1;
            
            /// <summary>Id of Alpha</summary>
            public const int Alpha = 2;
            
            /// <summary>Id of Additive</summary>
            public const int Additive = 3;
            
            /// <summary>Id of GUI</summary>
            public const int GUI = 4;
            
            /// <summary>Id of Debug</summary>
            public const int Debug = 5;
        }
        
        public sealed class Scenes
        {
            
            /// <summary> Path to Content/Scenes/MyScene.wscene </summary>
            public const string MyScene = "Content/Scenes/MyScene.wscene";
        }
    }
}
