//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// File generated on 8/8/2017 1:36:44 PM
namespace HingleJoint
{
    using System;
    
    
    public sealed class WaveContent
    {
        
        /// <summary> Path to Content/HingleJoint.wgame </summary>
        public const string GameInfo = "Content/HingleJoint.wgame";
        
        public sealed class Assets
        {
            
            /// <summary> Path to Content/Assets/checkered.png </summary>
            public const string checkered_png = "Content/Assets/checkered.png";
            
            /// <summary> Path to Content/Assets/basicMaterial.wmat </summary>
            public const string basicMaterial = "Content/Assets/basicMaterial.wmat";
            
            /// <summary> Path to Content/Assets/groundMaterial.wmat </summary>
            public const string groundMaterial = "Content/Assets/groundMaterial.wmat";
        }
        
        public sealed class Scenes
        {
            
            /// <summary> Path to Content/Scenes/MyScene.wscene </summary>
            public const string MyScene = "Content/Scenes/MyScene.wscene";
        }
    }
}
