//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// File generated on 8/8/2017 12:35:55 PM
namespace Entity3DCollision
{
    using System;
    
    
    public sealed class WaveContent
    {
        
        /// <summary> Path to Content/Entity3DCollision.wgame </summary>
        public const string GameInfo = "Content/Entity3DCollision.wgame";
        
        public sealed class Assets
        {
            
            /// <summary> Path to Content/Assets/checkered.png </summary>
            public const string checkered_png = "Content/Assets/checkered.png";
            
            /// <summary> Path to Content/Assets/basicMaterial.wmat </summary>
            public const string basicMaterial = "Content/Assets/basicMaterial.wmat";
        }
        
        public sealed class Scenes
        {
            
            /// <summary> Path to Content/Scenes/MyScene.wscene </summary>
            public const string MyScene = "Content/Scenes/MyScene.wscene";
        }
    }
}
