//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// File generated on 22-May-18 17:08:07
namespace IsisTemple
{
    using System;
    
    
    public sealed class WaveContent
    {
        
        /// <summary> Path to Content/IsisTemple.wgame </summary>
        public const string GameInfo = "Content/IsisTemple.wgame";
        
        public sealed class Assets
        {
            
            public sealed class Models
            {
                
                /// <summary> Path to Content/Assets/Models/column1.fbx </summary>
                public const string column1_fbx = "Content/Assets/Models/column1.fbx";
                
                /// <summary> Path to Content/Assets/Models/column2.fbx </summary>
                public const string column2_fbx = "Content/Assets/Models/column2.fbx";
                
                /// <summary> Path to Content/Assets/Models/floor.fbx </summary>
                public const string floor_fbx = "Content/Assets/Models/floor.fbx";
                
                /// <summary> Path to Content/Assets/Models/isis.fbx </summary>
                public const string isis_fbx = "Content/Assets/Models/isis.fbx";
                
                public sealed class Materials
                {
                    
                    /// <summary> Path to Content/Assets/Models/Materials/DefaultMaterial.wmat </summary>
                    public const string DefaultMaterial = "Content/Assets/Models/Materials/DefaultMaterial.wmat";
                    
                    /// <summary> Path to Content/Assets/Models/Materials/Isis.wmat </summary>
                    public const string Isis = "Content/Assets/Models/Materials/Isis.wmat";
                    
                    /// <summary> Path to Content/Assets/Models/Materials/Material #503.wmat </summary>
                    public const string Material_503 = "Content/Assets/Models/Materials/Material #503.wmat";
                    
                    /// <summary> Path to Content/Assets/Models/Materials/Material #505.wmat </summary>
                    public const string Material_505 = "Content/Assets/Models/Materials/Material #505.wmat";
                }
            }
            
            public sealed class Textures
            {
                
                /// <summary> Path to Content/Assets/Textures/column1_diffuse.png </summary>
                public const string column1_diffuse_png = "Content/Assets/Textures/column1_diffuse.png";
                
                /// <summary> Path to Content/Assets/Textures/column1_normal.png </summary>
                public const string column1_normal_png = "Content/Assets/Textures/column1_normal.png";
                
                /// <summary> Path to Content/Assets/Textures/column1_spec.png </summary>
                public const string column1_spec_png = "Content/Assets/Textures/column1_spec.png";
                
                /// <summary> Path to Content/Assets/Textures/column2_diffuse.png </summary>
                public const string column2_diffuse_png = "Content/Assets/Textures/column2_diffuse.png";
                
                /// <summary> Path to Content/Assets/Textures/column2_normal.png </summary>
                public const string column2_normal_png = "Content/Assets/Textures/column2_normal.png";
                
                /// <summary> Path to Content/Assets/Textures/column2_spec.png </summary>
                public const string column2_spec_png = "Content/Assets/Textures/column2_spec.png";
                
                /// <summary> Path to Content/Assets/Textures/floor1_diffuse.png </summary>
                public const string floor1_diffuse_png = "Content/Assets/Textures/floor1_diffuse.png";
                
                /// <summary> Path to Content/Assets/Textures/floor1_normal.png </summary>
                public const string floor1_normal_png = "Content/Assets/Textures/floor1_normal.png";
                
                /// <summary> Path to Content/Assets/Textures/floor1_spec.png </summary>
                public const string floor1_spec_png = "Content/Assets/Textures/floor1_spec.png";
                
                /// <summary> Path to Content/Assets/Textures/isis_diffuse.png </summary>
                public const string isis_diffuse_png = "Content/Assets/Textures/isis_diffuse.png";
                
                /// <summary> Path to Content/Assets/Textures/isis_normal.png </summary>
                public const string isis_normal_png = "Content/Assets/Textures/isis_normal.png";
                
                /// <summary> Path to Content/Assets/Textures/isis_spec.png </summary>
                public const string isis_spec_png = "Content/Assets/Textures/isis_spec.png";
                
                /// <summary> Path to Content/Assets/Textures/JoystickButton.png </summary>
                public const string JoystickButton_png = "Content/Assets/Textures/JoystickButton.png";
                
                /// <summary> Path to Content/Assets/Textures/ShiftButton.png </summary>
                public const string ShiftButton_png = "Content/Assets/Textures/ShiftButton.png";
            }
            
            public sealed class Materials
            {
                
                /// <summary> Path to Content/Assets/Materials/Column1Material.wmat </summary>
                public const string Column1Material = "Content/Assets/Materials/Column1Material.wmat";
                
                /// <summary> Path to Content/Assets/Materials/Column2Material.wmat </summary>
                public const string Column2Material = "Content/Assets/Materials/Column2Material.wmat";
                
                /// <summary> Path to Content/Assets/Materials/FloorMaterial.wmat </summary>
                public const string FloorMaterial = "Content/Assets/Materials/FloorMaterial.wmat";
                
                /// <summary> Path to Content/Assets/Materials/IsisMaterial.wmat </summary>
                public const string IsisMaterial = "Content/Assets/Materials/IsisMaterial.wmat";
            }
        }
        
        public sealed class RenderLayers
        {
            
            /// <summary>Id of Opaque</summary>
            public const int Opaque = 0;
            
            /// <summary>Id of Skybox</summary>
            public const int Skybox = 1;
            
            /// <summary>Id of Alpha</summary>
            public const int Alpha = 2;
            
            /// <summary>Id of Additive</summary>
            public const int Additive = 3;
            
            /// <summary>Id of GUI</summary>
            public const int GUI = 4;
            
            /// <summary>Id of Debug</summary>
            public const int Debug = 5;
        }
        
        public sealed class Scenes
        {
            
            /// <summary> Path to Content/Scenes/MyScene.wscene </summary>
            public const string MyScene = "Content/Scenes/MyScene.wscene";
        }
    }
}
