//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// File generated on 07/02/2017 15:56:31
namespace PlatformGameDemo
{
    using System;
    
    
    public sealed class WaveContent
    {
        
        public sealed class Assets
        {
            
            /// <summary> Path to Content/Assets/Credits.png </summary>
            public const string Credits_png = "Content/Assets/Credits.png";
            
            /// <summary> Path to Content/Assets/Floor.png </summary>
            public const string Floor_png = "Content/Assets/Floor.png";
            
            /// <summary> Path to Content/Assets/Sky.png </summary>
            public const string Sky_png = "Content/Assets/Sky.png";
            
            /// <summary> Path to Content/Assets/Tim.spritesheet </summary>
            public const string Tim_spritesheet = "Content/Assets/Tim.spritesheet";
            
            /// <summary> Texture names from spritesheet Content/Assets/Tim.spritesheet </summary>
            public struct Tim_spritesheet_TextureName
            {
                
                public const string tim_01 = "tim_01";
                
                public const string tim_02 = "tim_02";
                
                public const string tim_03 = "tim_03";
                
                public const string tim_04 = "tim_04";
                
                public const string tim_05 = "tim_05";
                
                public const string tim_06 = "tim_06";
                
                public const string tim_07 = "tim_07";
                
                public const string tim_08 = "tim_08";
                
                public const string tim_09 = "tim_09";
                
                public const string tim_10 = "tim_10";
                
                public const string tim_11 = "tim_11";
                
                public const string tim_12 = "tim_12";
                
                public const string tim_13 = "tim_13";
                
                public const string tim_14 = "tim_14";
                
                public const string tim_15 = "tim_15";
                
                public const string tim_16 = "tim_16";
                
                public const string tim_17 = "tim_17";
                
                public const string tim_18 = "tim_18";
                
                public const string tim_19 = "tim_19";
                
                public const string tim_20 = "tim_20";
                
                public const string tim_21 = "tim_21";
                
                public const string tim_22 = "tim_22";
                
                public const string tim_23 = "tim_23";
                
                public const string tim_24 = "tim_24";
                
                public const string tim_25 = "tim_25";
                
                public const string tim_26 = "tim_26";
                
                public const string tim_27 = "tim_27";
                
                public const string tim_28 = "tim_28";
                
                public const string tim_29 = "tim_29";
                
                public const string tim_30 = "tim_30";
                
                public const string tim_31 = "tim_31";
                
                public const string tim_32 = "tim_32";
                
                public const string tim_33 = "tim_33";
                
                public const string tim_34 = "tim_34";
                
                public const string tim_35 = "tim_35";
                
                public const string tim_36 = "tim_36";
                
                public const string tim_37 = "tim_37";
                
                public const string tim_38 = "tim_38";
                
                public const string tim_39 = "tim_39";
                
                public const string tim_40 = "tim_40";
                
                public const string tim_41 = "tim_41";
                
                public const string tim_42 = "tim_42";
                
                public const string tim_43 = "tim_43";
                
                public const string tim_44 = "tim_44";
                
                public const string tim_45 = "tim_45";
                
                public const string tim_46 = "tim_46";
                
                public const string tim_47 = "tim_47";
                
                public const string tim_48 = "tim_48";
                
                public const string tim_49 = "tim_49";
            }
        }
        
        public sealed class Scenes
        {
            
            /// <summary> Path to Content/Scenes/MyScene.wscene </summary>
            public const string MyScene = "Content/Scenes/MyScene.wscene";
        }
    }
}
