#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("SocialService.Resource", IsApplication=true)]

namespace SocialService
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010000
			public const int adSize = 2130771968;
			
			// aapt resource value: 0x7f010001
			public const int adSizes = 2130771969;
			
			// aapt resource value: 0x7f010002
			public const int adUnitId = 2130771970;
			
			// aapt resource value: 0x7f010004
			public const int cameraBearing = 2130771972;
			
			// aapt resource value: 0x7f010005
			public const int cameraTargetLat = 2130771973;
			
			// aapt resource value: 0x7f010006
			public const int cameraTargetLng = 2130771974;
			
			// aapt resource value: 0x7f010007
			public const int cameraTilt = 2130771975;
			
			// aapt resource value: 0x7f010008
			public const int cameraZoom = 2130771976;
			
			// aapt resource value: 0x7f010003
			public const int mapType = 2130771971;
			
			// aapt resource value: 0x7f010009
			public const int uiCompass = 2130771977;
			
			// aapt resource value: 0x7f01000a
			public const int uiRotateGestures = 2130771978;
			
			// aapt resource value: 0x7f01000b
			public const int uiScrollGestures = 2130771979;
			
			// aapt resource value: 0x7f01000c
			public const int uiTiltGestures = 2130771980;
			
			// aapt resource value: 0x7f01000d
			public const int uiZoomControls = 2130771981;
			
			// aapt resource value: 0x7f01000e
			public const int uiZoomGestures = 2130771982;
			
			// aapt resource value: 0x7f01000f
			public const int useViewLifecycle = 2130771983;
			
			// aapt resource value: 0x7f010010
			public const int zOrderOnTop = 2130771984;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040009
			public const int common_action_bar_splitter = 2130968585;
			
			// aapt resource value: 0x7f040000
			public const int common_signin_btn_dark_text_default = 2130968576;
			
			// aapt resource value: 0x7f040002
			public const int common_signin_btn_dark_text_disabled = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int common_signin_btn_dark_text_focused = 2130968579;
			
			// aapt resource value: 0x7f040001
			public const int common_signin_btn_dark_text_pressed = 2130968577;
			
			// aapt resource value: 0x7f040008
			public const int common_signin_btn_default_background = 2130968584;
			
			// aapt resource value: 0x7f040004
			public const int common_signin_btn_light_text_default = 2130968580;
			
			// aapt resource value: 0x7f040006
			public const int common_signin_btn_light_text_disabled = 2130968582;
			
			// aapt resource value: 0x7f040007
			public const int common_signin_btn_light_text_focused = 2130968583;
			
			// aapt resource value: 0x7f040005
			public const int common_signin_btn_light_text_pressed = 2130968581;
			
			// aapt resource value: 0x7f04000b
			public const int common_signin_btn_text_dark = 2130968587;
			
			// aapt resource value: 0x7f04000c
			public const int common_signin_btn_text_light = 2130968588;
			
			// aapt resource value: 0x7f04000a
			public const int custom_theme_color = 2130968586;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int common_signin_btn_icon_dark = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int common_signin_btn_icon_disabled_dark = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int common_signin_btn_icon_disabled_focus_dark = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int common_signin_btn_icon_disabled_focus_light = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int common_signin_btn_icon_disabled_light = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int common_signin_btn_icon_focus_dark = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int common_signin_btn_icon_focus_light = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int common_signin_btn_icon_light = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int common_signin_btn_icon_normal_dark = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int common_signin_btn_icon_normal_light = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int common_signin_btn_icon_pressed_dark = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int common_signin_btn_icon_pressed_light = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int common_signin_btn_text_dark = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int common_signin_btn_text_disabled_dark = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int common_signin_btn_text_disabled_focus_dark = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int common_signin_btn_text_disabled_focus_light = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int common_signin_btn_text_disabled_light = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int common_signin_btn_text_focus_dark = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int common_signin_btn_text_focus_light = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int common_signin_btn_text_light = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int common_signin_btn_text_normal_dark = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int common_signin_btn_text_normal_light = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int common_signin_btn_text_pressed_dark = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int common_signin_btn_text_pressed_light = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int ic_plusone_medium_off_client = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int ic_plusone_small_off_client = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int ic_plusone_standard_off_client = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int ic_plusone_tall_off_client = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int Icon = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int logo = 2130837533;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f080005
			public const int glview = 2131230725;
			
			// aapt resource value: 0x7f080000
			public const int hybrid = 2131230720;
			
			// aapt resource value: 0x7f080007
			public const int imgMain = 2131230727;
			
			// aapt resource value: 0x7f080006
			public const int lnMain = 2131230726;
			
			// aapt resource value: 0x7f080001
			public const int none = 2131230721;
			
			// aapt resource value: 0x7f080002
			public const int normal = 2131230722;
			
			// aapt resource value: 0x7f080003
			public const int satellite = 2131230723;
			
			// aapt resource value: 0x7f080004
			public const int terrain = 2131230724;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7f060000
			public const int google_play_services_version = 2131099648;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Splash = 2130903041;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050015
			public const int auth_client_needs_enabling_title = 2131034133;
			
			// aapt resource value: 0x7f050016
			public const int auth_client_needs_installation_title = 2131034134;
			
			// aapt resource value: 0x7f050017
			public const int auth_client_needs_update_title = 2131034135;
			
			// aapt resource value: 0x7f050018
			public const int auth_client_play_services_err_notification_msg = 2131034136;
			
			// aapt resource value: 0x7f050019
			public const int auth_client_requested_by_msg = 2131034137;
			
			// aapt resource value: 0x7f050014
			public const int auth_client_using_bad_version_title = 2131034132;
			
			// aapt resource value: 0x7f050006
			public const int common_google_play_services_enable_button = 2131034118;
			
			// aapt resource value: 0x7f050005
			public const int common_google_play_services_enable_text = 2131034117;
			
			// aapt resource value: 0x7f050004
			public const int common_google_play_services_enable_title = 2131034116;
			
			// aapt resource value: 0x7f050003
			public const int common_google_play_services_install_button = 2131034115;
			
			// aapt resource value: 0x7f050001
			public const int common_google_play_services_install_text_phone = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int common_google_play_services_install_text_tablet = 2131034114;
			
			// aapt resource value: 0x7f050000
			public const int common_google_play_services_install_title = 2131034112;
			
			// aapt resource value: 0x7f05000c
			public const int common_google_play_services_invalid_account_text = 2131034124;
			
			// aapt resource value: 0x7f05000b
			public const int common_google_play_services_invalid_account_title = 2131034123;
			
			// aapt resource value: 0x7f05000a
			public const int common_google_play_services_network_error_text = 2131034122;
			
			// aapt resource value: 0x7f050009
			public const int common_google_play_services_network_error_title = 2131034121;
			
			// aapt resource value: 0x7f05000d
			public const int common_google_play_services_unknown_issue = 2131034125;
			
			// aapt resource value: 0x7f050010
			public const int common_google_play_services_unsupported_date_text = 2131034128;
			
			// aapt resource value: 0x7f05000f
			public const int common_google_play_services_unsupported_text = 2131034127;
			
			// aapt resource value: 0x7f05000e
			public const int common_google_play_services_unsupported_title = 2131034126;
			
			// aapt resource value: 0x7f050011
			public const int common_google_play_services_update_button = 2131034129;
			
			// aapt resource value: 0x7f050008
			public const int common_google_play_services_update_text = 2131034120;
			
			// aapt resource value: 0x7f050007
			public const int common_google_play_services_update_title = 2131034119;
			
			// aapt resource value: 0x7f050012
			public const int common_signin_button_text = 2131034130;
			
			// aapt resource value: 0x7f050013
			public const int common_signin_button_text_long = 2131034131;
			
			// aapt resource value: 0x7f05001a
			public const int location_client_powered_by_google = 2131034138;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070000
			public const int Theme_Splash = 2131165184;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] AdsAttrs = new int[] {
					2130771968,
					2130771969,
					2130771970};
			
			// aapt resource value: 0
			public const int AdsAttrs_adSize = 0;
			
			// aapt resource value: 1
			public const int AdsAttrs_adSizes = 1;
			
			// aapt resource value: 2
			public const int AdsAttrs_adUnitId = 2;
			
			public static int[] MapAttrs = new int[] {
					2130771971,
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976,
					2130771977,
					2130771978,
					2130771979,
					2130771980,
					2130771981,
					2130771982,
					2130771983,
					2130771984};
			
			// aapt resource value: 1
			public const int MapAttrs_cameraBearing = 1;
			
			// aapt resource value: 2
			public const int MapAttrs_cameraTargetLat = 2;
			
			// aapt resource value: 3
			public const int MapAttrs_cameraTargetLng = 3;
			
			// aapt resource value: 4
			public const int MapAttrs_cameraTilt = 4;
			
			// aapt resource value: 5
			public const int MapAttrs_cameraZoom = 5;
			
			// aapt resource value: 0
			public const int MapAttrs_mapType = 0;
			
			// aapt resource value: 6
			public const int MapAttrs_uiCompass = 6;
			
			// aapt resource value: 7
			public const int MapAttrs_uiRotateGestures = 7;
			
			// aapt resource value: 8
			public const int MapAttrs_uiScrollGestures = 8;
			
			// aapt resource value: 9
			public const int MapAttrs_uiTiltGestures = 9;
			
			// aapt resource value: 10
			public const int MapAttrs_uiZoomControls = 10;
			
			// aapt resource value: 11
			public const int MapAttrs_uiZoomGestures = 11;
			
			// aapt resource value: 12
			public const int MapAttrs_useViewLifecycle = 12;
			
			// aapt resource value: 13
			public const int MapAttrs_zOrderOnTop = 13;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
