//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// File generated on 16/12/2016 11:37:23
namespace Tumbler
{
    using System;
    
    
    public sealed class WaveContent
    {
        
        public sealed class Assets
        {
            
            /// <summary> Path to Content/Assets/blue_desert.png </summary>
            public const string blue_desert_png = "Content/Assets/blue_desert.png";
            
            /// <summary> Path to Content/Assets/circle.png </summary>
            public const string circle_png = "Content/Assets/circle.png";
            
            /// <summary> Path to Content/Assets/square.png </summary>
            public const string square_png = "Content/Assets/square.png";
            
            /// <summary> Path to Content/Assets/stoneBar.png </summary>
            public const string stoneBar_png = "Content/Assets/stoneBar.png";
            
            /// <summary> Path to Content/Assets/suited.png </summary>
            public const string suited_png = "Content/Assets/suited.png";
        }
        
        public sealed class Prefabs
        {
            
            /// <summary> Path to Content/Prefabs/circle.wpref </summary>
            public const string circle = "Content/Prefabs/circle.wpref";
            
            /// <summary> Path to Content/Prefabs/edge.wpref </summary>
            public const string edge = "Content/Prefabs/edge.wpref";
            
            /// <summary> Path to Content/Prefabs/square.wpref </summary>
            public const string square = "Content/Prefabs/square.wpref";
            
            /// <summary> Path to Content/Prefabs/suited.wpref </summary>
            public const string suited = "Content/Prefabs/suited.wpref";
        }
        
        public sealed class Scenes
        {
            
            /// <summary> Path to Content/Scenes/MyScene.wscene </summary>
            public const string MyScene = "Content/Scenes/MyScene.wscene";
        }
    }
}
