//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// File generated on 10/04/2018 17:38:25
namespace Tumbler
{
    using System;
    
    
    public sealed class WaveContent
    {
        
        /// <summary> Path to Content/Tumbler.wgame </summary>
        public const string GameInfo = "Content/Tumbler.wgame";
        
        public sealed class Assets
        {
            
            /// <summary> Path to Content/Assets/blue_desert.png </summary>
            public const string blue_desert_png = "Content/Assets/blue_desert.png";
            
            /// <summary> Path to Content/Assets/circle.png </summary>
            public const string circle_png = "Content/Assets/circle.png";
            
            /// <summary> Path to Content/Assets/square.png </summary>
            public const string square_png = "Content/Assets/square.png";
            
            /// <summary> Path to Content/Assets/stoneBar.png </summary>
            public const string stoneBar_png = "Content/Assets/stoneBar.png";
            
            /// <summary> Path to Content/Assets/suited.png </summary>
            public const string suited_png = "Content/Assets/suited.png";
        }
        
        public sealed class RenderLayers
        {
            
            /// <summary>Id of Opaque</summary>
            public const int Opaque = 0;
            
            /// <summary>Id of Skybox</summary>
            public const int Skybox = 1;
            
            /// <summary>Id of Alpha</summary>
            public const int Alpha = 2;
            
            /// <summary>Id of Additive</summary>
            public const int Additive = 3;
            
            /// <summary>Id of GUI</summary>
            public const int GUI = 4;
            
            /// <summary>Id of Debug</summary>
            public const int Debug = 5;
        }
        
        public sealed class Prefabs
        {
            
            /// <summary> Path to Content/Prefabs/circle.wpref </summary>
            public const string circle = "Content/Prefabs/circle.wpref";
            
            /// <summary> Path to Content/Prefabs/edge.wpref </summary>
            public const string edge = "Content/Prefabs/edge.wpref";
            
            /// <summary> Path to Content/Prefabs/square.wpref </summary>
            public const string square = "Content/Prefabs/square.wpref";
            
            /// <summary> Path to Content/Prefabs/suited.wpref </summary>
            public const string suited = "Content/Prefabs/suited.wpref";
        }
        
        public sealed class Scenes
        {
            
            /// <summary> Path to Content/Scenes/MyScene.wscene </summary>
            public const string MyScene = "Content/Scenes/MyScene.wscene";
        }
    }
}
