//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// File generated on 09/08/2017 14:54:35
namespace TiledMap
{
    using System;
    
    
    public sealed class WaveContent
    {
        
        /// <summary> Path to Content/TiledMap.wgame </summary>
        public const string GameInfo = "Content/TiledMap.wgame";
        
        public sealed class Assets
        {
            
            /// <summary> Path to Content/Assets/ball.png </summary>
            public const string ball_png = "Content/Assets/ball.png";
            
            /// <summary> Path to Content/Assets/coin.spritesheet </summary>
            public const string coin_spritesheet = "Content/Assets/coin.spritesheet";
            
            /// <summary> Path to Content/Assets/joystickBackground.png </summary>
            public const string joystickBackground_png = "Content/Assets/joystickBackground.png";
            
            /// <summary> Path to Content/Assets/joystickThumb.png </summary>
            public const string joystickThumb_png = "Content/Assets/joystickThumb.png";
            
            /// <summary> Path to Content/Assets/map.tmx </summary>
            public const string map_tmx = "Content/Assets/map.tmx";
            
            /// <summary> Texture names from spritesheet Content/Assets/coin.spritesheet </summary>
            public struct coin_spritesheet_TextureName
            {
                
                public const string coin_0000_Capa_9 = "coin_0000_Capa-9";
                
                public const string coin_0001_Capa_8 = "coin_0001_Capa-8";
                
                public const string coin_0002_Capa_7 = "coin_0002_Capa-7";
                
                public const string coin_0003_Capa_6 = "coin_0003_Capa-6";
                
                public const string coin_0004_Capa_5 = "coin_0004_Capa-5";
                
                public const string coin_0005_Capa_4 = "coin_0005_Capa-4";
                
                public const string coin_0006_Capa_3 = "coin_0006_Capa-3";
                
                public const string coin_0007_Capa_2 = "coin_0007_Capa-2";
            }
            
            public sealed class Music
            {
                
                /// <summary> Path to Content/Assets/Music/Ozzed_-_A_Well_Worked_Analogy.mp3 </summary>
                public const string Ozzed___A_Well_Worked_Analogy_mp3 = "Content/Assets/Music/Ozzed_-_A_Well_Worked_Analogy.mp3";
            }
            
            public sealed class Sound
            {
                
                /// <summary> Path to Content/Assets/Sound/coin.wav </summary>
                public const string coin_wav = "Content/Assets/Sound/coin.wav";
                
                /// <summary> Path to Content/Assets/Sound/contact.wav </summary>
                public const string contact_wav = "Content/Assets/Sound/contact.wav";
                
                /// <summary> Path to Content/Assets/Sound/crash.wav </summary>
                public const string crash_wav = "Content/Assets/Sound/crash.wav";
                
                /// <summary> Path to Content/Assets/Sound/crateDrop.wav </summary>
                public const string crateDrop_wav = "Content/Assets/Sound/crateDrop.wav";
                
                /// <summary> Path to Content/Assets/Sound/jump.wav </summary>
                public const string jump_wav = "Content/Assets/Sound/jump.wav";
                
                /// <summary> Path to Content/Assets/Sound/victory.wav </summary>
                public const string victory_wav = "Content/Assets/Sound/victory.wav";
            }
            
            public sealed class tilesets
            {
                
                /// <summary> Path to Content/Assets/tilesets/background.png </summary>
                public const string background_png = "Content/Assets/tilesets/background.png";
                
                /// <summary> Path to Content/Assets/tilesets/sceneTiles.png </summary>
                public const string sceneTiles_png = "Content/Assets/tilesets/sceneTiles.png";
            }
        }
        
        public sealed class Scenes
        {
            
            /// <summary> Path to Content/Scenes/MyScene.wscene </summary>
            public const string MyScene = "Content/Scenes/MyScene.wscene";
        }
    }
}
