//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// File generated on 08/08/2017 14:14:40
namespace DolbyTest
{
    using System;
    
    
    public sealed class WaveContent
    {
        
        /// <summary> Path to Content/DolbyTest.wgame </summary>
        public const string GameInfo = "Content/DolbyTest.wgame";
        
        public sealed class Assets
        {
            
            /// <summary> Path to Content/Assets/met.mp3 </summary>
            public const string met_mp3 = "Content/Assets/met.mp3";
        }
        
        public sealed class Scenes
        {
            
            /// <summary> Path to Content/Scenes/MyScene.wscene </summary>
            public const string MyScene = "Content/Scenes/MyScene.wscene";
        }
    }
}
