//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// File generated on 11/09/2015 18:14:22
namespace RevoluteJoint2DSample
{
    using System;
    
    
    public sealed class WaveContent
    {
        
        public sealed class Assets
        {
            
            /// <summary> Path to Content/Assets/CrateA.png </summary>
            public const string CrateA_png = "Content/Assets/CrateA.png";
            
            /// <summary> Path to Content/Assets/CrateB.png </summary>
            public const string CrateB_png = "Content/Assets/CrateB.png";
            
            /// <summary> Path to Content/Assets/groundSprite.png </summary>
            public const string groundSprite_png = "Content/Assets/groundSprite.png";
            
            /// <summary> Path to Content/Assets/PinAzureA.png </summary>
            public const string PinAzureA_png = "Content/Assets/PinAzureA.png";
            
            /// <summary> Path to Content/Assets/PinAzureB.png </summary>
            public const string PinAzureB_png = "Content/Assets/PinAzureB.png";
            
            /// <summary> Path to Content/Assets/Wood20x5a.png </summary>
            public const string Wood20x5a_png = "Content/Assets/Wood20x5a.png";
            
            /// <summary> Path to Content/Assets/Wood20x5b.png </summary>
            public const string Wood20x5b_png = "Content/Assets/Wood20x5b.png";
            
            /// <summary> Path to Content/Assets/Wood20x5c.png </summary>
            public const string Wood20x5c_png = "Content/Assets/Wood20x5c.png";
        }
        
        public sealed class Scenes
        {
            
            /// <summary> Path to Content/Scenes/MyScene.wscene </summary>
            public const string MyScene = "Content/Scenes/MyScene.wscene";
        }
    }
}
