//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// File generated on 22/08/2016 14:33:31
namespace Buoyancy
{
    using System;
    
    
    public sealed class WaveContent
    {
        
        public sealed class Assets
        {
            
            /// <summary> Path to Content/Assets/alienBeige_square.png </summary>
            public const string alienBeige_square_png = "Content/Assets/alienBeige_square.png";
            
            /// <summary> Path to Content/Assets/alienGreen_square.png </summary>
            public const string alienGreen_square_png = "Content/Assets/alienGreen_square.png";
            
            /// <summary> Path to Content/Assets/alienPink_square.png </summary>
            public const string alienPink_square_png = "Content/Assets/alienPink_square.png";
            
            /// <summary> Path to Content/Assets/alienYellow_square.png </summary>
            public const string alienYellow_square_png = "Content/Assets/alienYellow_square.png";
            
            /// <summary> Path to Content/Assets/blue_land.png </summary>
            public const string blue_land_png = "Content/Assets/blue_land.png";
            
            /// <summary> Path to Content/Assets/debrisWood_2.png </summary>
            public const string debrisWood_2_png = "Content/Assets/debrisWood_2.png";
            
            /// <summary> Path to Content/Assets/elementStone025.png </summary>
            public const string elementStone025_png = "Content/Assets/elementStone025.png";
            
            /// <summary> Path to Content/Assets/elementWood012.png </summary>
            public const string elementWood012_png = "Content/Assets/elementWood012.png";
            
            /// <summary> Path to Content/Assets/ground.png </summary>
            public const string ground_png = "Content/Assets/ground.png";
            
            /// <summary> Path to Content/Assets/water.png </summary>
            public const string water_png = "Content/Assets/water.png";
        }
        
        public sealed class Scenes
        {
            
            /// <summary> Path to Content/Scenes/MyScene.wscene </summary>
            public const string MyScene = "Content/Scenes/MyScene.wscene";
        }
    }
}
