//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// File generated on 17/04/2018 15:30:31
namespace Buoyancy
{
    using System;
    
    
    public sealed class WaveContent
    {
        
        /// <summary> Path to Content/Buoyancy.wgame </summary>
        public const string GameInfo = "Content/Buoyancy.wgame";
        
        public sealed class Assets
        {
            
            /// <summary> Path to Content/Assets/alienBeige_square.png </summary>
            public const string alienBeige_square_png = "Content/Assets/alienBeige_square.png";
            
            /// <summary> Path to Content/Assets/alienGreen_square.png </summary>
            public const string alienGreen_square_png = "Content/Assets/alienGreen_square.png";
            
            /// <summary> Path to Content/Assets/alienPink_square.png </summary>
            public const string alienPink_square_png = "Content/Assets/alienPink_square.png";
            
            /// <summary> Path to Content/Assets/alienYellow_square.png </summary>
            public const string alienYellow_square_png = "Content/Assets/alienYellow_square.png";
            
            /// <summary> Path to Content/Assets/blue_land.png </summary>
            public const string blue_land_png = "Content/Assets/blue_land.png";
            
            /// <summary> Path to Content/Assets/debrisWood_2.png </summary>
            public const string debrisWood_2_png = "Content/Assets/debrisWood_2.png";
            
            /// <summary> Path to Content/Assets/elementStone025.png </summary>
            public const string elementStone025_png = "Content/Assets/elementStone025.png";
            
            /// <summary> Path to Content/Assets/elementWood012.png </summary>
            public const string elementWood012_png = "Content/Assets/elementWood012.png";
            
            /// <summary> Path to Content/Assets/ground.png </summary>
            public const string ground_png = "Content/Assets/ground.png";
            
            /// <summary> Path to Content/Assets/water.png </summary>
            public const string water_png = "Content/Assets/water.png";
        }
        
        public sealed class RenderLayers
        {
            
            /// <summary>Id of Opaque</summary>
            public const int Opaque = 0;
            
            /// <summary>Id of Skybox</summary>
            public const int Skybox = 1;
            
            /// <summary>Id of Alpha</summary>
            public const int Alpha = 2;
            
            /// <summary>Id of Additive</summary>
            public const int Additive = 3;
            
            /// <summary>Id of GUI</summary>
            public const int GUI = 4;
            
            /// <summary>Id of Debug</summary>
            public const int Debug = 5;
        }
        
        public sealed class Scenes
        {
            
            /// <summary> Path to Content/Scenes/MyScene.wscene </summary>
            public const string MyScene = "Content/Scenes/MyScene.wscene";
            
            /// <summary> Path to Content/Scenes/MyScene01.wscene </summary>
            public const string MyScene01 = "Content/Scenes/MyScene01.wscene";
        }
    }
}
