//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// File generated on 24-May-18 13:32:38
namespace CameraRenderTarget
{
    using System;
    
    
    public sealed class WaveContent
    {
        
        /// <summary> Path to Content/CameraRenderTarget.wgame </summary>
        public const string GameInfo = "Content/CameraRenderTarget.wgame";
        
        public sealed class Assets
        {
            
            public sealed class Models
            {
                
                /// <summary> Path to Content/Assets/Models/isis.fbx </summary>
                public const string isis_fbx = "Content/Assets/Models/isis.fbx";
                
                /// <summary> Path to Content/Assets/Models/Stage.fbx </summary>
                public const string Stage_fbx = "Content/Assets/Models/Stage.fbx";
            }
            
            public sealed class Textures
            {
                
                /// <summary> Path to Content/Assets/Textures/isis-difuse.png </summary>
                public const string isis_difuse_png = "Content/Assets/Textures/isis-difuse.png";
                
                /// <summary> Path to Content/Assets/Textures/isis-normal.png </summary>
                public const string isis_normal_png = "Content/Assets/Textures/isis-normal.png";
                
                /// <summary> Path to Content/Assets/Textures/isis-spec.png </summary>
                public const string isis_spec_png = "Content/Assets/Textures/isis-spec.png";
                
                /// <summary> Path to Content/Assets/Textures/stageCeiling_Diffuse.png </summary>
                public const string stageCeiling_Diffuse_png = "Content/Assets/Textures/stageCeiling_Diffuse.png";
                
                /// <summary> Path to Content/Assets/Textures/stageDoor_Diffuse.png </summary>
                public const string stageDoor_Diffuse_png = "Content/Assets/Textures/stageDoor_Diffuse.png";
                
                /// <summary> Path to Content/Assets/Textures/stageFloor_Diffuse.png </summary>
                public const string stageFloor_Diffuse_png = "Content/Assets/Textures/stageFloor_Diffuse.png";
                
                /// <summary> Path to Content/Assets/Textures/stageLightingMap.png </summary>
                public const string stageLightingMap_png = "Content/Assets/Textures/stageLightingMap.png";
                
                /// <summary> Path to Content/Assets/Textures/stageWall2_Diffuse.png </summary>
                public const string stageWall2_Diffuse_png = "Content/Assets/Textures/stageWall2_Diffuse.png";
                
                /// <summary> Path to Content/Assets/Textures/stageWall_Diffuse.png </summary>
                public const string stageWall_Diffuse_png = "Content/Assets/Textures/stageWall_Diffuse.png";
            }
            
            public sealed class Materials
            {
                
                /// <summary> Path to Content/Assets/Materials/CeilingMaterial.wmat </summary>
                public const string CeilingMaterial = "Content/Assets/Materials/CeilingMaterial.wmat";
                
                /// <summary> Path to Content/Assets/Materials/DoorMaterial.wmat </summary>
                public const string DoorMaterial = "Content/Assets/Materials/DoorMaterial.wmat";
                
                /// <summary> Path to Content/Assets/Materials/FloorMaterial.wmat </summary>
                public const string FloorMaterial = "Content/Assets/Materials/FloorMaterial.wmat";
                
                /// <summary> Path to Content/Assets/Materials/IsisMaterial.wmat </summary>
                public const string IsisMaterial = "Content/Assets/Materials/IsisMaterial.wmat";
                
                /// <summary> Path to Content/Assets/Materials/securityCam1Material.wmat </summary>
                public const string securityCam1Material = "Content/Assets/Materials/securityCam1Material.wmat";
                
                /// <summary> Path to Content/Assets/Materials/securityCam2Material.wmat </summary>
                public const string securityCam2Material = "Content/Assets/Materials/securityCam2Material.wmat";
                
                /// <summary> Path to Content/Assets/Materials/SecurityCam3Material.wmat </summary>
                public const string SecurityCam3Material = "Content/Assets/Materials/SecurityCam3Material.wmat";
                
                /// <summary> Path to Content/Assets/Materials/StageWall2Material.wmat </summary>
                public const string StageWall2Material = "Content/Assets/Materials/StageWall2Material.wmat";
                
                /// <summary> Path to Content/Assets/Materials/StageWallMaterial.wmat </summary>
                public const string StageWallMaterial = "Content/Assets/Materials/StageWallMaterial.wmat";
            }
        }
        
        public sealed class RenderLayers
        {
            
            /// <summary>Id of Opaque</summary>
            public const int Opaque = 0;
            
            /// <summary>Id of Skybox</summary>
            public const int Skybox = 1;
            
            /// <summary>Id of Alpha</summary>
            public const int Alpha = 2;
            
            /// <summary>Id of Additive</summary>
            public const int Additive = 3;
            
            /// <summary>Id of GUI</summary>
            public const int GUI = 4;
            
            /// <summary>Id of Debug</summary>
            public const int Debug = 5;
        }
        
        public sealed class Scenes
        {
            
            /// <summary> Path to Content/Scenes/MyScene.wscene </summary>
            public const string MyScene = "Content/Scenes/MyScene.wscene";
        }
    }
}
