//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// File generated on 9/11/2015 7:04:56 PM
namespace CameraRengerTarget
{
    using System;
    
    
    public sealed class WaveContent
    {
        
        public sealed class Assets
        {
            
            public sealed class Models
            {
                
                /// <summary> Path to Content/Assets/Models/isis </summary>
                public const string isis = "Content/Assets/Models/isis";
                
                /// <summary> Path to Content/Assets/Models/Stage </summary>
                public const string Stage = "Content/Assets/Models/Stage";
            }
            
            public sealed class Textures
            {
                
                /// <summary> Path to Content/Assets/Textures/isis-difuse </summary>
                public const string isis_difuse = "Content/Assets/Textures/isis-difuse";
                
                /// <summary> Path to Content/Assets/Textures/isis-normal </summary>
                public const string isis_normal = "Content/Assets/Textures/isis-normal";
                
                /// <summary> Path to Content/Assets/Textures/stageCeiling_Diffuse </summary>
                public const string stageCeiling_Diffuse = "Content/Assets/Textures/stageCeiling_Diffuse";
                
                /// <summary> Path to Content/Assets/Textures/stageCeiling_NormSpec </summary>
                public const string stageCeiling_NormSpec = "Content/Assets/Textures/stageCeiling_NormSpec";
                
                /// <summary> Path to Content/Assets/Textures/stageDoor_Diffuse </summary>
                public const string stageDoor_Diffuse = "Content/Assets/Textures/stageDoor_Diffuse";
                
                /// <summary> Path to Content/Assets/Textures/stageDoor_NormSpec </summary>
                public const string stageDoor_NormSpec = "Content/Assets/Textures/stageDoor_NormSpec";
                
                /// <summary> Path to Content/Assets/Textures/stageFloor_Diffuse </summary>
                public const string stageFloor_Diffuse = "Content/Assets/Textures/stageFloor_Diffuse";
                
                /// <summary> Path to Content/Assets/Textures/stageFloor_NormSpec </summary>
                public const string stageFloor_NormSpec = "Content/Assets/Textures/stageFloor_NormSpec";
                
                /// <summary> Path to Content/Assets/Textures/stageLightingMap </summary>
                public const string stageLightingMap = "Content/Assets/Textures/stageLightingMap";
                
                /// <summary> Path to Content/Assets/Textures/stageWall2_Diffuse </summary>
                public const string stageWall2_Diffuse = "Content/Assets/Textures/stageWall2_Diffuse";
                
                /// <summary> Path to Content/Assets/Textures/stageWall2_NormSpec </summary>
                public const string stageWall2_NormSpec = "Content/Assets/Textures/stageWall2_NormSpec";
                
                /// <summary> Path to Content/Assets/Textures/stageWall_Diffuse </summary>
                public const string stageWall_Diffuse = "Content/Assets/Textures/stageWall_Diffuse";
                
                /// <summary> Path to Content/Assets/Textures/stageWall_NormSpec </summary>
                public const string stageWall_NormSpec = "Content/Assets/Textures/stageWall_NormSpec";
            }
            
            public sealed class Materials
            {
                
                /// <summary> Path to Content/Assets/Materials/CeilingMaterial.wmat </summary>
                public const string CeilingMaterial = "Content/Assets/Materials/CeilingMaterial.wmat";
                
                /// <summary> Path to Content/Assets/Materials/DoorMaterial.wmat </summary>
                public const string DoorMaterial = "Content/Assets/Materials/DoorMaterial.wmat";
                
                /// <summary> Path to Content/Assets/Materials/FloorMaterial.wmat </summary>
                public const string FloorMaterial = "Content/Assets/Materials/FloorMaterial.wmat";
                
                /// <summary> Path to Content/Assets/Materials/IsisMaterial.wmat </summary>
                public const string IsisMaterial = "Content/Assets/Materials/IsisMaterial.wmat";
                
                /// <summary> Path to Content/Assets/Materials/securityCam1Material.wmat </summary>
                public const string securityCam1Material = "Content/Assets/Materials/securityCam1Material.wmat";
                
                /// <summary> Path to Content/Assets/Materials/securityCam2Material.wmat </summary>
                public const string securityCam2Material = "Content/Assets/Materials/securityCam2Material.wmat";
                
                /// <summary> Path to Content/Assets/Materials/SecurityCam3Material.wmat </summary>
                public const string SecurityCam3Material = "Content/Assets/Materials/SecurityCam3Material.wmat";
                
                /// <summary> Path to Content/Assets/Materials/StageWall2Material.wmat </summary>
                public const string StageWall2Material = "Content/Assets/Materials/StageWall2Material.wmat";
                
                /// <summary> Path to Content/Assets/Materials/StageWallMaterial.wmat </summary>
                public const string StageWallMaterial = "Content/Assets/Materials/StageWallMaterial.wmat";
            }
        }
        
        public sealed class Scenes
        {
            
            /// <summary> Path to Content/Scenes/MyScene.wscene </summary>
            public const string MyScene = "Content/Scenes/MyScene.wscene";
        }
    }
}
