// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

// File generated on 07/09/2016 10:32:17
namespace CardboardCockpit
{
    using System;
    
    
    public sealed class WaveContent
    {
        
        public sealed class Assets
        {
            
            public sealed class Model
            {
                
                /// <summary> Path to Content/Assets/Model/ShoperCockpit.fbx </summary>
                public const string ShoperCockpit_fbx = "Content/Assets/Model/ShoperCockpit.fbx";
            }
            
            public sealed class Sounds
            {
                
                /// <summary> Path to Content/Assets/Sounds/helicopter.wav </summary>
                public const string helicopter_wav = "Content/Assets/Sounds/helicopter.wav";
            }
            
            public sealed class Texture
            {
                
                /// <summary> Path to Content/Assets/Texture/Skybox.cubemap </summary>
                public const string Skybox_cubemap = "Content/Assets/Texture/Skybox.cubemap";
                
                /// <summary> Path to Content/Assets/Texture/fuse.png </summary>
                public const string fuse_png = "Content/Assets/Texture/fuse.png";
                
                /// <summary> Path to Content/Assets/Texture/gazelle_interior.png </summary>
                public const string gazelle_interior_png = "Content/Assets/Texture/gazelle_interior.png";
                
                /// <summary> Path to Content/Assets/Texture/inn.png </summary>
                public const string inn_png = "Content/Assets/Texture/inn.png";
                
                /// <summary> Path to Content/Assets/Texture/interior04LightingMap.png </summary>
                public const string interior04LightingMap_png = "Content/Assets/Texture/interior04LightingMap.png";
            }
            
            public sealed class Materials
            {
                
                /// <summary> Path to Content/Assets/Materials/Fuse.wmat </summary>
                public const string Fuse = "Content/Assets/Materials/Fuse.wmat";
                
                /// <summary> Path to Content/Assets/Materials/Instruments.wmat </summary>
                public const string Instruments = "Content/Assets/Materials/Instruments.wmat";
                
                /// <summary> Path to Content/Assets/Materials/Interior.wmat </summary>
                public const string Interior = "Content/Assets/Materials/Interior.wmat";
            }
        }
        
        public sealed class Scenes
        {
            
            /// <summary> Path to Content/Scenes/MyScene.wscene </summary>
            public const string MyScene = "Content/Scenes/MyScene.wscene";
        }
    }
}
