//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CardboardCockpit
{
    public sealed class WaveContent
    {
        /// <summary> Path to Content/GameInfo.wgame </summary>
        public const string GameInfo = "Content/CardboardCockpit.wgame";

        public sealed class Scenes
        {
            /// <summary> Path to Content/Scenes/MyScene.wscene </summary>
            public const string MyScene = "Content/Scenes/MyScene.wscene";
        }
    }
}
