//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// File generated on 20/08/2015 15:31:27
namespace IsisTemple
{
    using System;
    
    
    public sealed class WaveContent
    {
        
        public sealed class Assets
        {
            
            public sealed class Models
            {
                
                /// <summary> Path to Content/Assets/Models/column1.FBX </summary>
                public const string column1_FBX = "Content/Assets/Models/column1.FBX";
                
                /// <summary> Path to Content/Assets/Models/column2.FBX </summary>
                public const string column2_FBX = "Content/Assets/Models/column2.FBX";
                
                /// <summary> Path to Content/Assets/Models/floor.FBX </summary>
                public const string floor_FBX = "Content/Assets/Models/floor.FBX";
                
                /// <summary> Path to Content/Assets/Models/isis.FBX </summary>
                public const string isis_FBX = "Content/Assets/Models/isis.FBX";
            }
            
            public sealed class Textures
            {
                
                /// <summary> Path to Content/Assets/Textures/column1_diffuse.png </summary>
                public const string column1_diffuse_png = "Content/Assets/Textures/column1_diffuse.png";
                
                /// <summary> Path to Content/Assets/Textures/column1_normal.png </summary>
                public const string column1_normal_png = "Content/Assets/Textures/column1_normal.png";
                
                /// <summary> Path to Content/Assets/Textures/column1_spec.png </summary>
                public const string column1_spec_png = "Content/Assets/Textures/column1_spec.png";
                
                /// <summary> Path to Content/Assets/Textures/column2_diffuse.png </summary>
                public const string column2_diffuse_png = "Content/Assets/Textures/column2_diffuse.png";
                
                /// <summary> Path to Content/Assets/Textures/column2_normal.png </summary>
                public const string column2_normal_png = "Content/Assets/Textures/column2_normal.png";
                
                /// <summary> Path to Content/Assets/Textures/column2_spec.png </summary>
                public const string column2_spec_png = "Content/Assets/Textures/column2_spec.png";
                
                /// <summary> Path to Content/Assets/Textures/floor1_diffuse.png </summary>
                public const string floor1_diffuse_png = "Content/Assets/Textures/floor1_diffuse.png";
                
                /// <summary> Path to Content/Assets/Textures/floor1_normal.png </summary>
                public const string floor1_normal_png = "Content/Assets/Textures/floor1_normal.png";
                
                /// <summary> Path to Content/Assets/Textures/floor1_spec.png </summary>
                public const string floor1_spec_png = "Content/Assets/Textures/floor1_spec.png";
                
                /// <summary> Path to Content/Assets/Textures/isis_diffuse.png </summary>
                public const string isis_diffuse_png = "Content/Assets/Textures/isis_diffuse.png";
                
                /// <summary> Path to Content/Assets/Textures/isis_normal.png </summary>
                public const string isis_normal_png = "Content/Assets/Textures/isis_normal.png";
                
                /// <summary> Path to Content/Assets/Textures/isis_spec.png </summary>
                public const string isis_spec_png = "Content/Assets/Textures/isis_spec.png";
                
                /// <summary> Path to Content/Assets/Textures/JoystickButton.png </summary>
                public const string JoystickButton_png = "Content/Assets/Textures/JoystickButton.png";
                
                /// <summary> Path to Content/Assets/Textures/ShiftButton.png </summary>
                public const string ShiftButton_png = "Content/Assets/Textures/ShiftButton.png";
            }
            
            public sealed class Materials
            {
                
                /// <summary> Path to Content/Assets/Materials/Column1Material.wmat </summary>
                public const string Column1Material = "Content/Assets/Materials/Column1Material.wmat";
                
                /// <summary> Path to Content/Assets/Materials/Column2Material.wmat </summary>
                public const string Column2Material = "Content/Assets/Materials/Column2Material.wmat";
                
                /// <summary> Path to Content/Assets/Materials/FloorMaterial.wmat </summary>
                public const string FloorMaterial = "Content/Assets/Materials/FloorMaterial.wmat";
                
                /// <summary> Path to Content/Assets/Materials/IsisMaterial.wmat </summary>
                public const string IsisMaterial = "Content/Assets/Materials/IsisMaterial.wmat";
            }
        }
        
        public sealed class Scenes
        {
            
            /// <summary> Path to Content/Scenes/MyScene.wscene </summary>
            public const string MyScene = "Content/Scenes/MyScene.wscene";
        }
    }
}
