//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// File generated on 13/09/2015 11:40:27
namespace IBLSample
{
    using System;
    
    
    public sealed class WaveContent
    {
        
        public sealed class Assets
        {
            
            /// <summary> Path to Content/Assets/Environment1.cubemap </summary>
            public const string Environment1_cubemap = "Content/Assets/Environment1.cubemap";
            
            /// <summary> Path to Content/Assets/Environment1Light.cubemap </summary>
            public const string Environment1Light_cubemap = "Content/Assets/Environment1Light.cubemap";
            
            /// <summary> Path to Content/Assets/Environment2.cubemap </summary>
            public const string Environment2_cubemap = "Content/Assets/Environment2.cubemap";
            
            /// <summary> Path to Content/Assets/Environment2Light.cubemap </summary>
            public const string Environment2Light_cubemap = "Content/Assets/Environment2Light.cubemap";
            
            /// <summary> Path to Content/Assets/Environment3.cubemap </summary>
            public const string Environment3_cubemap = "Content/Assets/Environment3.cubemap";
            
            /// <summary> Path to Content/Assets/Environment3Light.cubemap </summary>
            public const string Environment3Light_cubemap = "Content/Assets/Environment3Light.cubemap";
            
            /// <summary> Path to Content/Assets/venusLightingMap.jpg </summary>
            public const string venusLightingMap_jpg = "Content/Assets/venusLightingMap.jpg";
            
            public sealed class Models
            {
                
                /// <summary> Path to Content/Assets/Models/venus.fbx </summary>
                public const string venus_fbx = "Content/Assets/Models/venus.fbx";
            }
            
            public sealed class Materials
            {
                
                /// <summary> Path to Content/Assets/Materials/Environment1.wmat </summary>
                public const string Environment1 = "Content/Assets/Materials/Environment1.wmat";
                
                /// <summary> Path to Content/Assets/Materials/Environment2.wmat </summary>
                public const string Environment2 = "Content/Assets/Materials/Environment2.wmat";
                
                /// <summary> Path to Content/Assets/Materials/Environment3.wmat </summary>
                public const string Environment3 = "Content/Assets/Materials/Environment3.wmat";
            }
        }
        
        public sealed class Scenes
        {
            
            /// <summary> Path to Content/Scenes/MyScene.wscene </summary>
            public const string MyScene = "Content/Scenes/MyScene.wscene";
        }
    }
}
