//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// File generated on 19/04/2018 15:34:03
namespace IBLSample
{
    using System;
    
    
    public sealed class WaveContent
    {
        
        /// <summary> Path to Content/IBLSample.wgame </summary>
        public const string GameInfo = "Content/IBLSample.wgame";
        
        public sealed class Assets
        {
            
            /// <summary> Path to Content/Assets/Environment1.cubemap </summary>
            public const string Environment1_cubemap = "Content/Assets/Environment1.cubemap";
            
            /// <summary> Path to Content/Assets/Environment1Light.cubemap </summary>
            public const string Environment1Light_cubemap = "Content/Assets/Environment1Light.cubemap";
            
            /// <summary> Path to Content/Assets/Environment2.cubemap </summary>
            public const string Environment2_cubemap = "Content/Assets/Environment2.cubemap";
            
            /// <summary> Path to Content/Assets/Environment2Light.cubemap </summary>
            public const string Environment2Light_cubemap = "Content/Assets/Environment2Light.cubemap";
            
            /// <summary> Path to Content/Assets/Environment3.cubemap </summary>
            public const string Environment3_cubemap = "Content/Assets/Environment3.cubemap";
            
            /// <summary> Path to Content/Assets/Environment3Light.cubemap </summary>
            public const string Environment3Light_cubemap = "Content/Assets/Environment3Light.cubemap";
            
            /// <summary> Path to Content/Assets/venus.fbx </summary>
            public const string venus_fbx = "Content/Assets/venus.fbx";
            
            /// <summary> Path to Content/Assets/venusLightingMap.png </summary>
            public const string venusLightingMap_png = "Content/Assets/venusLightingMap.png";
            
            public sealed class Materials
            {
                
                /// <summary> Path to Content/Assets/Materials/Environment1.wmat </summary>
                public const string Environment1 = "Content/Assets/Materials/Environment1.wmat";
                
                /// <summary> Path to Content/Assets/Materials/Environment2.wmat </summary>
                public const string Environment2 = "Content/Assets/Materials/Environment2.wmat";
                
                /// <summary> Path to Content/Assets/Materials/Environment3.wmat </summary>
                public const string Environment3 = "Content/Assets/Materials/Environment3.wmat";
                
                /// <summary> Path to Content/Assets/Materials/venus.wmat </summary>
                public const string venus = "Content/Assets/Materials/venus.wmat";
            }
        }
        
        public sealed class RenderLayers
        {
            
            /// <summary>Id of Opaque</summary>
            public const int Opaque = 0;
            
            /// <summary>Id of Skybox</summary>
            public const int Skybox = 1;
            
            /// <summary>Id of Alpha</summary>
            public const int Alpha = 2;
            
            /// <summary>Id of Additive</summary>
            public const int Additive = 3;
            
            /// <summary>Id of GUI</summary>
            public const int GUI = 4;
            
            /// <summary>Id of Debug</summary>
            public const int Debug = 5;
        }
        
        public sealed class Scenes
        {
            
            /// <summary> Path to Content/Scenes/MyScene.wscene </summary>
            public const string MyScene = "Content/Scenes/MyScene.wscene";
        }
    }
}
