//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// File generated on 26/01/2016 15:10:30
namespace XBoxController
{
    using System;
    
    
    public sealed class WaveContent
    {
        
        public sealed class Assets
        {
            
            /// <summary> Path to Content/Assets/Buttons.spritesheet </summary>
            public const string Buttons_spritesheet = "Content/Assets/Buttons.spritesheet";
            
            /// <summary> Path to Content/Assets/FrontController.png </summary>
            public const string FrontController_png = "Content/Assets/FrontController.png";
            
            /// <summary> Path to Content/Assets/TopController.png </summary>
            public const string TopController_png = "Content/Assets/TopController.png";
            
            /// <summary> Texture names from spritesheet Content/Assets/Buttons.spritesheet </summary>
            public struct Buttons_spritesheet_TextureName
            {
                
                public const string circlePressed = "circlePressed";
                
                public const string DPad = "DPad";
                
                public const string JoyStick = "JoyStick";
                
                public const string JoyStickPressed = "JoyStickPressed";
                
                public const string LeftShoulderPressed = "LeftShoulderPressed";
                
                public const string LeftTrigger = "LeftTrigger";
                
                public const string rectangularPressed = "rectangularPressed";
                
                public const string RightShoulder = "RightShoulder";
                
                public const string RightTrigger = "RightTrigger";
            }
        }
        
        public sealed class Scenes
        {
            
            /// <summary> Path to Content/Scenes/MyScene.wscene </summary>
            public const string MyScene = "Content/Scenes/MyScene.wscene";
        }
    }
}
