//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// File generated on 28/10/2015 17:45:41
namespace TeapotSample
{
    using System;
    
    
    public sealed class WaveContent
    {
        
        public sealed class Assets
        {
            
            public sealed class Textures
            {
                
                /// <summary> Path to Content/Assets/Textures/metal_diffuse.png </summary>
                public const string metal_diffuse_png = "Content/Assets/Textures/metal_diffuse.png";
                
                /// <summary> Path to Content/Assets/Textures/metal_normal.png </summary>
                public const string metal_normal_png = "Content/Assets/Textures/metal_normal.png";
            }
            
            public sealed class Materials
            {
                
                /// <summary> Path to Content/Assets/Materials/MetalMaterial.wmat </summary>
                public const string MetalMaterial = "Content/Assets/Materials/MetalMaterial.wmat";
            }
        }
        
        public sealed class Scenes
        {
            
            /// <summary> Path to Content/Scenes/MyScene.wscene </summary>
            public const string MyScene = "Content/Scenes/MyScene.wscene";
        }
    }
}
