//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// File generated on 19/04/2018 17:12:12
namespace GUIIntegrations
{
    using System;
    
    
    public sealed class WaveContent
    {
        
        /// <summary> Path to Content/GUIIntegrations.wgame </summary>
        public const string GameInfo = "Content/GUIIntegrations.wgame";
        
        public sealed class Assets
        {
            
            public sealed class Textures
            {
                
                /// <summary> Path to Content/Assets/Textures/metal_diffuse.png </summary>
                public const string metal_diffuse_png = "Content/Assets/Textures/metal_diffuse.png";
                
                /// <summary> Path to Content/Assets/Textures/metal_normal.png </summary>
                public const string metal_normal_png = "Content/Assets/Textures/metal_normal.png";
            }
            
            public sealed class Materials
            {
                
                /// <summary> Path to Content/Assets/Materials/MyMaterial.wmat </summary>
                public const string MyMaterial = "Content/Assets/Materials/MyMaterial.wmat";
            }
        }
        
        public sealed class RenderLayers
        {
            
            /// <summary>Id of Opaque</summary>
            public const int Opaque = 0;
            
            /// <summary>Id of Skybox</summary>
            public const int Skybox = 1;
            
            /// <summary>Id of Alpha</summary>
            public const int Alpha = 2;
            
            /// <summary>Id of Additive</summary>
            public const int Additive = 3;
            
            /// <summary>Id of GUI</summary>
            public const int GUI = 4;
            
            /// <summary>Id of Debug</summary>
            public const int Debug = 5;
        }
        
        public sealed class Scenes
        {
            
            /// <summary> Path to Content/Scenes/MyScene.wscene </summary>
            public const string MyScene = "Content/Scenes/MyScene.wscene";
        }
    }
}
