// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

// File generated on 1/18/2016 4:03:11 AM
namespace AngleJoint2D
{
    using System;
    
    
    public sealed class WaveContent
    {
        
        public sealed class Assets
        {
            
            /// <summary> Path to Content/Assets/Crate.png </summary>
            public const string Crate_png = "Content/Assets/Crate.png";
            
            /// <summary> Path to Content/Assets/Ground.png </summary>
            public const string Ground_png = "Content/Assets/Ground.png";
            
            /// <summary> Path to Content/Assets/Pin.png </summary>
            public const string Pin_png = "Content/Assets/Pin.png";
            
            /// <summary> Path to Content/Assets/Wheel.png </summary>
            public const string Wheel_png = "Content/Assets/Wheel.png";
        }
        
        public sealed class Scenes
        {
            
            /// <summary> Path to Content/Scenes/MyScene.wscene </summary>
            public const string MyScene = "Content/Scenes/MyScene.wscene";
        }
    }
}
